### ISSUE TITLE
Problem importing .hom file on Apple mobile devices

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#1018]
[I thought I had already created this issue but now I can't find it. Apologies if this is a duplicate.]

Chris Heunen writes: "when I save one of the .hom example files on an ipad (so in iOS), [homotopy.io](http://homotopy.io/) nor [beta.homotopy.io](http://beta.homotopy.io/) wants to import it. I can see the file but it's grayed out so can't select it. Probably a silly ui bug but crippling. :)"

**Comment by calintat** [comment]
I've noticed this too, not sure why it isn't working.

**Comment by regular-citizen** [comment]
Think we need to add the correct mime type here

https://github.com/homotopy-io/homotopy-rs/blob/355ca30f17e4de27ab1b692e9998dd06599b4efd/homotopy-web/src/app/project.rs#L57

I think ```application/octet-stream``` should do the job.

**Comment by calintat** [comment]
Fixed by f8290de0f936a7f1b8b2849ef2c3e1cc14477008, thanks Chiara!
