### ISSUE TITLE
Efficient cube/plane intersection rendering

### ISSUE THREAD

**Issue by doctorn** [homotopy-io/homotopy-rs#104]
(I'm going to have a serious look at the theory of this today and will write up where I get to.)

**Comment by jamievicary** [comment]
Thanks for the discussion earlier on this Nathan.

I have been reading a bit about vertex, geometry and pixel shaders. My
fairly limited understanding is:

  - the vertex shader updates the coordinates of the vertices;
  - the geometry shader updates the geometry, possibly adding additional
elements;
  - the fragment shader renders the pixels.

So a natural approach could be to pass the *cubes themselves* as the
geometrical elements, and the *cube edges* as the points. The vertex shader
can update the point coordinates as appropriate to the current time frame.
We then use the geometry shader to intersect the actual cubes, creating the
actual triangles to be rendered as necessary.

The only issue I can foresee is that our cubes are defined by an 8-tuple of
points, not a 3-tuple. Can a geometry shader handle this?

(There could be many additional issues I cannot foresee.)

**Comment by zrho** [comment]
IIRC webgl does not support geometry shaders, much to my dismay back then when I was implementing subdivision. I think webgpu will have something like this, but widespread support for webgpu probably won't come for quite some time.

**Comment by jamievicary** [comment]
Ah damn.

**Comment by jamievicary** [comment]
This is pretty impressive: https://acko.net/blog/yak-shading/
