### ISSUE TITLE
Signature panel doesn't auto-open on keyboard shortcuts

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#105]
Immediately after loading the application, all the panels are closed. If you click the 'Add generator' button, it will add the generator and then open the signature panel. However, if you press 'a' the generator gets added but the panel doesn't open.

**Comment by doctorn** [comment]
This is my fault - I'll fix this next week

**Comment by jamievicary** [comment]
bump!

**Comment by doctorn** [comment]
Closed by #111
