### ISSUE TITLE
Fail of contracting an isolated singularity

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#108]
When the following singularity is created in the homotopy.io, I experience crack-down when I try to resolve this singularity by dragging the singularity to the left in the 3-cell level (i.e. pic3).

**Screenshots:**
![image](https://user-images.githubusercontent.com/35509721/124470099-16f4b900-dd93-11eb-9471-e4cf45c48408.png)
_pic1. 4-cell_
![image](https://user-images.githubusercontent.com/35509721/124470247-4b687500-dd93-11eb-8cf2-c61b724b9382.png)
_pic2. source/target 3-cells_
![image](https://user-images.githubusercontent.com/35509721/124470338-6804ad00-dd93-11eb-97f4-f5c2d0c609cb.png)
_pic3. singular 3-cell_

**Project Demo:**
[bug-isolated singularity.zip](https://github.com/homotopy-io/homotopy-rs/files/6764071/bug-isolated.singularity.zip)

**Error report 1:**
> panicked at 'called `Option::unwrap()` on a `None` value', homotopy-web/src/model/proof.rs:76:67
> Stack:
> Error
>    at W (https://beta.homotopy.io/235.js:1:9276)
>     at console_error_panic_hook::hook::h6aba13f31c7bca6d (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[909]:0x14342f)
>     at core::ops::function::Fn::call::hf988c63c6d1134ec (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2629]:0x193f00)
>     at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[1689]:0x181eee)
>     at std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[1865]:0x189e4c)
>     at std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2200]:0x1919eb)
>     at rust_begin_unwind (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2143]:0x190e21)
>     at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2201]:0x191a21)
>     at core::panicking::panic::h5bfdfaa3db9a4b4a (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2110]:0x1905ba)
>     at homotopy_web::model::proof::Workspace::visible_diagram::h54414cbf24a26ba7 (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[481]:0xfdea5)

> j @ 235.js:1
> d717dc4f4045fce763cd.module.wasm:0x194133 Uncaught RuntimeError: unreachable
>     at __rust_start_panic (d717dc4f4045fce763cd.module.wasm:0x194133)
>     at rust_panic (d717dc4f4045fce763cd.module.wasm:0x192128)
>    at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (d717dc4f4045fce763cd.module.wasm:0x181f12)
>     at std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 (d717dc4f4045fce763cd.module.wasm:0x189e4c)
>     at std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 (d717dc4f4045fce763cd.module.wasm:0x1919eb)
>    at rust_begin_unwind (d717dc4f4045fce763cd.module.wasm:0x190e21)
>    at core::panicking::panic_fmt::h3ab5417155b7ba3b (d717dc4f4045fce763cd.module.wasm:0x191a21)
>    at core::panicking::panic::h5bfdfaa3db9a4b4a (d717dc4f4045fce763cd.module.wasm:0x1905ba)
>     at homotopy_web::model::proof::Workspace::visible_diagram::h54414cbf24a26ba7 (d717dc4f4045fce763cd.module.wasm:0xfdea5)
 >    at <homotopy_web::app::workspace::WorkspaceView as yew::html::component::Component>::view::h10f65cc44fe708aa (d717dc4f4045fce763cd.module.wasm:0x10875)

**Error report 2:**
> 235.js:1 panicked at 'called `Option::unwrap()` on a `None` value', homotopy-web/src/model/proof.rs:76:67
> Stack:
> Error
>     at W (https://beta.homotopy.io/235.js:1:9276)
>     at console_error_panic_hook::hook::h6aba13f31c7bca6d (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[909]:0x14342f)
>     at core::ops::function::Fn::call::hf988c63c6d1134ec (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2629]:0x193f00)
>     at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[1689]:0x181eee)
>     at std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[1865]:0x189e4c)
>     at std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2200]:0x1919eb)
>     at rust_begin_unwind (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2143]:0x190e21)
>     at core::panicking::panic_fmt::h3ab5417155b7ba3b (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2201]:0x191a21)
>     at core::panicking::panic::h5bfdfaa3db9a4b4a (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[2110]:0x1905ba)
>     at homotopy_web::model::proof::Workspace::visible_diagram::h54414cbf24a26ba7 (https://beta.homotopy.io/d717dc4f4045fce763cd.module.wasm:wasm-function[481]:0xfdea5)

> j @ 235.js:1
> console_error_panic_hook::hook::h6aba13f31c7bca6d @ d717dc4f4045fce763cd.module.wasm:0x143511
> core::ops::function::Fn::call::hf988c63c6d1134ec @ d717dc4f4045fce763cd.module.wasm:0x193f00
> std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 @ d717dc4f4045fce763cd.module.wasm:0x181eee
> std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 @ d717dc4f4045fce763cd.module.wasm:0x189e4c
> std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 @ d717dc4f4045fce763cd.module.wasm:0x1919eb
> rust_begin_unwind @ d717dc4f4045fce763cd.module.wasm:0x190e21
> core::panicking::panic_fmt::h3ab5417155b7ba3b @ d717dc4f4045fce763cd.module.wasm:0x191a21
> core::panicking::panic::h5bfdfaa3db9a4b4a @ d717dc4f4045fce763cd.module.wasm:0x1905ba
> homotopy_web::model::proof::Workspace::visible_diagram::h54414cbf24a26ba7 @ d717dc4f4045fce763cd.module.wasm:0xfdea5
> <homotopy_web::app::workspace::WorkspaceView as yew::html::component::Component>::view::h10f65cc44fe708aa @ d717dc4f4045fce763cd.module.wasm:0x10875
<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h4ceea31ecd6a3a35 @ d717dc4f4045fce763cd.module.wasm:0x724b6
> yew::scheduler::Scheduler::start::h8a075d6297612502 @ d717dc4f4045fce763cd.module.wasm:0x104e40
> yew::html::component::scope::Scope<COMP>::process::h12f14072572882b9 @ d717dc4f4045fce763cd.module.wasm:0x189a43
> <homotopy_web::app::diagram2d::Diagram2D as yew::html::component::Component>::view::{{closure}}::h8b37a222ee64df87 @ > d717dc4f4045fce763cd.module.wasm:0x18b31b
> <yew::html::listener::events::ontransitionend::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::h57734efaec70cfe0 @ d717dc4f4045fce763cd.module.wasm:0x183b88
> <dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hc375c1e92a109740 @ d717dc4f4045fce763cd.module.wasm:0x190d5d
> S @ 235.js:1
> r @ 235.js:1
d717dc4f4045fce763cd.module.wasm:0x194133 Uncaught RuntimeError: unreachable
>     at __rust_start_panic (d717dc4f4045fce763cd.module.wasm:0x194133)
>     at rust_panic (d717dc4f4045fce763cd.module.wasm:0x192128)
>     at std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19 (d717dc4f4045fce763cd.module.wasm:0x181f12)
>    at std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38 (d717dc4f4045fce763cd.module.wasm:0x189e4c)
>     at std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002 (d717dc4f4045fce763cd.module.wasm:0x1919eb)
>     at rust_begin_unwind (d717dc4f4045fce763cd.module.wasm:0x190e21)
>     at core::panicking::panic_fmt::h3ab5417155b7ba3b (d717dc4f4045fce763cd.module.wasm:0x191a21)
>     at core::panicking::panic::h5bfdfaa3db9a4b4a (d717dc4f4045fce763cd.module.wasm:0x1905ba)
>    at homotopy_web::model::proof::Workspace::visible_diagram::h54414cbf24a26ba7 (d717dc4f4045fce763cd.module.wasm:0xfdea5)
>     at <homotopy_web::app::workspace::WorkspaceView as yew::html::component::Component>::view::h10f65cc44fe708aa (d717dc4f4045fce763cd.module.wasm:0x10875)

**Comment by doctorn** [comment]
Ok this is just a side-effect of this to-do:

https://github.com/homotopy-io/homotopy-rs/blob/91dc3c8590296ea6121e715ecee9dbdf26c86d7f/homotopy-web/src/model/proof.rs#L670

In this case, the path of the singular 3-cell before the expansion is invalid after the expansion, so failing to update the path leaves us with an out-of-bounds exception.

**Comment by jamievicary** [comment]
Hao can you check to see if this fixes your issue?

**Comment by HdXu** [comment]
Yes, this bug has been fixed. Thanks for the swift respond.
