### ISSUE TITLE
Cylinder geometry

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#118]
Here are some notes on how we could produce the cylinder geometries, to represent the "tubes" of the string diagram. This is just in 3d, but it came out of a discussion of the 4d case, and I'm confident it should generalize.

![cyl_1](https://user-images.githubusercontent.com/10602270/125942612-c1b8b0ce-8ff7-4915-82ed-1104cb694008.jpg)
![cyl_2](https://user-images.githubusercontent.com/10602270/125942633-848a99ba-05ec-41ef-9b35-44f65b3974ba.jpg)
![cyl_3](https://user-images.githubusercontent.com/10602270/125942642-d3c18ae0-5828-47f0-b982-0ea879be6a08.jpg)

**Comment by jamievicary** [comment]
A brief comment on 4d. We discussed the problem of the cylinders shearing or twisting over time, during the animation. However I'm convinced that doesn't happen, all they do is shrink to a point (or be born from a point.)

**Comment by doctorn** [comment]
Just read through this - excellent explanation. We just need to revise the definition of `t0` for the 4D case (as we can't take cross products).

**Comment by jamievicary** [comment]
Yes agreed Nathan good point.

**Comment by jamievicary** [comment]
Nathan here is the discussion we had previously.
