### ISSUE TITLE
Indicate error and success states with toasts

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#12]

**Comment by zrho** [comment]
We show error states as toasts now, but the error messages could be better. We're not showing success events yet.

**Comment by jamievicary** [comment]
Nathan I have a fantasy that the toasts could smoothly slide off screen (maybe something like these https://www.cssscript.com/demo/animated-queued-toast-messages-pure-javascript-siiimple-toast/)! What do you think.

**Comment by doctorn** [comment]
Sounds doable! I can have a look tomorrow

**Comment by jamievicary** [comment]
Excellent. Another comparison is the JS homotopy.io. Try repeatedly
dragging one vertex onto the other to create the toasts.

https://homotopy.io/#$proof=eJyNVsuumzAQ//ZXK3bLANhDItpWqSv2D6Ao5YBL3EhwZo9s24t9rY2xeBt1FFh5mzsw5M//bkBe6UlOAcBoA2UjDagjNOAsCakv7JJc9byQUtcyIE+QvOl0sYvEAFzi//wwcV7+yQF1Ye8BmfYB6Blt4bITjgjipWVSEmKuzXhuO//7t+ACLVLJyE2QhwvROLwTGrnp6joAkogblfbU1mxKirDyfgr+mxaS8WYgIqgqXlChvgag4ZJVrCD6a+uiIlMCsiXYfGOFCrMkkjhmYa8szYCnygDfgQ7G//uBoFRyPsXAeG9lYprQHEBiXcO4SW5fQIiUaSeFK0dE55LfBP7H+FRcfRJR5zR5M2tiTCr2S4t33ZZHcgJ0sWMEfT96o0XDapUv//X4N//uik2Wxc7+v8c//LOldvkog221OaOlLCYShptUUE8enJ1WmdGcGYSHOkG0K5T61G9lh2hfKojdKOct+0fNHZkQjHYQbxlFO60eNYhW8i3nzam4mGFtr5ho5SBo210HclOt2ZLdmCk+VivZVyvxzRVMDtQ6+SYLnrbqpIezBdPPDBf2Dle2SYbCnVaY8lC4TwhBHyEEtznQISGEfITQZwghO1sT//mCO//GbX7RttqCDq6Z//I6FbTkklamofYPKCun+7+If3UIHfK1Am7hxWO765rakMeVE8HresvukUusQNIFUDBa20BX4sQZ+iq//CpedK0upSJ1Sw1oun6QfdvDDcNq60TLXv0w8mW+OpGvThzO66xwVkDkrxOH+4vD1jpZXK8L3kg1XdMy2FDAyxtsKGDoo4C9FNCcQkqjSP0z8FM4WJxLCthSwFsKw7u95oCXq3YksbNr14saR95FHflWxtGSwO4i8Of4x8FMz53d7rX6SXcH3vr//Dp3A0Q==
