### ISSUE TITLE
Mousing over distinct attachment positions should not add to the undo stack

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#121]
More discussion here: https://github.com/homotopy-io/homotopy-rs/issues/8#issuecomment-877193722

**Comment by NickHu** [comment]
This introduced a bug whenever a redo action was manually triggered (by repeating the action as opposed to clicking 'Redo'), fixed in 019b2dedc03f95710058158ad5d943749fa6bcdc.
