### ISSUE TITLE
Alignment of lines

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#128]
There are problems in alignment of lines, see the follow demo file.

**Demo**
[alignment of lines.zip](https://github.com/homotopy-io/homotopy-rs/files/6885202/alignment.of.lines.zip)

**Screenshot**
<img width="342" alt="Screenshot 2021-07-27 at 13 04 13" src="https://user-images.githubusercontent.com/35509721/127150724-f05c3e53-cbb1-4f03-b349-0306de55457d.png">

**Comment by jamievicary** [comment]
Thanks Hao for this. Yes I had thought there were still some minor bugs in the layout code. This is something that will be shortly fixed with the new cubicalisation code for layout.

**Comment by jamievicary** [comment]
@calintat @doctorn We already have cubicalisation for 2d diagrams right? So we could already replace the 2d layout code to use this.

**Comment by doctorn** [comment]
Good idea! I've had some ideas about how to merge the 2, 3 & 4D pipelines so hopefully we can replace all of the old SVG code soon.

**Comment by jamievicary** [comment]
OK that sounds interesting. However in the short term all I was proposing is to change the layout code; i.e. the code that decides at what coordinates to display particular entities. That is, I'm not proposing in the short term we remove the SVG code.

**Comment by calintat** [comment]
This is fixed by the new layout algorithm.
