### ISSUE TITLE
Unexpected panic

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#129]
Unexpected panic occurs when we do the following operation.

**Demo**
[panic.zip](https://github.com/homotopy-io/homotopy-rs/files/6885527/panic.zip)

**Screenshot**
<img width="524" alt="Screenshot 2021-07-27 at 13 45 19" src="https://user-images.githubusercontent.com/35509721/127155971-e00dd2e2-54c9-459e-afbe-de494bba7140.png">

**Error Log**
[Error] panicked at 'assertion failed: `(left == right)`
  left: `[GenericCospan { forward: RewriteN { dimension: 1, cones: [], payload: () }, backward: RewriteN { dimension: 1, cones: [], payload: () } }, GenericCospan { forward: RewriteN { dimension: 1, cones: [Cone { index: 0, internal: ConeInternal { source: [], target: GenericCospan { forward: Rewrite0(0:0, 1:2), backward: Rewrite0(0:0, 1:2) }, slices: [] } }], payload: () }, backward: RewriteN { dimension: 1, cones: [Cone { index: 0, internal: ConeInternal { source: [], target: GenericCospan { forward: Rewrite0(0:0, 1:2), backward: Rewrite0(0:0, 1:2) }, slices: [] } }], payload: () } }]`,
 right: `[GenericCospan { forward: RewriteN { dimension: 1, cones: [Cone { index: 0, internal: ConeInternal { source: [], target: GenericCospan { forward: Rewrite0(0:0, 1:2), backward: Rewrite0(0:0, 1:2) }, slices: [] } }], payload: () }, backward: RewriteN { dimension: 1, cones: [Cone { index: 0, internal: ConeInternal { source: [], target: GenericCospan { forward: Rewrite0(0:0, 1:2), backward: Rewrite0(0:0, 1:2) }, slices: [] } }], payload: () } }, GenericCospan { forward: RewriteN { dimension: 1, cones: [], payload: () }, backward: RewriteN { dimension: 1, cones: [], payload: () } }]`', homotopy-core/src/diagram.rs:263:13

Stack:

W@https://beta.homotopy.io/235.js:1:9607
wasm-stub@[wasm code]
<?>.wasm-function[console_error_panic_hook::hook::h6aba13f31c7bca6d]@[wasm code]
<?>.wasm-function[core::ops::function::Fn::call::h042126be8e13bf49]@[wasm code]
<?>.wasm-function[std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19]@[wasm code]
<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38]@[wasm code]
<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002]@[wasm code]
<?>.wasm-function[rust_begin_unwind]@[wasm code]
<?>.wasm-function[core::panicking::panic_fmt::h3ab5417155b7ba3b]@[wasm code]
<?>.wasm-function[core::panicking::assert_failed::inner::h67d89b54e013299d]@[wasm code]
<?>.wasm-function[core::panicking::assert_failed::hfbe4b7f7bbc7a49e]@[wasm code]
<?>.wasm-function[homotopy_core::diagram::DiagramN::rewrite_forward::h9d37bcca385e8f70]@[wasm code]
<?>.wasm-function[<homotopy_core::diagram::Slices as core::iter::traits::iterator::Iterator>::next::h33ed9f69e684013c]@[wasm code]
<?>.wasm-function[<alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hd03e121cb9cc271b]@[wasm code]
<?>.wasm-function[homotopy_core::normalization::normalize_relative::he599385955ac9988]@[wasm code]
<?>.wasm-function[homotopy_core::normalization::normalize_relative::he599385955ac9988]@[wasm code]
<?>.wasm-function[homotopy_core::normalization::normalize_relative::he599385955ac9988]@[wasm code]
<?>.wasm-function[homotopy_core::normalization::normalize::h9d19b43f4f659bb7]@[wasm code]
<?>.wasm-function[homotopy_core::typecheck::typecheck_cospan::hd8f33376ea114d8b]@[wasm code]
<?>.wasm-function[homotopy_core::contraction::<impl homotopy_core::diagram::DiagramN>::contract::{{closure}}::h0887dceb03415368]@[wasm code]
<?>.wasm-function[homotopy_core::attach::attach_worker::h78c12bf2e96cf364]@[wasm code]
<?>.wasm-function[homotopy_web::model::proof::ProofState::update::he9d3f357ecde8691]@[wasm code]
<?>.wasm-function[homotopy_web::model::State::update::hc534deb828780a5f]@[wasm code]
<?>.wasm-function[<homotopy_web::app::App as yew::html::component::Component>::update::h2c8328a44d0ecb9a]@[wasm code]
<?>.wasm-function[<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h39ba2e481bf20f77]@[wasm code]
<?>.wasm-function[yew::scheduler::Scheduler::start::h49a9c034775ead2e]@[wasm code]
<?>.wasm-function[yew::html::component::scope::Scope<COMP>::process::ha0ec65fa04fc1879]@[wasm code]
<?>.wasm-function[<homotopy_web::app::diagram2d::Diagram2D as yew::html::component::Component>::view::{{closure}}::hf972da02dd28c302]@[wasm code]
<?>.wasm-function[<yew::html::listener::events::oncanplaythrough::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::h0a48eb8113e6d213]@[wasm code]
<?>.wasm-function[<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1864696aafdd1a77]@[wasm code]
wasm-stub@[native code]
O@https://beta.homotopy.io/235.js:1:9224
r@https://beta.homotopy.io/235.js:1:8249

	j (235.js:1:9752)
	wasm-stub
	<?>.wasm-function[console_error_panic_hook::hook::h6aba13f31c7bca6d]
	<?>.wasm-function[core::ops::function::Fn::call::h042126be8e13bf49]
	<?>.wasm-function[std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19]
	<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38]
	<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002]
	<?>.wasm-function[rust_begin_unwind]
	<?>.wasm-function[core::panicking::panic_fmt::h3ab5417155b7ba3b]
	<?>.wasm-function[core::panicking::assert_failed::inner::h67d89b54e013299d]
	<?>.wasm-function[core::panicking::assert_failed::hfbe4b7f7bbc7a49e]
	<?>.wasm-function[homotopy_core::diagram::DiagramN::rewrite_forward::h9d37bcca385e8f70]
	<?>.wasm-function[<homotopy_core::diagram::Slices as core::iter::traits::iterator::Iterator>::next::h33ed9f69e684013c]
	<?>.wasm-function[<alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hd03e121cb9cc271b]
	<?>.wasm-function[homotopy_core::normalization::normalize_relative::he599385955ac9988]
	<?>.wasm-function[homotopy_core::normalization::normalize_relative::he599385955ac9988]
	<?>.wasm-function[homotopy_core::normalization::normalize_relative::he599385955ac9988]
	<?>.wasm-function[homotopy_core::normalization::normalize::h9d19b43f4f659bb7]
	<?>.wasm-function[homotopy_core::typecheck::typecheck_cospan::hd8f33376ea114d8b]
	<?>.wasm-function[homotopy_core::contraction::<impl homotopy_core::diagram::DiagramN>::contract::{{closure}}::h0887dceb03415368]
	<?>.wasm-function[homotopy_core::attach::attach_worker::h78c12bf2e96cf364]
	<?>.wasm-function[homotopy_web::model::proof::ProofState::update::he9d3f357ecde8691]
	<?>.wasm-function[homotopy_web::model::State::update::hc534deb828780a5f]
	<?>.wasm-function[<homotopy_web::app::App as yew::html::component::Component>::update::h2c8328a44d0ecb9a]
	<?>.wasm-function[<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h39ba2e481bf20f77]
	<?>.wasm-function[yew::scheduler::Scheduler::start::h49a9c034775ead2e]
	<?>.wasm-function[yew::html::component::scope::Scope<COMP>::process::ha0ec65fa04fc1879]
	<?>.wasm-function[<homotopy_web::app::diagram2d::Diagram2D as yew::html::component::Component>::view::{{closure}}::hf972da02dd28c302]
	<?>.wasm-function[<yew::html::listener::events::oncanplaythrough::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::h0a48eb8113e6d213]
	<?>.wasm-function[<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1864696aafdd1a77]
	wasm-stub
	O (235.js:1:9225)
	r (235.js:1:8250)
[Error] RuntimeError: Unreachable code should not be executed (evaluating 'c._dyn_core__ops__function__FnMut___A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1864696aafdd1a77(_,e,A(n))')
	<?>.wasm-function[__rust_start_panic] (235.js:1:9225)
	<?>.wasm-function[rust_panic]
	<?>.wasm-function[std::panicking::rust_panic_with_hook::hbdbceb5cd158bf19]
	<?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h9995bb2f0de4bb38]
	<?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::hc7608161a467c002]
	<?>.wasm-function[rust_begin_unwind]
	<?>.wasm-function[core::panicking::panic_fmt::h3ab5417155b7ba3b]
	<?>.wasm-function[core::panicking::assert_failed::inner::h67d89b54e013299d]
	<?>.wasm-function[core::panicking::assert_failed::hfbe4b7f7bbc7a49e]
	<?>.wasm-function[homotopy_core::diagram::DiagramN::rewrite_forward::h9d37bcca385e8f70]
	<?>.wasm-function[<homotopy_core::diagram::Slices as core::iter::traits::iterator::Iterator>::next::h33ed9f69e684013c]
	<?>.wasm-function[<alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hd03e121cb9cc271b]
	<?>.wasm-function[homotopy_core::normalization::normalize_relative::he599385955ac9988]
	<?>.wasm-function[homotopy_core::normalization::normalize_relative::he599385955ac9988]
	<?>.wasm-function[homotopy_core::normalization::normalize_relative::he599385955ac9988]
	<?>.wasm-function[homotopy_core::normalization::normalize::h9d19b43f4f659bb7]
	<?>.wasm-function[homotopy_core::typecheck::typecheck_cospan::hd8f33376ea114d8b]
	<?>.wasm-function[homotopy_core::contraction::<impl homotopy_core::diagram::DiagramN>::contract::{{closure}}::h0887dceb03415368]
	<?>.wasm-function[homotopy_core::attach::attach_worker::h78c12bf2e96cf364]
	<?>.wasm-function[homotopy_web::model::proof::ProofState::update::he9d3f357ecde8691]
	<?>.wasm-function[homotopy_web::model::State::update::hc534deb828780a5f]
	<?>.wasm-function[<homotopy_web::app::App as yew::html::component::Component>::update::h2c8328a44d0ecb9a]
	<?>.wasm-function[<yew::html::component::lifecycle::ComponentRunnable<COMP> as yew::scheduler::Runnable>::run::h39ba2e481bf20f77]
	<?>.wasm-function[yew::scheduler::Scheduler::start::h49a9c034775ead2e]
	<?>.wasm-function[yew::html::component::scope::Scope<COMP>::process::ha0ec65fa04fc1879]
	<?>.wasm-function[<homotopy_web::app::diagram2d::Diagram2D as yew::html::component::Component>::view::{{closure}}::hf972da02dd28c302]
	<?>.wasm-function[<yew::html::listener::events::oncanplaythrough::Wrapper as yew::virtual_dom::Listener>::attach::{{closure}}::h0a48eb8113e6d213]
	<?>.wasm-function[<dyn core::ops::function::FnMut<(&A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1864696aafdd1a77]
	wasm-stub
	O (235.js:1:9225)
	r (235.js:1:8250)

**Comment by jamievicary** [comment]
Thanks Hao, looks like a normalization bug, I'm tagging Lukas. We haven't had a normalization bug for a while.

**Comment by calintat** [comment]
This diagram is also malformed (see my comment in #130).
