### ISSUE TITLE
Crash during torus eversion

### ISSUE THREAD

**Issue by wilfofford** [homotopy-io/homotopy-rs#1290]
[torus_eversion_actions.txt](https://github.com/homotopy-io/homotopy-rs/files/13719205/torus_eversion_actions.txt)

Crash I experienced while trying to simplify one of the proof steps in an attempt to build the torus eversion.

**Comment by jamievicary** [comment]
Thanks Calin and Wilf. Calin what was the issue here?

**Comment by calintat** [comment]
It was trying to do an anticontraction but it couldn't do the factorization so it panicked. Now if that happens, it just does a bubbling (which has always been our fallback).
