### ISSUE TITLE
3D Rendering Artefacts

### ISSUE THREAD

**Issue by wilfofford** [homotopy-io/homotopy-rs#1291]
I have been seeing some problems with the 3d renderer. Surfaces can sometimes seem to clip through each other causing these weird jaggedy artefacts:

<img width="478" alt="Screenshot 2023-12-19 at 18 57 21" src="https://github.com/homotopy-io/homotopy-rs/assets/111688351/72d46a43-08d6-4975-85ef-11857db7b262">
<img width="610" alt="Screenshot 2023-12-19 at 18 55 50" src="https://github.com/homotopy-io/homotopy-rs/assets/111688351/fc610f35-d439-4211-9ee0-8f57d9fdc36e">

I am using chrome.

edit: it looks like you can only ever see the red surface behind the green one, and never the other way round. The red surface was defined first in the signature.

**Comment by doctorn** [comment]
Hi Wilf, could you add a workspace so I can try this out?

**Comment by wilfofford** [comment]
Sure - I see the artefacts when I view any of the cusps, swallowtails, and cusp flips in the project attached. They become a lot worse the more zoomed out I am.

[oriented.zip](https://github.com/homotopy-io/homotopy-rs/files/13733966/oriented.zip)

**Comment by doctorn** [comment]
Thanks Wilf! Could you have a quick look on Firefox on your machine and see if you observe the same artefacts?

**Comment by wilfofford** [comment]
firefox, I haven't heard that name for years ... 
yes, on firefox I don't see the same issues, or at least, they're much less pronounced - things still start to look weird but only when im SUPER zoomed out, like in the screenshots below, so I don't know whether this is the same issue. 
<img width="200" alt="Screenshot 2023-12-21 at 12 15 29" src="https://github.com/homotopy-io/homotopy-rs/assets/111688351/597be997-f02e-4977-9454-458792cd08d1">
<img width="200" alt="Screenshot 2023-12-21 at 12 15 00" src="https://github.com/homotopy-io/homotopy-rs/assets/111688351/8c4c81cf-b1bc-420d-b6eb-55f3114c532e">

**Comment by doctorn** [comment]
If you're super zoomed out the resolution of the depth buffer becomes limiting and you see depth artefacts (we can't fix this).

But yes, the problem here is then the same problem we had previously which is that Chrome doesn't properly support depth attachments for render buffers in WebGL2. Not sure what we can do about this beyond disabling deferred shading on Chrome (which means no animations on Chrome).

**Comment by wilfofford** [comment]
Ah, thanks Nathan. Yeah I suspected that the zoomed out firefox things were normal and to be expected, but since I don't know anything about graphics I thought I'd share them to be sure. The chrome thing is not a super pressing issue, I can just switch to another browser if it ever becomes too annoying!
