### ISSUE TITLE
Catch panics in the model so that the program does not crash

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#13]
At the moment a crash in the core library will freeze the entire application, which could mean the loss of a lot of work and prevents exporting the workspace to recreate the crash. Instead of the panic could be caught. A crash could be indicated with a toast (see #12).

**Comment by jamievicary** [comment]
Hi, could you please explain why this is closed. In the current build, panics do not yet appear to trigger toasts.

**Comment by zrho** [comment]
Panics are now caught and transformed into the same kind of error as invalid contractions, for example. The program does not crash anymore. Issue #12 is to display the errors as toasts.

**Comment by jamievicary** [comment]
Thanks Lukas for that explanation. However, issue #21 still causes a panic for me, and the whole system then becomes unresponsive.

**Comment by zrho** [comment]
Apparently panics in the model do not get caught yet although the panic handler is in place. I'll investigate why that is.

**Comment by jamievicary** [comment]
@doctorn Any idea why Lukas's panic handler is misbehaving?

**Comment by doctorn** [comment]
Unfortunately, `catch_unwind` makes essentially no guarantees about what it can actually catch. The notes section here goes into more detail: https://doc.rust-lang.org/std/panic/fn.catch_unwind.html, but the long and short is things like vector bounds checking doesn't panic using the same mechanism as user-level `panic!()`.

**Comment by doctorn** [comment]
If you're sure you want to catch all panics, I think you probably want to bracket your call with [installing a panic hook](https://doc.rust-lang.org/beta/std/panic/fn.set_hook.html) and removing it. I have no idea about the performance of this though.

**Comment by doctorn** [comment]
Maybe give this a try:
```rust
use std::thread;

fn catch_all<F, T>(f: F) -> Result<T, ()>
where
    T : Send + 'static,
    F : FnOnce() -> T + Send + 'static,
{
    let handle = thread::spawn(f);
    handle.join().map_err(|_| ())
}
```

**Comment by jamievicary** [comment]
Thanks Nathan for your suggestion. This is something we might revisit. For now the instances of three panics have been much reduced so I we decided to close.
