### ISSUE TITLE
Panic when taking identity in attachment

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#135]
**Demo**
[panic.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/6893970/panic.hom.zip)

**Screenshots**
<img width="1266" alt="Screenshot 2021-07-28 at 15 44 02" src="https://user-images.githubusercontent.com/35509721/127342886-3be0aba5-e600-42d3-bc00-3af979b94afc.png">

_pic1. click a position to open the attachment window_

<img width="214" alt="Screenshot 2021-07-28 at 15 45 23" src="https://user-images.githubusercontent.com/35509721/127343495-25c0b102-e435-4d57-8364-8cddf02b25a9.png"> 

_pic.2 click the identity operation_

<img width="1257" alt="Screenshot 2021-07-28 at 15 48 49" src="https://user-images.githubusercontent.com/35509721/127343722-72d02846-13f5-47bb-bca1-774b42e9a02d.png"> 

_pic3. move your mouse to any cell in the attachment list, then panic occurs_

**Comment by jamievicary** [comment]
Thanks for discovering this Hao.

Selecting any of the interaction icons in the bottom left should cancel
attachment mode.

**Comment by NickHu** [comment]
I can't reproduce this, I believe it has already been fixed.

**Comment by jamievicary** [comment]
When modifying the diagram by taking the identity, the attachment interface needs to be closed.

**Comment by calintat** [comment]
Furthermore, the attachment interface should be closed whenever we interact with the diagram, e.g. when you're scrolling through the slices of the diagram (this one caused me some problems while I was fixing the attachment bug).

**Comment by jamievicary** [comment]
Yes absolutely.
