### ISSUE TITLE
Handling invalid rewrites

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#148]
Say that a rewrite is "invalid" if its the data doesn't even form commuting squares.

We need an assertion in the Rewrite constructor that checks whether these squares commute. This will be slow so it should be togglable as a global setting (in the settings pane) during this dev phase.

We also need a "deep commutativity checking" function that can inspect an already-constructed diagram and check this.

**Comment by jamievicary** [comment]
Related to #147.

**Comment by jamievicary** [comment]
This issue would be a good place to discuss how we will handle this issue going forwards.

**Comment by calintat** [comment]
We can now check if a diagram/rewrite is malformed by using `is_well_formed()` which returns a `bool`.
