### ISSUE TITLE
Investigate malformed diagram

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#158]
The following diagram, taken from issue #119, is malformed. We need to investigate whether it is still reproducible after the fix in expansion (#150), and if so, figure out where in the code we introduce malformed diagrams.

[singularityIII.zip](https://github.com/homotopy-io/homotopy-rs/files/7048240/singularityIII.zip)

<img width="436" alt="127769090-684a7654-0850-4b99-8973-ef37c18d1b56" src="https://user-images.githubusercontent.com/16837293/130821904-47280232-1a36-40fe-a8db-eee64586a8a2.png">

**Comment by jamievicary** [comment]
Calin feels he knew how to reproduce it before. Maybe Calin liaise with Hao?

**Comment by calintat** [comment]
I believe this is no longer reproducible and was fixed by #150 so closing it.
