### ISSUE TITLE
When importing malformed diagram, it panics.

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#159]
For example, importing  https://github.com/homotopy-io/homotopy-rs/files/6912583/singularityIII.zip would cause panic immediately. They should not pass the type-checking before causing the panic.

**Comment by jamievicary** [comment]
Can you explain a bit more about the problem here Hao.

In the current version, if you import a malformed workspace, it is supposed to panic, that is the current design.

**Comment by HdXu** [comment]
I think before the change, when I import a malformed diagram, an error badge appears and then I can carry on using homotopy.io; but now it panics and I have to reload the webpage. Is there any reason for this change?

**Comment by jamievicary** [comment]
Yes it's unfortunately an unavoidable consequence of the changes we had to
make.

If you really still need to load an old malformed diagram (e.g. to see how
you built something) then one of the others can tell you how to run an old
version of the software locally on your own computer.

**Comment by HdXu** [comment]
No, I mean that I will prefer a warning badge than a genuine panic, from the point of view of user-experience.

**Comment by jamievicary** [comment]
Yes I understand. But for technical reasons this is impossible at the
moment.

**Comment by HdXu** [comment]
OK. In that case, shall we close this issue or leave it for notice in the future?

**Comment by jamievicary** [comment]
I think it can be closed.
