### ISSUE TITLE
Homotopy between 3d singularity and 2d singularity

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#160]
**Demo file**
[homotopy between singularities of different dimensions.zip](https://github.com/homotopy-io/homotopy-rs/files/7070678/homotopy.between.singularities.of.different.dimensions.zip)

The following homotopy between a 3d singularity and a 2d singularity is viewed as 'ill-formed' in the current homotopy.io version. This is potentially caused because homotopy.io treats this move in a wrong way; instead of a homotopy between a 3d singularity and a 2d singularity, this should really be a homotopy between that 3d singularity and the identity of that 2d sigularity.

<img width="435" alt="Screenshot 2021-08-28 at 13 16 47" src="https://user-images.githubusercontent.com/35509721/131217736-66c8585d-68aa-42ba-9eef-ff92dd1ec47a.png">

**Comment by jamievicary** [comment]
Thanks for this Hao. Can you be more precise please as to exactly what interaction you want to make in the tool, for which you think it is giving the wrong response. I don't understand what your annotations (1), (2) on the picture mean.

**Comment by HdXu** [comment]
(1) and (2) are two different homotopies (hence I denote the arrows by two colours), and each homotopy can be realized by mouse-dragging in two ways, as illustrated by those arrows.

________________________________

**Comment by jamievicary** [comment]
I see. I think Move 2 should be valid here, and should trigger an expansion via factorization.

**Comment by jamievicary** [comment]
I just checked this and it works properly at homotopy.io, see here: https://homotopy.io/#$proof=eJydWttu4zYQ//ZVCffUDh3fmtQsUBfoHiyJQbDlR17ECWcG2XeTfK9m6kTMcaxMgD5JIaubozJkhxz+Kl6o8FA9iV1Tnrq2rS//EA1uyK+nyo//nnsmsdL17TV4bFs2//Lf4uHrV7H7URyLhx//F96b9dnkr99Vw8Xjq533sikv9fC6793a5KWx//u+y6cv8y37P64+Pjr91XmNY61OVzW75OA+SwUvPeDmuf30+nXdGV7XPVTVeXU716rdD98Le2+bvad3VzvjrTVr39bdX2a+2Kc9PVx3pfDk8vyzRzM0JORkxvvD1X//aKHsiunaxM++jv96qq3pngovhTDZEVP1slkMONkuZ6s6ckmmWzHubCea6a5df//1CihuQ8R6iJ2GiGkl14+C2abhe8nl0fCZioeufa//Wb//vtupSbljo27feyPTye6te6m+b6fupTuf9GPYnsui3mp8X2zetbc+55N3+UEI////8zo+ID9ApNaOE//64TgARA//s4YjTR6HYtY8zGqcB6CjLrav+I8BVk3llQlLegsLuad1dvcVeR7hr8MrsmiXJrkhibGiIjZy0PnsuCJxOOj+s5Bjw//a8Tjpf6vugXsssIIpsf+hQzTR0RCAuY6EqX4mEGN7g+hdKzbS3fF9//L+dPVuNlaa2L3bq+REUy7yJE9ImSekJAkpGUJKkpASE1LyhJSbCGkoQkrDYjJaZBkfXMoLQ//BCOuyTZ3khPceL8DleKEHyAgteKtwcY5RA0xVEMY2+XoSNgjy6SlIMURK//UbEMUYpiiNzCEKUZ8wxpHhY5hYQsfoelzFObzONTpcrnSqMoDVRMtlRhC9cVppNG+TMioE7z55rTGmiua7lwHQiua0txXQMW6IisfF2iJYu2Vlm0taLUUas82lpT5NIao2tYcmmzRR01RS6NSzodSYPJfdjRWCahak+6hxOoRgk0tjFNoGTskO4ZkTfPAGWewfQxkjXPyC3KQ5vHkMPoLeWIwWQxiCxRfJiULFvKkXuhSJcjhq//eTL56M55SLsOQDSsXCRejfRhwoFbA2mdRiKi11VawKFjIohCmzUtUE1smm1qZQUGufbA4u1qUXeX6S9o0uyZbUZI0VvO1ikvcG1+lebhMFi7nKNJYw8Blt5DGYo20kUbeSX7WMeBZnwEv3AFPURFnsbjy6c4GFm0n8mgLKt05RnAdKbgOC67jBdeRgpumO0sJrsM7D8fXro4pDh1ZHDpcHDq+OHRkcZhmENohRhId2tBSguYwZWJ238knDguiF+v5fmDyvOEPiI+RNHmGPx5SfzThj8d88jKyh9+W+ZRd66j06nPR6jUVrZ7YB//9Eqepx7vcmms5T2zPK6C1FbY+V0CMbI376VPvGfc4Gantuf7xlzyA37xl8yCMRxBbWBbxFDvATrAvAOBvk51gXyBwRcPaPsxlS34h1gZTQ1fzAsy4wghpIQQ1YUAMvqIEUVL2FdYER1IAEVVJUIAWV//fgM//UAg//gFR0vXDiDNtdKwTVVr9c66qEznW3SnrQCiqruvXw1uVO6e//AnPtTv4AsRZFWIbeHuKzwNv9mS//P1blqy65pV+4M0VEd6q463LpFt0aTmImyHKMJv051AMOnU8vlkDz0cjmsa+ZLNQy2y6UfG1piptO5fK0GbKrT6Zeh2pltXd4//CMK+OQ23il9l8OIp9AOPzf79Mlh//LE+Xalw22VTTbbG5skraaUmc//j52OgRlqiRNvZ7JzKbuhQryKWMqQGrqZMRi7nJnrp32zbnrI2mtcYkXMHdYIPYj08BDbbRkl//plnK4oGBQNg17DcIS9FsccDExzLwODwjBccUc4GBoHsw0HALKhCIDLhTsnzbA0aNbYaRo7H7HdlZUVOew87QlAQOjB9RBkzhgpfpICUPpY8iYAUZDRAGog8ZNi23Qp6On3Oo9c6zFhxNR75JqPUm1Jj0B0fwC3f+IWGur////GwtSCUquhYEyZTFINGJgSB9JJgv+SIAJHdMsOVgbnufENLeUxwPUWzL5JRmIhfRQ5e5emNkjyLzgyGDW0X5gRVGlckPsAJtWVdOwW2I4FaKCG5lyeBWG7PEDGAcnUvDio5OpfPRqejo5BpZuLtNElcx5MeNUDK+01ZX//DkibilHckvhXirg9l//CLbJMsjS3ojLpeP3LcSuj4KAJbuk58VqCW5qqQOxUgaiIW2m//bF2xJBjOuSPGkGqD6egc5F7xfacTBkwrDLQmCco1wzBBqdMq0AzHMUHJX3Ck7TIOXEuDO1GcB5Bv3ILOd27BJAXFtCTTvwCNWiAyWmNyn1Bu3OWL926G699CLgGDufNrBTD0VtHcqVwMU7kYSVLPMJUL3teT1DNE4WKiow//IxtS0BKfQxmzSV4OPQ3zuyGbCk//l5C5htsm6wKIdcMT+9lmOrQWwVFFuJfhvghltMH8uz1X6WrRZIts4NOfbT20y5cMskkSFWxUlhVB1L//Y4PFZVR7xGWblrzNv5Y9bazf6mfX079fzefafz18T801rq3

**Comment by HdXu** [comment]
A slightly different case, now (1) passes type-check but (2) does not in beta.homotopy.io
[2d-3d-singularity-homotopy-2.zip](https://github.com/homotopy-io/homotopy-rs/files/7072999/2d-3d-singularity-homotopy-2.zip)

**Comment by jamievicary** [comment]
I think that is correct.

**Comment by jamievicary** [comment]
The issue identified by Hao in the original post before is definitely a bug. It could perhaps be an issue with factorization. Could someone look at it please? @NickHu @calintat @zrho

**Comment by calintat** [comment]
I'm looking at this. I don't think it's an issue with factorisation, it's either an issue with expansion or type checking.

**Comment by jamievicary** [comment]
Thank you Calin. Is it possible to extract the full expansion rewrite. Then we can directly verify by hand if it's correct.

**Comment by calintat** [comment]
So I think the expansion rewrite is wrong. It doesn't seem to match the source diagram. What confuses me even more is that this doesn't fail the wellformedness check because I believe the diagram we're trying to type check is malformed.

**Comment by jamievicary** [comment]
That seems strange. I guess it's worth looking more closely to be really sure if it's malformed or not. Maybe you could turn this into a test for the malformedness checker?

**Comment by jamievicary** [comment]
Thanks Calin yes that makes sense. Factorization needs to be updated then.
Do you mind doing that? Nick would usually handle that but he's busy at
MFPS at the moment.

**Comment by calintat** [comment]
I'm already working on it.
