### ISSUE TITLE
Highlight computed incorrectly

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#168]
Trying to attach cells in the given position causes panic.
<img width="860" alt="Screenshot 2021-09-08 at 14 45 42" src="https://user-images.githubusercontent.com/35509721/132521372-fa1147ae-e84b-48ea-99f6-89e8c570bfd6.png">

This could be related to issue #135 

**Demo**
[panic-8thSep.zip](https://github.com/homotopy-io/homotopy-rs/files/7129279/panic-8thSep.zip)

**Error message**
panicked at 'called `Option::unwrap()` on a `None` value', homotopy-web/src/app/diagram2d.rs:414:65

Stack:

init/imports.wbg.__wbg_new_59cb74e423758ede@https://beta.homotopy.io/index-a286b7f59f2c67a3.js:312:19
console_error_panic_hook::hook::h7c2d1c246b116ea2@https://beta.homotopy.io/index-a286b7f59f2c67a3_bg.wasm:wasm-function[1132]:0x1526a8
core::ops::function::Fn::call::h9f6eef0081d446f1@https://beta.homotopy.io/index-a286b7f59f2c67a3_bg.wasm:wasm-function[2900]:0x19f714
std::panicking::rust_panic_with_hook::h2d9079427a2d996a@https://beta.homotopy.io/index-a286b7f59f2c67a3_bg.wasm:wasm-function[1850]:0x18a4b1
std::panicking::begin_panic_handler::{{closure}}::h4e49f350d9f4de36@https://beta.homotopy.io/index-a286b7f59f2c67a3_bg.wasm:wasm-function[2043]:0x1935ea
std::sys_common::backtrace::__rust_end_short_backtrace::h91e711607d91be52@https://beta.homotopy.io/index-a286b7f59f2c67a3_bg.wasm:wasm-function[2453]:0x19d1d0
rust_begin_unwind@https://beta.homotopy.io/index-a286b7f59f2c67a3_b…
index-a286b7f59f2c67a3.js:324:21

Uncaught RuntimeError: unreachable executed
index-a286b7f59f2c67a3_bg.wasm:1702294:1

**Comment by jamievicary** [comment]
I am also encountering this...

**Comment by calintat** [comment]
> I am also encountering this...

Do you have a simpler example than the one Hao uploaded? The problem here is that the highlight positions are wrong (they reference a place outside the diagram). I'm still to understand how the highlight positions are calculated, it could be that the underlying embedding is wrong.

**Comment by jamievicary** [comment]
No my example is bigger than Hao's. His example is pretty small right?

**Comment by calintat** [comment]
It's not too big but it's 4D.

**Comment by jamievicary** [comment]
No unfortunately my example is 5D.

**Comment by jamievicary** [comment]
OK here is a simpler example of the same problem.
[filename_todo (46).zip](https://github.com/homotopy-io/homotopy-rs/files/7153589/filename_todo.46.zip)

**Comment by jamievicary** [comment]
Sorry that was wrong. Use this one.
[filename_todo (47).zip](https://github.com/homotopy-io/homotopy-rs/files/7153599/filename_todo.47.zip)

**Comment by NickHu** [comment]
As @calintat  says, the highlight is not being computed correctly.
The out-of-bounds coordinate for @jamievicary's example is computed here:
https://github.com/homotopy-io/homotopy-rs/blob/5f9e5a808a8f7f7e8e544681edffe9896d7fd129/homotopy-web/src/app/workspace.rs#L205

The highlight it computes is:
```
Highlight2D { from: [Interior(Regular(0)), Interior(Regular(2))], to: [Interior(Regular(1)), Interior(Regular(4))], kind: Attach }
```

That means it wants to highlight from the bit above the cap to somewhere above where the output wire would be. I believe the correct highlight should be something like:
```
Highlight2D { from: [Interior(Regular(1)), Interior(Regular(2))], to: [Interior(Regular(1)), Interior(Regular(2))], kind: Attach }
```

but I'm not sure. Probably best for @zrho to take a look at this?

I can at least prevent it from crashing for now.

**Comment by NickHu** [comment]
It won't cause crashes anymore. Now, when it computes an impossible highlight, it just draws nothing.

**Comment by jamievicary** [comment]
Thank you Nick this is certainly an improvement!

Do you think you can straightforwardly supply a complete fix, or does it look difficult?

**Comment by calintat** [comment]
I think I figured out how to fix this. @zrho I'll take it off your hands if you don't mind.

**Comment by calintat** [comment]
This is fixed now. This is what the highlights for Jamie's example will look like:

<img width="315" alt="Screenshot 2021-12-16 at 14 57 46" src="https://user-images.githubusercontent.com/16837293/146396095-eaf4fd65-8ab8-456f-9778-08c01e6f9676.png">

<img width="316" alt="Screenshot 2021-12-16 at 15 02 17" src="https://user-images.githubusercontent.com/16837293/146396099-23292900-236f-4c75-90b9-f9e7f157ae38.png">

<img width="317" alt="Screenshot 2021-12-16 at 14 58 11" src="https://user-images.githubusercontent.com/16837293/146396103-06ab45e4-7a94-4cf3-b7df-f37750e9bded.png">

<img width="319" alt="Screenshot 2021-12-16 at 15 02 27" src="https://user-images.githubusercontent.com/16837293/146396104-422c8f40-9c39-408f-869a-a77ed498528c.png">

**Comment by jamievicary** [comment]
Great thanks Calin!
