### ISSUE TITLE
Naturality of braid-cancelling and enhancing of smoothing

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#171]
I try to find an **actual** homotopy replacement for the following **algebraic** naturality move of braid-cancelling with saddle.
[naturality of braid-cancelling with saddle.pdf](https://github.com/homotopy-io/homotopy-rs/files/7146083/naturality.of.braid-cancelling.with.saddle.pdf)
In the second file attached, I encounter the following problem: the best I can go is to concentrate the homotopies to the saddle. Now I couldn't find a way to _free the saddle singularity out_. I imagine the `smoothing` function of homotopy.io could be upgraded to tackle this.

<img width="416" alt="Screenshot 2021-09-10 at 21 09 01" src="https://user-images.githubusercontent.com/35509721/132911909-532e68fb-155f-4043-bd00-577eaaaabf79.png">

**Files**
[algebraic_naturality_move.zip](https://github.com/homotopy-io/homotopy-rs/files/7145920/algebraic_naturality_move.zip)
[attempt_build_naturality_move.zip](https://github.com/homotopy-io/homotopy-rs/files/7146133/attempt_build_naturality_move.zip)

**Comment by jamievicary** [comment]
I think I can do this, but I keep triggering #168.

**Comment by HdXu** [comment]
**Addendum**
I encounter a similar difficulty in this example:
<img width="593" alt="Screenshot 2021-09-12 at 13 11 46" src="https://user-images.githubusercontent.com/35509721/132987108-a96a3b41-a28a-45d2-b144-68f1e07732dd.png">
[smoothing_around_singularity_12thSep.zip](https://github.com/homotopy-io/homotopy-rs/files/7149544/smoothing_around_singularity_12thSep.zip)

**Comment by HdXu** [comment]
There is a way of solving this smoothing problem: to construct the algebraic resolution of singularity and then rewrite it by the actual homotopic resolution of singularity. 
1. Construct a new diagram for the desired neighbourhood of the **resolved** singularity. 
2. Then take its identity (in order to record the homotopies) and **go the source slice**. 
3. Now apply the `contraction` until the source slice becomes the neighbourhood of the original singulaity we tried to resolve. 
4. You can tidy up the homotopies a little bit if you want by going back to the top dimension. 
5. Finally, use the `Theorem` option on the menu, which would create a new cell (i.e. the **algebraic resolution of singularity**) with the same source and target slices of the current diagram (i.e. the **homotopic resolution of singularity**), and a cell of one-dimension higher with the algebraic resolution as the source and the homotopic resolution as the target.
6. To apply the resolution of singularity, go to any diagram where a singularity of the same type lies; click on the singularity, and apply the algebraic resolution. Then go one dimension back, and click the algebraic resolution. Apply the rewrite there, and eventually it leaves you with an actual homotopic resolution of singularity.
