### ISSUE TITLE
Document build instructions

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#19]

**Comment by jamievicary** [comment]
This would be great, if I could build it I could try to work on some of these easier issues myself.

**Comment by jamievicary** [comment]
@calintat Do you feel like adding this Calin, I know you built it successfully the other day.

**Comment by calintat** [comment]
I just followed the instructions in the readme: homotopy-web/README.md.

**Comment by jamievicary** [comment]
Ah I didn't see that before, thanks. Is there a reason these instructions are there rather than at the top level? If not, then we can move these instructions to the main readme, and close this issue.

**Comment by NickHu** [comment]
That documentation is auto-generated, and perhaps not the best. I'll find some time to do some proper documentation soon
