### ISSUE TITLE
Continuous slice transformations please

### ISSUE THREAD

**Issue by vinnylarouge** [homotopy-io/homotopy-rs#191]
![AwSBCDLaH_fullreduce](https://user-images.githubusercontent.com/5328067/136610002-e69df225-69e2-44dd-9255-45560b1bde76.gif)

I can make animations for proofs using a screencapture, but the jerkiness is offputting, and it isn't clear what is being reduced.

**Comment by jamievicary** [comment]
Vincent hello there! Smooth animations are coming soon.
