### ISSUE TITLE
not enough ways to distinguish wires

### ISSUE THREAD

**Issue by vinnylarouge** [homotopy-io/homotopy-rs#195]
there are only 8 colours at the moment, more colours would be nice, but...

I intend to use the generated diagrams in a paper. due to colour-blindness, apart from black, I can reasonably use a palette of size 3 before someone will have difficulties distinguishing wires.

would either of the following be possible?
- dotted or dashed wires, which extend to dotted and lined fill patterns?
- labels alongside wires?

**Comment by doctorn** [comment]
You can choose an arbitrary colour in the colour picker already by clicking on the large box at the bottom of the picker. I appreciate this needs a better label though.

**Comment by vinnylarouge** [comment]
thanks for the tip!

**Comment by calintat** [comment]
Improving the colour picker is tracked in #526.

I am closing this as "won't fix" since we decided against dotted/dashed wires.
