### ISSUE TITLE
Signature suspension

### ISSUE THREAD

**Issue by vinnylarouge** [homotopy-io/homotopy-rs#198]
for a specific use case I have, my generators are all 2-cells on 1-cells of a single 0-cell (planar), but I would like to define a special 1-cell X that braids with the other 1-cells. Since it was less effort than specifying that many braiding rules, I promoted all my 2-cells to 3-cells and 1-cells to 2-cells.

would It be possible either to shortcut braiding equations, or to systematically promote/demote collections of cells to give/remove symmetries?

**Comment by vinnylarouge** [comment]
(i might have to seek the symmetric closure of the dependency relation to pick out the legal subcollection to suspend)

**Comment by calintat** [comment]
I think this is an interesting. We should at least provide an option to suspend the entire signature. Maybe also a subset of generators (though this might be trickier).

**Comment by regular-citizen** [comment]
@mlharaujo also requested this feature (#788), here is his take on this:
> It would be useful to be able to take a signature and "suspend" it. The suspended signature would have either one or two 0-cells (this could be a user choice). Then it would have a (k+1)-cell for each k-cell in the original signature, with the obvious sources and targets. The 1-cells in the suspended signature would all have the same source and the same target.

**Comment by regular-citizen** [comment]
This feature was requested by Hei Li as well.
