### ISSUE TITLE
Disable click-to-attach

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#231]
In building large homotopy diagram, I believe it is beneficial to add a switch in the Setting to disable click-to-attach. It will take minutes if you accidentally click on a region, and currently there is no way to break out of the searching. When I indeed want to attach some cell, I can turn the function back on in the Setting.

Also, it would be helpful if we can select a cell from the list and then choose a region on the diagram to attach. This should significantly reduce the amount of time required for type-checking.

**Comment by calintat** [comment]
I am closing this as won't fix. There are open issues to improve the search for attachments (#4, #169) which we should prioritise.
