### ISSUE TITLE
Mouse hover tooltips broken in Chrome

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#233]
Still working in Firefox

**Comment by jamievicary** [comment]
This is working now in chrome, maybe it was a blip on my machine.

**Comment by jamievicary** [comment]
OK I now see what's going on. The mouse hover tooltips do not appear when the sidebar is open. (Maybe they are under the sidebar?) Please can this be fixed.

**Comment by calintat** [comment]
I'll close this since it's a duplicate of #248.
