### ISSUE TITLE
Consistent coordinate ordering

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#24]
Issue #21 was caused by a confusion about coordinate ordering: in most contexts coordinates into a diagram are ordered in such a way that we can arrive at the point they address by iteratively taking slices of the diagram at the coordinate heights in sequence. In the 2d graphics the traditional (x, y) coordinate system is used, which happens to be the other way around. This is more confusing than just using the (y, x) orientation in the renderer instead and can cause many potential problems.

**Comment by jamievicary** [comment]
Yeah this tripped me up all the time in the previous implementation.

**Comment by calintat** [comment]
I fixed this because it's a prerequisite to migrating the 2d renderer to the new cubical mesh extraction.

**Comment by calintat** [comment]
`Highlight2D` still uses the wrong ordering, so I reopened the issue.
