### ISSUE TITLE
Issue counter

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#240]
Not really an issue ... but if there are 61 open issues, and 108 closed ones, how can we be on issue #240 already?

![Issues · homotopy-io_homotopy-rs - Google Chrome 24_11_2021 16_53_47](https://user-images.githubusercontent.com/10602270/143281635-af546f5b-0c34-427d-8b6e-7ec5846d3002.png)

**Comment by doctorn** [comment]
Pull requests count!
