### ISSUE TITLE
Labelled factorization

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#242]
I'd like to explore whether "labelled factorization" might make sense. We would ideally like to use this, in the labelled world, for expansion in a singular slice #234.

Nick how does the base case of unlabelled factorization work? Suppose we have unlabelled 0-rewrites f:A-->C and g:B-->C, and we are searching for a factorizing map h:A-->C. Then I guess it does a case analysis, something like this:

- If A=B, return the 0-rewrite A-->B. (This is saying h := id.)
- Otherwise, if B=C, return the 0-rewrite A-->C. (This is like saying h := f.)
- Otherwise, fail.

Of course 0-rewrites have no additional data beyond the source and target, which is already known. But the point is to determine the failure case. (Even this is unnecessary since we type-check afterwards.)

So I think there is a relatively obvious factorization algorithm for labelled rewrites. Namely, use precisely the ordinary factorization algorithm, plus obvious extensions to give the regular-singular sublimits. Then in the base case (which of course is the only place labels actually appear):

- If A=B:
  - if f and g have different labels, fail.
  - otherwise, return the trivial 0-rewrite A-->B.
- Otherwise, if B=C, return h := f.
- Otherwise, fail.

This seems reasonable to me, and would completely avoid "label propagation" #235. It would be good to hear what people think.

We argued before that factorisation is weird in a world where rewrites are not composable. In fact, consistent with my ideas here, it is probably better to say that rewrites ARE composable, as long as at least one is a homotopy. And in this factorisation situation, g:B-->C is always a homotopy.

**Comment by calintat** [comment]
So the base for unlabelled factorisation works a little differently:
* If dim(A) ≤ dim(B), return the 0-rewrite A → B.
* Otherwise, fail.

But I agree that for labelled factorisation, it should be like Jamie described.

In fact, we already have special cases for f = g and g = id, so we don't even need to bother having another case for 0-rewrites.

**Comment by NickHu** [comment]
I've implemented this essentially how @jamievicary described, with a mild refactor for `Monotone`. I think these ideas generalise to any case where we 'inflate' a monotone function into a rewrite; the code reflects this, and hopefully this will make it easier to port anticontraction (#554) too.

**Comment by calintat** [comment]
I am reopening this as I am not convinced that it's correct.

**Comment by jamievicary** [comment]
Can you explain your suspicions?

**Comment by calintat** [comment]
Basically the way we calculate the regular slices of the factorising rewrite is incorrect.

We use this function which construct a rewrite from a monotone and the singular subslices:
https://github.com/homotopy-io/homotopy-rs/blob/d5473607c27afe13f21dba45ae3ab4fb15f6d00f/homotopy-core/src/rewrite.rs#L643-L666
It tries to determine the regular slices based on the target cospan, but that is wrong for regular slices which are contained between singular slices (i.e. *not* side flanges). Unless the monotone map is injective, this will return malformed rewrites.

The correct way to do this is to calculate the regular slices of the factorising rewrite by recursively factorising pairs of regular slices of the input rewrites. This is what we do for singular slices, but it's trickier for regular slices as it's harder to index them. This will ensure that the labels are calculated correctly, and we will not need composition.

**Comment by jamievicary** [comment]
That's an interesting point and sounds plausible, Nick what do you think?

**Comment by calintat** [comment]
Also I have a strong suspicion that if we proceed this way, we will not need the wellformedness checks at all (except for debugging and checking imports).

Right now on master, the code can and will generate malformed factorisations which we need to reject. This is something that always bothered me. But in the labelled version, I think if we compute the regular slices correctly, the result will be guaranteed to be wellformed (assuming no bugs of course).

**Comment by jamievicary** [comment]
This would be wonderful. However I am wary.

**Comment by calintat** [comment]
I fixed all the remaining problems in factorisation, so we can close this.

I also added the wellformedness checks as the algorithm in its current form does not guarantee the result is wellformed. However I figured out what I need to do to guarantee the result is wellformed and therefore get rid of the checks, but implementing that is not a priority right now.
