### ISSUE TITLE
Auto-smoothing after contraction

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#245]
In the labelled world, contraction will be the basic mechanism for cancelling generators with their inverses. But then we probably want to smooth automatically after contraction (#239), otherwise we get a singularity remaining, and the user will really want to see an identity.

Note this is not specifically an issue for the labelled world, we could also consider this feature for the non-labelled tool, there's just less of a use-case.

**Comment by NickHu** [comment]
Closed by f06f0130d2bd9cc1d4b76cda536b8a4cb8d8f58f
