### ISSUE TITLE
Normalization of labelled diagrams

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#247]
This might give us another way to type check labelled diagrams for noninvertible generators.

The hope is that the labels "get along" with the degeneracy maps and so this works ok.

This could let us avoid orientation detection #243.

**Comment by jamievicary** [comment]
Is this done? Or did we just decide not to do it.

**Comment by calintat** [comment]
We decided not to do it. Both Nick and I believe there is probably a deep connection between collapse and normalisation, but there doesn't seem to be any immediate reason to implement labelled normalization.
