### ISSUE TITLE
2D layout issue

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#256]
<img width="468" alt="Screenshot 2021-11-29 at 22 31 16" src="https://user-images.githubusercontent.com/35509721/143946002-5cf4637c-3a74-4c68-a38e-c65fd381bb1b.png">

File:
[layout.zip](https://github.com/homotopy-io/homotopy-rs/files/7621260/layout.zip)

**Comment by calintat** [comment]
Thanks Hao! This should be fixed by cubicalisation.

**Comment by calintat** [comment]
This is fixed by the new layout algorithm.
