### ISSUE TITLE
Order of generators constructed from `Theorem` has issue

### ISSUE THREAD

**Issue by HdXu** [homotopy-io/homotopy-rs#257]
When I press `Theorem` on a n-dim diagram, it generates an (n+1)-cell and an n cell. This (n+1)-cell lies above n cell, **and you cannot drag that n cell above the (n+1) cell**. Instead, you need to **drag that n cell exactly between itself and the (n+1) cell to switch their positions**. Then, if you use `Theorem` again, the relative positions between the former n cell and (n+1) cell switch back again.

It seems like an issue of incompatibility between default orders of cells generated by `Theorem` and drag-and-drop function.

**Comment by jamievicary** [comment]
Thanks Hao we are looking at this.

**Comment by jamievicary** [comment]
I tried this just now and it still seems that I can replicate the bug.

**Comment by jamievicary** [comment]
Nathan: this is a Yew problem, the old state is being reused with the new elements, but this doesn't make sense. Need to put in indirection.

**Comment by jamievicary** [comment]
Lukas: need to use keys.

**Comment by jamievicary** [comment]
Something similar happens when you edit the name of one generator, then delete an earlier generator.

**Comment by calintat** [comment]
Fixed by 16cff6a96bb435a1b37378c3f72c689e107660ea
