### ISSUE TITLE
More ergonomic API for testing

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#26]
The tests for contraction and expansion use type checking and thus need to build a signature. At the moment the generators and the signature are created separately which makes writing tests annoying. An ergonomic builder API for signatures would make it easier to quickly write regression tests for the bugs we encounter on the way.

**Comment by NickHu** [comment]
I think we're effectively there since c2cbea3e4fb9dfb431a4f75bd2fd00990e0c10d8
