### ISSUE TITLE
Finalising the 3D renderer

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#283]
If there are any simple ways we could adjust features of the 3d rendering, e.g. the shininess/mattness of the material, that would be good to have in the setting drawer

**Comment by doctorn** [comment]
Options I'm thinking:

- [x] Disable lighting (actually looks surprisingly cool)
- [ ] Gamma control (was previously 2.2, is currently 1.0)
- [ ] Specularity exponent ('shininess')
- [ ] Lighting settings
  - [ ] Number of lights
  - [ ] Their positions
  - [ ] Their colours (this is an easy bonus after we've done the first two)

**Comment by jamievicary** [comment]
Now that we can render 3d models nicely this suddenly got more important. In particular the darkness issue illustrated in #384 is quite annoying and would be easy to resolve with some extra light sources.

**Comment by doctorn** [comment]
Closing this in favour of the 'rendering milestone' project

**Comment by jamievicary** [comment]
Closed in favour of #386
