### ISSUE TITLE
Models look a bit dark from some angles

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#284]
Maybe we need to add more light sources? I think the js homotopy.io has light sources at the vertices of a tetrahedron around the model.

![homotopy io - Google Chrome 09_12_2021 18_54_29](https://user-images.githubusercontent.com/10602270/145458147-2d72e4d4-5e60-40ad-b1e8-8a0d78338606.png)
![homotopy io - Google Chrome 09_12_2021 18_44_48](https://user-images.githubusercontent.com/10602270/145458162-d494e310-fcb9-46ee-8845-7dfa0d1fe52f.png)

**Comment by jamievicary** [comment]
Here the second image looks good, but on the first image the red and purple surfaces look very dark.

**Comment by doctorn** [comment]
I'm going to close this in favour of #283 which covers this
