### ISSUE TITLE
Preserve signature item state when generators are added or removed

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#331]
This can be achieved easily using `key`s in yew. We have to be careful that yew only uses keys when all children of a node have keys, so we need to assign keys to the new folder button and the drop zones as well.

Unfortunately this is currently blocked by this bug which messes up the order of elements in keyed lists: https://github.com/yewstack/yew/issues/2327 This bug appears to be actively worked on, so I will revisit this issue once the bug is fixed.

**Comment by WorldSEnder** [comment]
Do note that removing and adding items do not trigger the linked bug and should already work correctly.
The bug is triggered by multiple existing keyed items being reordered to another place with respect to other already existing keyed items in the list.

**Comment by jamievicary** [comment]
@WorldSEnder ah that's great. So @zrho could you take a look? Seems this bug will not hold us back after all.

**Comment by zrho** [comment]
The bug is still triggered: when we drag and drop the items, not only the items themselves but also the dropzones are reordered, leading to dropzones which are not adjacent to the correct item. We could potentially integrate the dropzones into the items themselves, though, so that with drag and drop only single items are moved.

**Comment by WorldSEnder** [comment]
If the dropzones are not direct children of the keyed list and only a single item is moved, I'd expect this to work around the bug, yes.

**Comment by calintat** [comment]
Fixed by 16cff6a96bb435a1b37378c3f72c689e107660ea
