### ISSUE TITLE
Cannot render irregular cubes

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#340]
The current way we render cubes does not work for irregular cubes like the one below. It leaves gaps in the space, which is what we were seeing in #189 for the lisp.

[lips_2.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/7897981/lips_2.hom.zip)
 
![IMG_A2E1583F5F05-1](https://user-images.githubusercontent.com/16837293/150153112-62698c3c-e30a-404d-92f4-c456b6034d15.jpeg)

**Comment by calintat** [comment]
@jamievicary @doctorn 

It seems this issue is fairly well-studied and there is plenty of literature about this:
[Artifacts Caused By Simplicial Subdivision — Hamish Carr, Torsten Moller, and Jack Snoeyink (2006)](https://eprints.cs.univie.ac.at/4975/1/2006_-_artifacts_caused_by_simplicial_subdivision.pdf)

Basically, it’s not question of how we render each cube individually but rather of being consistent at the faces.

Consider for example what happens when we have two cubes meeting at an irregular face:

<img src="https://user-images.githubusercontent.com/16837293/150763196-56908c11-fbc1-4088-b053-9346fbf90a95.jpeg" width=500 />

If we triangulate cube A along the blue diagonal and cube B along the red diagonal, we will get a tetrahedron-shaped hole:

<img src="https://user-images.githubusercontent.com/16837293/150763285-98fea76b-4b0f-499c-be11-2a03b33cc240.jpeg" width=500 />

Conversely, if we triangulate cube A along the red diagonal and cube B along the blue diagonal, we will get an overlap at the same tetrahedron. This is precisely what we are seeing with the lisp (kudos to Nathan for spotting the overlaps):

<img src="https://user-images.githubusercontent.com/16837293/150765554-b5c23ceb-5a0a-4c7d-a35d-ae7d58a03d3a.jpg" width=500 />

Note that our idea of rendering the cubes directly will *not* work because the convex hulls of cubes A and B actually overlap  at that same tetrahedron. Instead, we need to fix the triangulate so that it is consistent at the faces (this property is called *topological consistency* in the literature). The fact that our cubes are directed will make this easier.

There are several triangulation schemes in the literature:

<img width="1002" alt="Screenshot 2022-01-24 at 10 38 31" src="https://user-images.githubusercontent.com/16837293/150768269-5d543614-731c-4bc3-93c1-f64c87d709ff.png">

We are using Minimal (5) and I am currently working on making it consistent. I have also implemented Freudenthal (6) which is the canonical triangulation induced by the zigzag structure, but I still need to figure out how to orient the simplicies to get the correct normals (this is not a problem for the other one as Nathan has already figured that out). Since I have already made significant progress on both, I was thinking we could have a toggle in the settings to choose between them.

**Comment by doctorn** [comment]
Amazing stuff! I disagree with the comment about the current proposal though as that proposal does not seek to render the convex hull of the cube. Even in the irregular case each individual slice is a convex hull, but the volume obtained by gluing these is not.

**Comment by calintat** [comment]
I thought that the aim of that idea was to render the convex hull. If not, what is it that it would render? It must be one of the triangulations, otherwise it will produce holes or overlaps.

**Comment by doctorn** [comment]
It's very cleverly not a triangulation! Want to Zoom quickly?
