### ISSUE TITLE
Render the cubical geometry directly

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#353]
As per Nathan's idea, we could render cubes directly by sorting them in the time coordinate and then constructing (up to) 18 animation polygons as illustrated below. If we do this, we could bin the simplicial geometry and triangulation entirely.

![ima_01b4794](https://user-images.githubusercontent.com/16837293/150855890-0115a137-e097-4af3-a23a-7dd281942cf8.jpeg)

**Comment by jamievicary** [comment]
I thought this had potential problems if there were multiple "first" or "last" vertices -- we wouldn't know which one to choose, but the rendering could potentially depend on the choice?

Why would we need this if we have fixed the problem with holes in the geometry via other means.

**Comment by doctorn** [comment]
Calin and I discussed this morning and we agreed that choosing an arbitrary start and end vertex from among those available does not impact the rendering. The topologically coherent subdivision implementation would be trickier than this to implement and less efficient in terms of animation polygons.

**Comment by jamievicary** [comment]
OK, thanks thinking that through, that's interesting.
