### ISSUE TITLE
Incorrect subdivision behaviour

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#379]
- Points on the bounding box should stay on the bounding box. Status: handled by a separate issue.
- Diagrams should meet the bounding box in a perpendicular fashion.
- Semantically important points should have appropriate coordinate values preserved
- Preserving coordinates of semantic points should not cause pinching for incident wires
- Render wires attached to surfaces (?)
- Tangents of wires meeting vertices

**Comment by jamievicary** [comment]
There is clearly not enough detail here, I'll try to improve the explanation of these points and split into separate issues if necessary.

**Comment by doctorn** [comment]
I think Calin has covered all of these points well enough for the MVP with his recent changes! 🍾
