### ISSUE TITLE
Situation where simple attachment not detected

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#38]
In this scenario, clicking on the central vertex should cause "Cell 3" to be attached. But nothing happens.

[filename_todo (16).zip](https://github.com/homotopy-io/homotopy-rs/files/6346587/filename_todo.16.zip)

**Comment by calintat** [comment]
I accidentally closed the wrong issue, sorry!

**Comment by calintat** [comment]
Oh wait, this was already closed, never mind!
