### ISSUE TITLE
In labelled contraction base case, only some edges are eligible for contraction

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#381]

**Comment by jamievicary** [comment]
Here's an image from the whiteboard when we talked about this last week. Maybe we should go with the following definition and see how well it works: a _candidate edge_  is a vertical edge within a regular-regular or singular-singular slice, which is also recursively a candidate edge within that slice. In other words, we just exactly disqualify those edges which form part of some regular-singular slice.

![PXL_20220203_181436258](https://user-images.githubusercontent.com/10602270/152987849-90df6375-c2d3-4cfb-bca3-debd0b21db10.jpg)

**Comment by NickHu** [comment]
I think this is implemented correctly now
