### ISSUE TITLE
Need a "restrict" operation

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#39]
When viewing some slice of a diagram, the "restrict" operation of the JS version replaces the current diagram object in the workspace with the one current visualized; that is, it throws away all the "other" slices. This is an important operation which is used all the time in practice. I would go so far as to say it's blocking for this big test isotopy I'm building.

Of course restriction is not always valid, so we should test this by typechecking the resulting restricted diagram.

**Comment by NickHu** [comment]
When would a restriction to a slice of a known good diagram fail to typecheck?

**Comment by jamievicary** [comment]
This could happen if you're viewing a singular slice.

**Comment by NickHu** [comment]
Is it the case that restriction is only legal if and only if you're viewing a slice along regular levels at each dimension? This is much cheaper to check for than typechecking.

**Comment by NickHu** [comment]
I've added this now, allowing for restriction along slices of only regular levels.

As with Theorem, suggestions for an icon from [here](https://fonts.google.com/icons) would be appreciated.

**Comment by jamievicary** [comment]
Can you please modify this to also allow restrictions to sources and targets, since they also count as regular levels.

**Comment by jamievicary** [comment]
Please also associate the "R" hotkey with this.

**Comment by jamievicary** [comment]
Almost there ... please could the "Restrict" tooltip be changed to "Restrict (R)".
