### ISSUE TITLE
Clicking in diagram skirting should only match attachments, not rewrites

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#4]
[filename_todo (1).zip](https://github.com/homotopy-io/homotopy-rs/files/6337560/filename_todo.1.zip)

Here clicking in the very lowest part of the diagram yields either an attachment or a rewrite. But since I was clicking near the edge, only the attachment should be considered.

**Comment by jamievicary** [comment]
This is good progress but still not quite right. Consider the following workspace, which shows a knot theory proof in progress:
[filename_todo (32).zip](https://github.com/homotopy-io/homotopy-rs/files/6394167/filename_todo.32.zip)

Clicking on the uppermost vertex should only match an internal rewrite "CapMakeTwist" or "CapMakeTwistInv" -- that works perfectly (although the highlights are a little wonky). This is "attaching a 4-cell by its 3-boundary".

Clicking in the half-strip on the right of the diagram should only allow attachment of a red string -- that works perfectly. This is "attaching a 2-cell by its 1-boundary".

Clicking in the half-strip at the top of the diagram should only allow attachment of a "Cup" 3-cell, which would be "attaching a 3-cell by its 2-boundary". But we're also erroneously given the red string attachment, and the "CapMakeTwist" and "CapMakeTwistInv" rewrites, as options. None of these are local to the upper half-strip and should not be displayed.

I think the simple general rule is as follows.
* When clicking internally to an n-diagram, you should only be able to rewrite by an (n+1)-cell, matching on its source.
* When clicking on a k-dimensional source or target boundary of an n-diagram, you should only be able to attach a (k+1)-dimensional generator, matching on its target or source k-dimensional boundary, respectively.

In the example above, we are looking in this workspace at the target 3-dimensional boundary of a 4-dimensional diagram. So when we click in the interior, we are clicking in the target 3-boundary, and so can only attach 4-cells. When we click near the top of bottom, we are clicking in the diagram's 2-boundary, and so can only attach 3-cells. And when we click near the left or right, we are clicking in the diagram's 1-boundary, and so can only attach 2-cells.

The corner case (literally) is when you click in the corner. Then it's ambiguous whether you are really clicking on a horizontal or vertical half-strip. I guess the horizontal half-strips tend to be thinner so it would be better to let them take priority.

**Comment by calintat** [comment]
We will track this in #684.
