### ISSUE TITLE
Subdivision causes things to peel away from the boundary

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#411]
Vertices on the boundary should never be allowed to move off the boundary during subdivision.

After Nathan's change 9798fe3, we can observe this in most examples.

We originally noticed this in issue #342: [filename_todo.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/8090094/filename_todo.hom.zip)

**Comment by jamievicary** [comment]
Here by "boundary" you mean the actual bounding box of the entire diagram, right?

**Comment by calintat** [comment]
Yes. We really need to find a better name for Akvile's "boundary" label.
