### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#420]
This is mostly a reminder for me to write tests for my stuff, but everyone should feel free to add to this.

- [x] [layout.rs](https://github.com/homotopy-io/homotopy-rs/blob/master/homotopy-core/src/layout.rs)
- [x] [mesh.rs](https://github.com/homotopy-io/homotopy-rs/blob/master/homotopy-core/src/mesh.rs)
- [x] [graph.rs](https://github.com/homotopy-io/homotopy-rs/blob/master/homotopy-core/src/graph.rs)
- [ ] [geom.rs](https://github.com/homotopy-io/homotopy-rs/blob/master/homotopy-graphics/src/geom.rs)

**Comment by calintat** [comment]
@NickHu are you still planning to write tests for graph explosion? I could do it if you want.

**Comment by NickHu** [comment]
I'm part-way done with those!
