### ISSUE TITLE
Maybe a contraction bug

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#421]
This should contract but it fails type checking. Could be another factorisation bug maybe.

[filename_todo.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/8214743/filename_todo.hom.zip)

**Comment by jamievicary** [comment]
I don't think this to do with factorisation. I am surprised this doesn't contract. The behaviour is the same in the old js tool.

**Comment by calintat** [comment]
This isn't a bug. The contracted diagram doesn't typecheck and that's correct.

**Comment by jamievicary** [comment]
I don't understand why, you'll have to explain this to me.
