### ISSUE TITLE
Crash: panicked at 'called `Result::unwrap()` on an `Err` value: DimensionError'

### ISSUE THREAD

**Issue by niss36** [homotopy-io/homotopy-rs#422]
Hi,

I'm consistently getting crashes with these error messages:

(Sorry about the formatting)

```
panicked at 'called `Result::unwrap()` on an `Err` value: DimensionError', homotopy-web/src/app/diagram_gl/renderer/scene.rs:120:10

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (https://beta.homotopy.io/homotopy_web.js:390:19)
    at https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[1296]:0x159565
    at https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[3239]:0x1b03f0
    at https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2113]:0x197b68
    at https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2429]:0x1a50b4
    at https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2788]:0x1ad5d8
    at https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2830]:0x1adde3
    at https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[2468]:0x1a6420
    at https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[198]:0x1ed33
    at https://beta.homotopy.io/homotopy_web_bg.wasm:wasm-function[528]:0xddcf0

imports.wbg.__wbg_error_09919627ac0992f5	@	homotopy_web.js:402
$func1296	@	homotopy_web_bg.wasm:0x159636
$func3239	@	homotopy_web_bg.wasm:0x1b03f0
$func2113	@	homotopy_web_bg.wasm:0x197b68
$func2429	@	homotopy_web_bg.wasm:0x1a50b4
$func2788	@	homotopy_web_bg.wasm:0x1ad5d8
$func2830	@	homotopy_web_bg.wasm:0x1adde3
$func2468	@	homotopy_web_bg.wasm:0x1a6420
$func198	@	homotopy_web_bg.wasm:0x1ed33
$func528	@	homotopy_web_bg.wasm:0xddcf0
$func281	@	homotopy_web_bg.wasm:0x7a88d
$func286	@	homotopy_web_bg.wasm:0x7de99
$func2360	@	homotopy_web_bg.wasm:0x1a2b29
$func1579	@	homotopy_web_bg.wasm:0x173952
$func2446	@	homotopy_web_bg.wasm:0x1a58e8
$func2070	@	homotopy_web_bg.wasm:0x1953ae
$func608	@	homotopy_web_bg.wasm:0xf1864
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hc1009139f4448beb	@	homotopy_web_bg.wasm:0x1af0dc
__wbg_adapter_27	@	homotopy_web.js:218
real	@	homotopy_web.js:199
```

```
Uncaught RuntimeError: unreachable
    at homotopy_web_bg.wasm:0x197b9e
    at homotopy_web_bg.wasm:0x1a50b4
    at homotopy_web_bg.wasm:0x1ad5d8
    at homotopy_web_bg.wasm:0x1adde3
    at homotopy_web_bg.wasm:0x1a6420
    at homotopy_web_bg.wasm:0x1ed33
    at homotopy_web_bg.wasm:0xddcf0
    at homotopy_web_bg.wasm:0x7a88d
    at homotopy_web_bg.wasm:0x7de99
    at homotopy_web_bg.wasm:0x1a2b29
$func2113 @ homotopy_web_bg.wasm:0x197b9e
$func2429 @ homotopy_web_bg.wasm:0x1a50b4
$func2788 @ homotopy_web_bg.wasm:0x1ad5d8
$func2830 @ homotopy_web_bg.wasm:0x1adde3
$func2468 @ homotopy_web_bg.wasm:0x1a6420
$func198 @ homotopy_web_bg.wasm:0x1ed33
$func528 @ homotopy_web_bg.wasm:0xddcf0
$func281 @ homotopy_web_bg.wasm:0x7a88d
$func286 @ homotopy_web_bg.wasm:0x7de99
$func2360 @ homotopy_web_bg.wasm:0x1a2b29
$func1579 @ homotopy_web_bg.wasm:0x173952
$func2446 @ homotopy_web_bg.wasm:0x1a58e8
$func2070 @ homotopy_web_bg.wasm:0x1953ae
$func608 @ homotopy_web_bg.wasm:0xf1864
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hc1009139f4448beb @ homotopy_web_bg.wasm:0x1af0dc
__wbg_adapter_27 @ homotopy_web.js:218
real @ homotopy_web.js:199
```

Environment:
- Chrome 99.0.4844.51
- Windows 10 21H2 Build 19044.1566

Steps to reproduce:
1. Import workspace: [Knot 3_29.zip](https://github.com/homotopy-io/homotopy-rs/files/8216816/Knot.3_29.zip).
2. Switch to 4D view.
3. ~~Change to a different desktop (e.g. Win + Tab -> new desktop) before it finishes loading, and stay there until it does (takes about a minute for me).~~ Press ~~Left or~~ Right while it's preparing the scene.

**Comment by doctorn** [comment]
Thanks @niss36! This very much looks like a me problem - I'll try and fix it for you

**Comment by calintat** [comment]
The error is thrown by `CubicalGeometry::new` so it's definitely a me problem, but I can't reproduce it :(

**Comment by calintat** [comment]
@niss36 Is step 3 really necessary to reproduce this? Also, when did you first observe this? Was it before yesterday?

**Comment by niss36** [comment]
Thanks! I only noticed this today (but hadn't been using 4D much before). And yep, step 3 seems necessary for me: if I stay on the same desktop and wait for it to finish, it works just fine.

**Comment by calintat** [comment]
Interesting! I am truly amazed that that makes a difference.

**Comment by niss36** [comment]
Right, so it's actually not related to desktops -- sorry! You should be able to reproduce it just by pressing left/right while it's preparing the 4D scene.

(I was using Win + Left/Right to switch desktops and that apparently doesn't 'catch' the keystroke.)

**Comment by doctorn** [comment]
This makes me thing maybe the view dimension isn't being update after using the arrow keys to change slice?

**Comment by calintat** [comment]
Ah that makes sense! The right key descends into a slice which changes the diagram.

**Comment by doctorn** [comment]
https://github.com/homotopy-io/homotopy-rs/blob/fa8da93a878e0ce41883f63674dc3c859c0dd79e/homotopy-web/src/model/proof.rs#L384

**Comment by doctorn** [comment]
Ok got it! This method might accidentally make the view dimension exceed the dimension of the diagram so we just need to add a check in here.

**Comment by calintat** [comment]
We might need to switch from the 3d/4d renderer to the 2d renderer if that happens, would that be hard?

**Comment by doctorn** [comment]
Nope it's all handled automatically! There's a state change here so the workspace is re-rendered anyway.
