### ISSUE TITLE
"Theorem" button

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#43]
We also need the "Theorem" button, or something equivalent. For a diagram D in the workspace, the theorem button does the following:

* Creates a new generator A in the signature with the same type as D
* Creates a new generator B in the signature with type A --> D

When invertibility is implemented, generator B will then be labelled invertible.

I'm pretty sure this corresponds to the notion of "weak homotopy equivalence" of groupoids.

In practice this is used as an internal way to "save the state" of a proof in progress, so it's blocking for this big proof I'm trying to build at the moment.

**Comment by NickHu** [comment]
Suggestions for the icon from [here](https://fonts.google.com/icons) would be very helpful - I just went with 'title', it being a big T

**Comment by jamievicary** [comment]
I suggest "Bookmark Add".

**Comment by jamievicary** [comment]
Please could the "H" key be  assigned as a keyboard shortcut, and the tooltip changed to "Theorem (H)"
