### ISSUE TITLE
Weird HTML element at the top middle of the screen

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#44]
This video demonstrates a weird HTML entity near the top middle of the screen, which prevents clicking on the diagram beneath it, and hovering over which with the mouse causes the cursor to change to a hand:
https://youtu.be/31mDlwDdOwQ

**Comment by jamievicary** [comment]
It's this HTML entity:

    <div class="workspace__path workspace__path--empty">
    <span class="workspace__path-home">
    <i class="material-icons md-light">menu</i>
    </span>
    </div>

**Comment by zrho** [comment]
I don’t see the video because it is marked as private. This element is the slice path navigation, which is hidden if the slice is empty. I suppose it is not sufficiently hidden yet to prevent interaction.

**Comment by jamievicary** [comment]
I've fixed the video. Yes that sounds like the culprit.
