### ISSUE TITLE
Left and right arrow buttons as keyboard shortcuts for undo and redo

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#45]

**Comment by zrho** [comment]
I don't know if the arrow buttons are the best choice for this. It would be great to have the up and down buttons switch between adjacent slices, in which case it would be natural for the left button to go up one slice. The right button could be used then to enter an interaction where you can select the slice that you want to descend into with the keyboard, allowing to navigate a diagram with the keyboard only. Currently there is a binding for undo on the U key, and we could introduce some binding for redo if desired (maybe shift U?).

**Comment by jamievicary** [comment]
Hi Lukas, I completely agree with your ideas here. Maybe you could make
separate issues for slice navigation hotkeys, and for undo hotkeys.

Jamie
