### ISSUE TITLE
Warn people when navigating away from the page

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#47]
There is a danger that somebody accidentally clicks the "back" button attempting to undo, and loses their work. It would at least be good to intercept that and warn people "Are you sure you want to leave?". That's definitely possible as it happens commonly on other websites.

**Comment by zrho** [comment]
Probably with a check that skips the warning if the workspace is empty.

**Comment by jamievicary** [comment]
bump!
