### ISSUE TITLE
Central dot not needed when rendering a homotopy

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#48]
Or maybe, render it transparent so it can still be used as a click target (as in the JS version).

**Comment by calintat** [comment]
I think I have a neat way to solve this using the new mesh extraction (#328).

**Comment by calintat** [comment]
Actually, this will work just as fine with the existing mesh.

We can very easily detect if an element should be rendered or not by just checking its codimension (which is the dimension of the diagram minus the dimension of that element's generator). So points should only be rendered if their codimension is zero, which immediately rules out all homotopies. We can just not render the homotopies but still keep them as `ActionRegions` to they can still be used as click targets.

The braid works perfectly fine:
<img width="236" alt="Screenshot 2022-01-11 at 10 25 33" src="https://user-images.githubusercontent.com/16837293/148925664-b01c86da-03e6-44e6-ada8-abd5faa0dd9c.png">

But the half-braid looks a bit off:
<img width="240" alt="Screenshot 2022-01-11 at 10 24 12" src="https://user-images.githubusercontent.com/16837293/148925703-9af52279-40d3-40c1-8d55-03906e81fb9b.png">

I reckon we could tidy this up by making the lines a bit longer. Or maybe if we merged the paths like we do the simplices?

@zrho WDYT?

**Comment by jamievicary** [comment]
Hi Calin, this is the correct approach (comparing codimension), please do this.

The lines that look off need solving in a different way, by changing the incoming strands to have vertical tangent. We can talk about that separately it's a different issue. If you could just do a commit to get rid of the dots on homotopies that would be great.
