### ISSUE TITLE
Host the labelled rewrite branch at alpha.homotopy.io

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#482]
Nick I will email you the credentials for the domain name registrar I use

**Comment by NickHu** [comment]
The hack was horribly broken and didn't work at all, so I moved our hosting to Firebase Hosting in 469eace6ca6274b6a3a14ec9082fd41bafc5ddc7.

`master` is available at both https://beta.homotopy.io (Firebase Hosting), and https://homotopy-io.github.io/homotopy-rs/ (GitHub Pages) for redundancy.

Moreover, each pull request now automatically gets a preview URL of the form: https://homotopy-rs--homotopy-io-branch-abcdefgh.web.app/. https://alpha.homotopy.io will redirect to the labelled branch for now.

It may take up to 24 hours for the SSL certificates and domain information to propagate everywhere, but it seems to have settled for me now.

**Comment by calintat** [comment]
The CSS is broken on https://homotopy-io.github.io/homotopy-rs/
