### ISSUE TITLE
Hidden vertices are shown

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#496]

**Comment by calintat** [comment]
Fixed by ec4df12098a67065cb07a28be1aa98dba0f10d97.

**Comment by calintat** [comment]
<img width="239" alt="Screenshot 2022-06-07 at 15 09 13" src="https://user-images.githubusercontent.com/16837293/172401569-ebf3a4cf-25ed-4616-b138-a718f6b07ae2.png">

[filename_todo.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/8853920/filename_todo.hom.zip)

**Comment by calintat** [comment]
@jamievicary I fixed this in a way that seemed logical to me.

Basically, before the change, each point was labelled with the max generator of its diagram. Now, we use the depth information, so if a point has depth $n$, we look at its $n$-th singular slice and pick the max generator of that slice.

So if the bead is in front, the central point is labelled by yellow as before: 
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/180264962-dfb6272b-0f46-47fa-b7c7-d4226eca0c3a.svg)

But if the bead is behind, the central point is now labelled by red (and hence not drawn as it's not codimension 0):
![homotopy_io_export-2](https://user-images.githubusercontent.com/16837293/180264946-6ecff3c4-d507-43e1-93c2-50d5df81e02a.svg)
