### ISSUE TITLE
Generalized contraction/expansion

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#497]
We realised in the meeting today that when you perform a top-level contraction, the correct response of the tool is to emit a contraction, expansion pair. The canonical example is when you have a composite of a cell with its inverse. The contraction UI move should cause the tool to generate a forward contraction, followed by a backward smoothing, which omits the singular point that results.

In principle this is something we could do in a singular or regular slice. So, we have an additional case to consider, beyond the existing cases of handling contraction in a singular slice, or expansion in a singular slice, or expansion in a regular slice, as we had before. We also have the problem of handling a contraction/expansion pair in a singular or regular slice.

I don't think this will be too bad, it will decompose in terms of what we already have. For example, I think a contraction/expansion pair in a regular slice decomposes into contraction in a regular slice, followed by expansion in a singular slice. A con/exp pair in a singular slice decomposes into contraction in a singular slice, followed by expansion in a singular slice.

**Comment by NickHu** [comment]
I've implemented this in d5473607c27afe13f21dba45ae3ab4fb15f6d00f. Recursive contraction now operates on a pair `ContractExpand` of rewrites, and expansion propagation has been refactored a little to allow for calling with any arbitrary rewrite as the input expansion to be propagated. Let's continue the discussion in #234.
