### ISSUE TITLE
Compile a fast LP solver to Wasm

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#509]
The best LP solvers such as CBC or Highs are written in C/C++. So if we want to use them in our project (#508), we need to compile them in Wasm using `emscripten`. Nick made some progress on this.

**Comment by jamievicary** [comment]
This is great. Has it improved the performance of the layout algorithm?

**Comment by regular-citizen** [comment]
To be determined, there are some issues to address with layout tests that currently depend on minilp to address before we can move to good_lp+highs.

**Comment by jamievicary** [comment]
Thanks Chiara. So is this new solver currently being used in the production
layout code?

**Comment by regular-citizen** [comment]
Not yet, but the idea is to either use this solver only for production or to just bin the tests altogether.
I think @calintat is the best position to figure out what to do on this front, but once that is sorted moving to highs should be relatively straightforward.
