### ISSUE TITLE
Shallow type checking after contraction and expansion

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#51]
Currently the entire result of contraction and expansion is type checked. Under the assumption that the original diagram was well-typed this is unnecessary, and given that type checking is expensive should therefore be avoided.

**Comment by jamievicary** [comment]
Great, yes this came up in my chat with Nick this morning. This is blocking for my big proof as interaction becomes too slow. It would be great if this could be prioritised, it should be quite easy.

**Comment by zrho** [comment]
I've added shallow type checking for contraction and expansion now; please let me know if that resolves the performance issues or if any ill-typed diagrams slip through now.

**Comment by jamievicary** [comment]
Yes it seems to completely resolve the performance issues I was having.
Once the contraction bug #52 is fixed I'll be able to test more thoroughly,
as I use contraction as a tool to rapidly build complex high-dimensional
diagrams.

**Comment by jamievicary** [comment]
[filename_todo (23).zip](https://github.com/homotopy-io/homotopy-rs/files/6372882/filename_todo.23.zip)
In this attached workspace, perform the following.

1. Dragging the lower vertex up, performing a contraction, it takes about 300ms on my machine, of which 200ms is contraction.

2. Next, do the following. Repeatedly merge the uppermost vertex downwards, stopping when the diagram has 3 singular levels. Note that we're on the target slice of a high-dimensional composite, so these rewrites are being attached to the proof object. Now, drag the lower vertex up. On my machine this final move takes about 1200ms, of which 200ms again is contraction.

However, moves 1 and 2 have precisely the same nontrivial part. So if typechecking is only looking at the nontrival cones generated by the rewrite, they should have similar processing times.

**Comment by jamievicary** [comment]
It would be great if this could be fixed as soon as possible, it's strongly blocking for me at the moment.

**Comment by jamievicary** [comment]
This commit seems to have fixed the issue for me, that's great. It's still quite easy to generate high-dimensional scenarios where type-checking is very slow, albeit somewhat artificially, but this may now be beyond any reasonable fix. I'll create a separate issue to discuss that.
