### ISSUE TITLE
Empty workspace information

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#512]
Many apps like text editors show some information when there is nothing open. We should do the same if the workspace is empty. We could show a message like "Click on a generator to select it. To create a new 0-dimensional generator, press the + button".

This would be hugely useful if a user opens homotopy.io for the first time and have no idea where to start.

**Comment by thud** [comment]
This could also include default keybinding information to help new users. (note from standup 21/07/22)

**Comment by calintat** [comment]
Yes! I am thinking something similar to VS code:
<img width="2672" alt="Screenshot 2022-07-21 at 15 09 42" src="https://user-images.githubusercontent.com/16837293/180234576-9347d855-4d56-4932-8531-03ece96e82d9.png">

**Comment by jamievicary** [comment]
Upvote!
