### ISSUE TITLE
Project metadata

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#513]
We need to add title, author, and abstract fields in the project panel and store these in the serialised object.

**Comment by calintat** [comment]
@anastasia-jc the first step here is to add the UI for editing the title, author, and abstract. This should go in the "Project" panel which is defined in [homotopy-web/src/app/project.rs](https://github.com/homotopy-io/homotopy-rs/blob/master/homotopy-web/src/app/project.rs).

**Comment by anastasia-jc** [comment]
Additionally:
- Moving import/export to right of title/Project.
- Adding project title to stay visible even when not viewing information, including on the tab name.

**Comment by jamievicary** [comment]
Thanks for adding these details Anastasia. We had the idea that the title could appear in the top-left of the main viewing area, possible in light grey so it is not too obtrusive.
