### ISSUE TITLE
Migration tool

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#514]
We need a tool to convert workspaces of the old JS version to the new Rust version.

The data structures are logically equivalent, so this will not be conceptually difficult, maybe just a hassle to write.

**Comment by calintat** [comment]
Once this is done, we can start preparing to phase out the JS version.

**Comment by NickHu** [comment]
This might become significantly more difficult/impossible once the invertible generators stuff is merged.

**Comment by calintat** [comment]
The signature should be easy, you can just reconstruct each generator diagram. But the workspace diagram will be tricky.

**Comment by calintat** [comment]
Here is an idea: we can construct the fully exploded graph (without any labels), and then figure out a way to add the labels using the fact that every neighbourhood in the graph should be equivalent to the canonical neighbourhood.

**Comment by NickHu** [comment]
Related to #235

**Comment by calintat** [comment]
Ah nice!

**Comment by calintat** [comment]
Yulong did the migration on `master` and I patched it so that it works on `labelled` so this can be closed now.
