### ISSUE TITLE
Image export dialog

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#525]
When exporting a diagram to TikZ, a confirmation dialog should pop up where you can customise and preview your TikZ export:
- turn off braidings to to get a more compact TikZ export,
- black-and-white or coloured,
- generator style (#519),

For 3D diagrams, you could have the option of exporting a stack of 2D diagrams (#475). Or maybe we could export them in Manuel's style which would also work for 4D diagrams:

<img width="170" alt="Screenshot 2022-06-20 at 10 18 14" src="https://user-images.githubusercontent.com/16837293/174569692-e30bf6f6-a9c3-483c-9e05-59e9bd11f117.png">

**Comment by calintat** [comment]
Now that we can also export SVGs, we need different buttons for "Export to TikZ" and "Export to SVG".

**Comment by calintat** [comment]
Thanks Yulong for implementing the first version!

In our standup yesterday, we decided to promote the image export panel to a full-blown drawer panel. We therefore need to change the icon to a "Share" button, move it to the top of the sidebar, and have it always be visible. Moreover, when you open the panel and there is no diagram in the workspace, it should say something like "No diagram visible".

Finally, we need to start adding some options. For now, let's start with these two and we can think of more later:
- a toggle "Show braidings" under TikZ,
- a toggle "Use OpenGL renderer" under Manim.

**Comment by jamievicary** [comment]
Why do we need this "show braidings" toggle for Tikz?

**Comment by calintat** [comment]
Turning off the braidings would simplify the TikZ code and if you're working in a symmetric monoidal category, you might not care about the braidings anyway.

**Comment by calintat** [comment]
And we already have the code to generate TikZ without braidings, so we might as well expose it to the user.

**Comment by jamievicary** [comment]
That makes sense.
