### ISSUE TITLE
Reverse x-axis in 3D

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#531]
Maybe this is just me, but I feel like the x-axis points the wrong way (leftwards) so everything looks mirrored.

**Comment by NickHu** [comment]
I think we absolutely shouldn't do this **if** it adds special case analysis to coordinate manipulations.

**Comment by calintat** [comment]
I find it really confusing. I'm not saying we should change the coordinates in layout or the geometry, just in the renderer.

**Comment by calintat** [comment]
@doctorn WDYT? Is that the default in GL?

**Comment by NickHu** [comment]
I believe GL uses 'screen-space coordinates' (at least in 2D, not sure about 3D). So (0, 0) is the top-left of the screen (Y-axis reversed).

**Comment by NickHu** [comment]
I think this is called handedness; you want it to be left-handed, but it's currently implemented in a right-handed way. Should be fixed by changing one of (or both) the camera-screen matrix or the world-camera matrix. Apparently it's a good idea for camera space to match clip space, so maybe the latter is the way to do it.

**Comment by doctorn** [comment]
z-axis is blue and points out of the screen.

**Comment by calintat** [comment]
Why is the x-axis pointing left?

Also it looks like the z-axis points into the screen, doesn't it?

**Comment by doctorn** [comment]
In the screenshot, you're 'behind' the origin. If you orbit so that the z-axis points out of the screen, the x-axis points rightward and the y-axis points upward.

**Comment by doctorn** [comment]
<img width="731" alt="Screenshot 2022-06-20 at 14 16 39" src="https://user-images.githubusercontent.com/6421560/174610214-738d7696-3e0d-4576-bc24-cc35be3e676b.png">
<img width="443" alt="Screenshot 2022-06-20 at 14 16 54" src="https://user-images.githubusercontent.com/6421560/174610221-59082510-3ac3-43d9-8732-1722d8beab62.png">

**Comment by calintat** [comment]
Alright in that case, we want a left-handed system with the z-axis pointing into the screen. It's important that 2D diagrams rendered in GL look the same as they do in SVG.

How easy is it to change this?

**Comment by doctorn** [comment]
https://github.com/homotopy-io/homotopy-rs/blob/4d0736bce64a68dfd9bf20fb117227b1f8ad7c55/homotopy-web/src/app/diagram_gl/orbit_camera.rs#L5

Change `rh_yup` to `lh_yup`

**Comment by doctorn** [comment]
I had a look and I _think_ I misunderstood what the handedness there refers to: my guess is it's the _target_ handedness not the input (which is assumed to be right-handed). So, switching to `lh_yup`, everything is rendered behind the camera? I am very unsure though as I expected this to 'just work™️'.

**Comment by NickHu** [comment]
According to the documentation, the `lh_yup` assumes the base coordinate is left handed in the source, rather than being a projection matrix to convert from right handed to left handed.

I fixed it by negating some values in `perspective_transform`.
