### ISSUE TITLE
TikZ exported code unclean

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#533]
Currently, the TikZ export will name nodes things like `generator-0-0`, when a better choice would be e.g. the name of the generator.
It also exhibits floating point precision ugliness by giving coordinate values like `5.000000000000000027` which should be rounded to a 'nice' number of significant figures.

**Comment by calintat** [comment]
Weird I thought I had fixed the rounding problem.

**Comment by calintat** [comment]
But I agree that the code can be cleaner. The only obstacle to using the generator name as the name of the colour is that you could have multiple generators with the same name.

**Comment by NickHu** [comment]
> Weird I thought I had fixed the rounding problem.

Perhaps this is true; I haven't checked recently.

> But I agree that the code can be cleaner. The only obstacle to using the generator name as the name of the colour is that you could have multiple generators with the same name.

Easy to fix! Probably `cup-0` and `cup-1` are still better than 'generator-X-Y` in my opinion.

**Comment by jamievicary** [comment]
Chiara good for you to look at?

**Comment by regular-citizen** [comment]
Merged PR to reduce the amount of rendering primitives issued.
I will make another PR to actually clean up the tikz code.
