### ISSUE TITLE
Moving between slices with the arrow keys

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#54]
As mentioned in #45 it would be great if we could navigate between adjacent slices in the diagram with the up and down key and go to the parent slice with the left key.

To descend slices, pressing the right arrow key could enable a mode where the user can select a slice to descend into with the arrow keys. The selected slice is visually highlighted in some way and pressing the up and down key in this mode would change the selected slice. By pressing right again the workspace would descent into the selected slice.

With these changes implemented a diagram can be navigated solely using the arrow keys.

**Comment by jamievicary** [comment]
I really like this idea.

**Comment by jamievicary** [comment]
Please could the actions of "up" and "down" be reversed. I believe it would be more natural if the progression "S","R0","S0","R1","S1",... was produced by starting at "S" and repeatedly pressing the "up" key, as we usually draw diagrams with their source slice at the bottom. But at the moment this progression is obtained by repeatedly pressing the "down" key.
