### ISSUE TITLE
Different colours for wires and surfaces in GL

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#549]
Similar to the SVG renderer, wires and surfaces should be rendered with lighter shades of the colour used for points. This will let us distinguish them when the lighting is turned off (which we may want for animated 2D diagrams).

**Comment by jamievicary** [comment]
We will need to think about how this interacts with the orientation information, which we are also planning to indicate via the lightness.

**Comment by jamievicary** [comment]
Related to #550

**Comment by thud** [comment]
#668 fixes the first half of this issue. Orientation information is still further down the track.

**Comment by calintat** [comment]
Thanks Jasper!
