### ISSUE TITLE
Dragging regular slice in 1D crashes

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#563]
Crash is here: https://github.com/homotopy-io/homotopy-rs/blob/1665c939047ebf1c7962cee87969a22075620916/homotopy-web/src/app/diagram_svg.rs#L532

We should do expansion in a regular slice (i.e. smoothing) in this case.

**Comment by NickHu** [comment]
Whoops, I thought it was genuinely unreachable
