### ISSUE TITLE
Problem with labelled contraction/expansion

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#568]
Consider the following scenario with three beads a+, a- and b on two wires:
![filename_todo](https://user-images.githubusercontent.com/16837293/178109619-067e6185-b83e-4732-bd7c-0be22ea99df7.svg)

Now drag a- down to annihilate it with a+. Note you can't do this by dragging a+ up as that will do an interchanger.

Actual result:
![filename_todo(1)](https://user-images.githubusercontent.com/16837293/178109646-c4f7433c-32e9-4f5b-912b-cbe391579a19.svg)

Expected result:
![filename_todo(2)](https://user-images.githubusercontent.com/16837293/178109675-aa10db6e-7331-482d-9ef2-c5930013de99.svg)

**Comment by calintat** [comment]
The problem is that we attempt to smooth the whole diagram
![filename_todo(1)](https://user-images.githubusercontent.com/16837293/178109816-f3d927df-fe75-4515-b7bd-a56d5fc1d9eb.svg)
which doesn't work because the forward and backward rewrites are different. I think instead we should attempt to smooth in each subproblem (i.e. in `collapse_base`) and then glue these together in `collapse_recursive`.

**Comment by calintat** [comment]
Also it's impossible to smooth this manually either (for the same reason).

This is also a problem in the unlabelled version, for example there is no way to simplify this:
![filename_todo(3)](https://user-images.githubusercontent.com/16837293/178109998-a98f1498-332d-442d-a5d5-cb4046151fcb.svg)

**Comment by NickHu** [comment]
Fixed by 506da953e24b8d6fdbd76f4bc7224fc988fc300d
