### ISSUE TITLE
Detect if a rewrite is a homotopy

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#570]
Does anyone know how we could check if a rewrite is a homotopy?

I think I need to be able to do this in my `oriented` branch as a pre-condition on smoothing in the absence of typechecking or Nick's labels (otherwise you would be able to smooth any endomorphism-like diagram).

My first attempt was a function which recursively checks that all 0-dimensional subslices are identities, but that doesn't work because any rewrite which introduces a scalar would be incorrectly labelled as a homotopy.

**Comment by calintat** [comment]
Actually nothing recursive seems to work because the subslices of a homotopy need not be homotopies.

**Comment by jamievicary** [comment]
I think an n-rewrite R:A-->B is a homotopy just when every generator in B
has dimension at most n-1. At least, I think this might serve for your
purposes. Let me know what you think.

**Comment by calintat** [comment]
Yes of course that makes sense.
