### ISSUE TITLE
Clear boundary

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#585]
Now that we have boundary previews, it would be nice to have an "X" button to clear the boundary.

**Comment by doctorn** [comment]
I want to be able to click on a boundary preview to recover the diagram

**Comment by H-Yulong** [comment]
I like that idea as well, will work on it

**Comment by calintat** [comment]
Thanks Yulong!

**Comment by H-Yulong** [comment]
Also, would it be helpful to click on the box with "Source/Target" text on it to switch between source and target?

**Comment by NickHu** [comment]
Sounds good
