### ISSUE TITLE
Migrate 2d renderer to `ultraviolet`

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#587]
Right now we are using two linear algebra libraries, `euclid` in the 2d renderer, and `ultraviolet` in the 3d/4d renderer. It would be great if we could migrate the 2d renderer to `ultraviolet` so we only use library in the whole module.

**Comment by calintat** [comment]
The reason we should use `ultraviolet` over `euclid` is performance.

**Comment by regular-citizen** [comment]
I had a go at this and I'm not sure this is possible. The 2d renderer uses lyon extensively, which ties us to euclid2d.
While in theory it may be possible to hide euclid's types from our methods, we would need to convert ultraviolet's Vec2 into euclid's Point2D whenever we're calling methods in lyon.

The following mini-patch illustrates the difficulties:
```
diff --git a/homotopy-graphics/src/svg/shape.rs b/homotopy-graphics/src/svg/shape.rs
index 1846c40..022148a 100644
--- a/homotopy-graphics/src/svg/shape.rs
+++ b/homotopy-graphics/src/svg/shape.rs
@@ -1,6 +1,7 @@
 use std::fmt::Write;
 
 use euclid::default::{Box2D, Point2D};
+use ultraviolet::vec::{Vec2, Vec4};
 use lyon_algorithms::{aabb::fast_bounding_box, hit_test::hit_test_path};
 use lyon_geom::{CubicBezierSegment, QuadraticBezierSegment};
 use lyon_path::Path;
@@ -10,22 +11,24 @@ pub type Point = Point2D<f32>;
 #[derive(Debug, Clone)]
 pub struct Fill {
     pub path: Path,
-    bounds: Box2D<f32>,
+    bounds: Vec4,
 }
 
 impl Fill {
     pub fn new(path: Path) -> Self {
-        let bounds = fast_bounding_box(path.into_iter());
+        let aabb = fast_bounding_box(path.into_iter());
+        let bounds = Vec4::new(aabb.min.x, aabb.min.y, aabb.max.x, aabb.max.y);
         Self { path, bounds }
     }
 
-    pub fn contains_point(&self, point: Point, tolerance: f32) -> bool {
-        if !self.bounds.contains(point) {
+    pub fn contains_point(&self, point: Vec2, tolerance: f32) -> bool {
+        let contained = self.bounds.x <= point.x && point.x < self.bounds.z && self.bounds.y <= point.y && point.y < self.bounds.w;
+        if !contained {
             return false;
         }
 
         hit_test_path(
-            &point,
+            &Point2D::new(point.x, point.y),
             self.path.into_iter(),
             lyon_path::FillRule::NonZero,
             tolerance,
```

**Comment by calintat** [comment]
Thanks for looking into this Chiara!

I agree, it doesn't seem worth it to switch if we are still going to need the `euclid` dependency.

**Comment by calintat** [comment]
Some notes on switching the 3D/4D renderer to `euclid`:
- performance might not be a concern anymore as we got rid of the matrix multiplications in subdivision,
- unfortunately `euclid` does not support 4D points  as it's really designed for 2D graphics :(

Therefore, I am closing as this as "won't fix".
