### ISSUE TITLE
Highlight error

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#59]
[filename_todo (29).zip](https://github.com/homotopy-io/homotopy-rs/files/6384198/filename_todo.29.zip)
To trigger this error, load the attached workspace and click the uppermost vertex.
![highlight_error](https://user-images.githubusercontent.com/10602270/116235603-fa665000-a755-11eb-8440-eb17d07ea3c2.png)

**Comment by jamievicary** [comment]
I've added a new "priority" label, indicating issues that should be relatively straightforward to fix, and will improve my quality of life as I try to build this Perko isotopy proof.

**Comment by jamievicary** [comment]
Calin will check a historical version to see if the issue is reproducible there

**Comment by NickHu** [comment]
I did a git bisect and determined that it stopped importing successfully here: 073f6db11bcc476d1861a070461a1f0408b0197d

**Comment by calintat** [comment]
Here is an up to date workspace: [homotopy_io_export.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/12039258/homotopy_io_export.hom.zip)
