### ISSUE TITLE
Possible bug in labelled contraction

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#597]
The following
![filename_todo](https://user-images.githubusercontent.com/16837293/179808099-444a2a72-eb56-4bf6-9868-89fcbae7f169.svg)
should contract to
![filename_todo(1)](https://user-images.githubusercontent.com/16837293/179808208-b285bc51-6765-484e-8c11-87c51e18b5e6.svg)

This works fine in the unlabelled version but it's invalid in the labelled version. There are no inverses here, so this should just work.

**Comment by calintat** [comment]
This is also invalid as an oriented contraction.

**Comment by jamievicary** [comment]
Hang on that means it has nothing to do with the labelled contraction code. Maybe the problem is that it's trying to annihilate the strands rather than braid them? What if you go into the slice and drag diagonally so it's definitely going to try to do the interchanger?

**Comment by calintat** [comment]
I thought so too, but even if you go inside the singular slice and drag one of them diagonally, it still doesn't work.

**Comment by calintat** [comment]
The error is triggered here where we propagate an expansion in a singular level to the whole diagram:
https://github.com/homotopy-io/homotopy-rs/blob/76953762548c131af8df764f18ecef0b7e8316a6/homotopy-core/src/contraction.rs#L267-L275

It's because the height is out of bounds, we probably need to adjust it after contraction.

**Comment by calintat** [comment]
Fixed by https://github.com/homotopy-io/homotopy-rs/commit/7a0e698bd940fbeefe9a1c1fbe48e83abe156019.
