### ISSUE TITLE
Labelled expansion introduces weak units

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#598]
Start with the following:
![filename_todo(2)](https://user-images.githubusercontent.com/16837293/179808888-b54db9d0-1ae3-4497-8752-c92a67f760f8.svg)
Do a contraction in a regular height:
![filename_todo(3)](https://user-images.githubusercontent.com/16837293/179809495-32698fef-a845-4561-a9e7-e3265fbcdf76.svg)
Now do an expansion in the second singular height:
![filename_todo(4)](https://user-images.githubusercontent.com/16837293/179809754-9b13519f-64c2-4b34-a5d7-ac1389dd7d15.svg)

We probably want to smooth the result of expansion or something like that.

**Comment by calintat** [comment]
Also it's bizarre that you can do a contraction in a regular slice by dragging horizontally. I was convinced that that's not implemented (see #567), but I think that's only the case when you have a single regular slice.

**Comment by jamievicary** [comment]
Did you mean to write, "Now do an expansion the the second singular height"?

**Comment by jamievicary** [comment]
That's what I said right?

**Comment by calintat** [comment]
Yep, I misread what you wrote.

Here is an even better example:
![filename_todo(5)](https://user-images.githubusercontent.com/16837293/179812046-3d78c6fc-2761-4d15-bb6f-3e259570fa35.svg)
and do an expansion in singular 0:
![filename_todo(6)](https://user-images.githubusercontent.com/16837293/179812072-379f3d15-4d1e-46c8-9408-08d817016d4a.svg)

**Comment by calintat** [comment]
@NickHu This is expansion, not contraction. I don't think contraction will create weak units as we always smooth the contracted diagram. I reckon we want to do something similar here. Or do labelled normalisation.

**Comment by jamievicary** [comment]
We made a concrete plan for what to do with contraction, did we write
that into an issue?

**Comment by calintat** [comment]
I know how to fix this without normalisation.

This is expansion in a singular slice $s_n$ of a diagram $D$. Here is what the unlabelled tool does. It first propagates the expansion to the whole diagram via factorisation to get a diagram $D'$, then normalises $D'$ to get a diagram $D''$.

In the example above, it will look something like this: 
![IMG_2C4A97147F97-1](https://user-images.githubusercontent.com/16837293/180015131-0e538b2d-e7a5-48b1-b51a-97957a86feac.jpeg)

But the result is a smoothing and we could have computed this directly without computing $e$ (which we completely discard) and without normalisation. Therefore, I think we should change expansion in a singular slice as follows:
1) start by attempting to remove $s_n$ by smoothing (we know how to check if this is possible),
2) if not, call the recursive case and propagate via factorisation/antipushout (and we don't need to normalise the result).

Let me know what you think. This will be a very easy fix.

**Comment by jamievicary** [comment]
I am doing admin today and my brain is not functioning properly to think through all the angles on this. If you're confident (and understand how it fits with other related functionality) then I think you should go ahead and do it. On Friday when we meet can you please give me and Nick a little presentation on all of these aspects --- contraction and expansion in singular and regular slices, also contraction-expansion, and when we auto-smooth and when we don't --- and the rationale for how they are treated in the tool.

**Comment by jamievicary** [comment]
I have never seen any evidence that labelled normalization is required for this sort of functionality.
