### ISSUE TITLE
Signature editing

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#6]
- [X] Create 0-dimensional generators
- [X] Create generators from a source and target
- [x] Delete generators
- [x] Edit generator names
- [ ] Edit generator colors

**Comment by jamievicary** [comment]
Added a "blocking" tag because this is blocking me from making good progress on the Perko knot isotopy.

**Comment by NickHu** [comment]
Added the ability to edit generator names in 93292fcf1a7c1492cdb7dfaaec179cb8fd862993

**Comment by jamievicary** [comment]
Has this potentially broken #10.

**Comment by NickHu** [comment]
Generators can now be deleted, and they recursively remove all entities which mention them

**Comment by jamievicary** [comment]
Great, and I love having this hidden under the "edit" icon, keeping it safe
from accidental use.

**Comment by jamievicary** [comment]
Let's get this closed, only the colours left

**Comment by jamievicary** [comment]
@NickHu, how about making the colour indicator a square rather than a strip (i.e. make the width greater, to be equal to the height) -- could you give that a try? That would regularize the display, where all other icons are currently square-shaped.

**Comment by NickHu** [comment]
@Akvile1206 has finished this off!

**Comment by jamievicary** [comment]
A wondrous moment!
