### ISSUE TITLE
Alternative allocator

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#61]
Nick explained to me there's an alternative allocator, with a larger file size but potentially better performance. It would be great to try this out and see how much of a difference it makes.

**Comment by NickHu** [comment]
Jamie is referring to wee_alloc:

 https://github.com/homotopy-io/homotopy-rs/blob/7b42f4202dd945c54015e814788ebb03efa93a62/homotopy-web/src/lib.rs#L55-L61

**Comment by jamievicary** [comment]
Ah great so have you already done the comparison using your new benchmarking wizardry?

**Comment by NickHu** [comment]
No, the benchmarks only operate on `homotopy_core`, which are run on my local architecture `x86_64-unknown-linux-gnu`. The WASM compile target is `wasm32-unknown-unknown`, and the benchmark runner doesn't handle these.

**Comment by jamievicary** [comment]
Ah I see. So does this mean that the benchmarking can't help us with WASM
performance issues?

At the very least you just run the two builds locally with each different
allocator, and try my expensive_operation scenario with the devtools
performance tracker, and write down the numbers. It would at least let us
see if are getting an order-of-magnitude improvement.

>

**Comment by jamievicary** [comment]
Is the current master branch using the default allocator?

**Comment by zrho** [comment]
Not yet, but soon.
