### ISSUE TITLE
Coinductive bubbling, expansion/contraction propagation

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#610]
Collecting some final issues discussed between NH, CT, JV today.
- [x] #613
- [ ] Need subdiagrams to flow along rewrites, we worked out how to do this nicely #30 CT
- [x] #612
- [x] Cone factorisation broken still #242 NH
- [x] #611

**Comment by calintat** [comment]
![image](https://user-images.githubusercontent.com/16837293/180493955-66870fe9-bdab-4454-96e8-a19232a93b52.jpeg)

**Comment by calintat** [comment]
I am closing this as the remaining task (updating the slice path after contraction/expansion) is being tracked separately.
