### ISSUE TITLE
Need to be able to bubble cospans NH

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#612]

**Comment by NickHu** [comment]
I think we can consider this particular issue closed; bubbles can be inserted now. However, because of #617 they can only be attached on the diagram boundaries currently.

**Comment by jamievicary** [comment]
Thanks Nick! So is it now possible to click in the interior of a diagram and insert a bubble?

**Comment by NickHu** [comment]
I think because of stupid bugs in the UI (e.g. #617) it's only possible to do it on the Source/Target of a diagram. Annoyingly, this means you can't insert a bubble inside another bubble. I'm confident that the logic should be correct in the general case though.

**Comment by jamievicary** [comment]
Understood, we can obviously revisit this if necessary at a later date.

**Comment by calintat** [comment]
Reopening this as it's broken again.

**Comment by calintat** [comment]
I reimplemented bubbling so that it works with the orientation labels. It wasn't that hard.

**Comment by jamievicary** [comment]
Thanks Calin what technique did you use?

**Comment by calintat** [comment]
Same technique we came up with a while ago. I just had to adjust it because now we have to construct these directed identities manually.

**Comment by jamievicary** [comment]
Got it.
