### ISSUE TITLE
In contract base, do cone-wise smoothing (including orientation 0 check), then coarse smoothing CT

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#613]

**Comment by NickHu** [comment]
Fixed by 506da953e24b8d6fdbd76f4bc7224fc988fc300d

**Comment by calintat** [comment]
Reopening this as it's broken. See https://github.com/homotopy-io/homotopy-rs/issues/622#issuecomment-1195749823.

**Comment by calintat** [comment]
Fixed by https://github.com/homotopy-io/homotopy-rs/commit/d55b3c67b6c4fb9997acfee6162a6ce6bce18668.
