### ISSUE TITLE
Actions are unnecessarily added to the undo/redo stack

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#614]
For example, if you select a generator from the signature while there is a diagram in the workspace, that does nothing, but it's still added to the history so you can technically undo it. Similar for some other actions.

Generally, if an action doesn't do anything, it shouldn't just return `Ok(())`, it should return an error. That usually means the action shouldn't have been triggered in the first place.

**Comment by regular-citizen** [comment]
This bug seems to only apply to mouse selections, but not keyboard shortcuts.

**Comment by doctorn** [comment]
I think we just need some smarter logic here:

https://github.com/homotopy-io/homotopy-rs/blob/c99330dd7c913f413f83692b0ec26d1f0df7eb6b/homotopy-web/src/model/proof.rs#L175-L181

**Comment by calintat** [comment]
Actually we need to carefully define when actions are valid (see Action::is_valid). If an action is invalid it won't be added to the undo/history stack.

**Comment by calintat** [comment]
For the SelectGenerator action I mentioned, we don't do that so that's the problem.

**Comment by regular-citizen** [comment]
Is this still open? I cannot reproduce it anymore for SelectGenerator.

There is still the "letter-wise actions" for metadata, but that is part of #745.

**Comment by calintat** [comment]
Fixed by a34efaba30a49fbcda4e1a895bc7ec7982465226.
