### ISSUE TITLE
Keypresses in cell name edit interface propagate to the UI and trigger operations

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#62]
For example, try creating a 0-cell and calling it "aaaa", you end up with 4 new 0-cells.

**Comment by jamievicary** [comment]
Blocking because this makes it rather horrific to build the signature.

**Comment by NickHu** [comment]
Likely a regression from f4738d4b43a34bdfc25c7c0d75184d38455410a3 (it worked when I first added it)
