### ISSUE TITLE
Bug in expansion bubbling

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#620]
Start with a wire and its inverse, next to a 2-cell:
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/181025065-3e5809f4-87de-4edb-8924-2414cad09045.svg)

Perform a contraction in the singular slice:
![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/181025212-0cea4deb-555d-400a-a4e8-1cbb223af798.svg)

We have now introduced two copies of that 2-cell which is wrong. There is no way to contract that further.

**Comment by calintat** [comment]
I am not sure what the expected result even is here, because it's ambigous:

![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/181026044-b5e2944c-689a-4bf7-8b9e-d33cce2192e6.svg) ![homotopy_io_export(3)](https://user-images.githubusercontent.com/16837293/181026060-f1e3bb61-e609-498e-854f-af97d4ed28ae.svg)

Maybe we shouldn't allow contraction in singular 0 in this case, as you can just do contraction in regular 0 or regular 1 to get either one of the above.

**Comment by NickHu** [comment]
I think it needs to do a biased contraction here.

**Comment by calintat** [comment]
What does that mean?

**Comment by calintat** [comment]
Right, so the question is how do we detect when you shouldn't be able to contract in a singular slice?

**Comment by NickHu** [comment]
This might just fix itself when factorization is fixed; the problem is that in the recursive case of contraction-in-a-singular-slice, it is trying to generate a `ContractExpand` pair. The contraction seems to be fine, but the expansion is the 'bubble' case of expansion-in-a-singular-slice.

**Comment by calintat** [comment]
Like I thought, this is not caused by factorization. We need to do some mild typechecking to reject things like this.

**Comment by jamievicary** [comment]
Following discussion today we don't want to allow this, it should be rejected as the expansion does not propagate (look at forward & backward rewrites), or in future use anticontraction.

**Comment by calintat** [comment]
This can be triggered directly via expansion:
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/184881648-8d8a4af6-413f-4ad9-8a92-b09f4cda7742.svg)
![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/184881654-27d327df-7d25-47b5-9f64-8a80141a3e06.svg)

Therefore, we should add an extra check in the bubble case of expansion to reject this kind of expansion.
