### ISSUE TITLE
Bubble-popping causes projection to fail

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#622]
If you take the identity on the bubble, then contract it, then project, the application crashes in `projection.rs`.

<details>
<summary>Panic log</summary>
panicked at 'called `Option::unwrap()` on a `None` value', /home/nick/Documents/homotopy-rs/homotopy-core/src/projection.rs:96:61

Stack:

getImports/imports.wbg.__wbg_new_693216e109162396@http://localhost:8080/homotopy_web.js line 49 > srcScript:387:21
console_error_panic_hook::hook::h5a139f443683055e@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[1459]:0x1f061d
core::ops::function::Fn::call::he26567e70db6cb93@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[4715]:0x296bf7
std::panicking::rust_panic_with_hook::h1c368a27f9b0afe1@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[2942]:0x270a95
std::panicking::begin_panic_handler::{{closure}}::h8e1f8b682ca33009@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3317]:0x28282d
std::sys_common::backtrace::__rust_end_short_backtrace::h7f7da41799766719@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[4335]:0x295886
rust_begin_unwind@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3933]:0x291df7
core::panicking::panic_fmt::hcdb13a4b2416cf82@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3937]:0x291eed
core::panicking::panic::ha8ced62e366a0d64@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3868]:0x290d2a
homotopy_core::projection::Projection<_>::new::hc3c93b8a22fcf5ef@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[258]:0x7a335
homotopy_web::app::diagram_svg::PreparedDiagram<_>::new::hec153064c2816731@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[373]:0xe1c54
<homotopy_web::app::diagram_svg::DiagramSvg<_> as yew::html::component::Component>::changed::h931ea43bad705492@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[895]:0x19425e
<yew::html::component::lifecycle::UpdateRunner<COMP> as yew::scheduler::Runnable>::run::h05bc4fc94f427b94@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[437]:0x1037f8
std::thread::local::LocalKey<T>::with::hc21852dcad9f4b82@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[2130]:0x23754a
yew::scheduler::start::h9737020cafa29921@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[4714]:0x296bef
yew::html::component::scope::Scope<COMP>::callback_with_passive::{{closure}}::hf4f179ca6c7a07f3@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3380]:0x284ac0
yew::callback::Callback<IN>::emit::h86d02d15020916fe@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[2985]:0x273078
yew::callback::Callback<IN>::reform::{{closure}}::h1923ac8b2cd5bf40@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3818]:0x28fe4b
yew::callback::Callback<IN>::emit::hab0301fb34845d62@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3180]:0x27ce48
yew::callback::Callback<IN>::reform::{{closure}}::h1eae87ab429c88c0@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[4049]:0x29353b
yew::callback::Callback<IN>::emit::h55a52115436530cd@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3211]:0x27e498
yew::callback::Callback<IN>::reform::{{closure}}::h646c36e015058ed1@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3342]:0x2835e1
yew::callback::Callback<IN>::emit::h02cd3be3e5a8653f@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[3214]:0x27e6bb
<yew::html::listener::events::onclick::Wrapper as yew::virtual_dom::listeners::Listener>::handle::h68cf7b513e73d190@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[4645]:0x29695d
yew::virtual_dom::listeners::Registry::run_handlers::{{closure}}::h169a6086f9799bac@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[1053]:0x1b397f
yew::virtual_dom::listeners::Registry::handle::h28f69ffbeb022a75@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[965]:0x1a2ba7
yew::virtual_dom::listeners::GlobalHandlers::ensure_handled::{{closure}}::{{closure}}::h1821ab407f77d597@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[4387]:0x295c37
<dyn core::ops::function::Fn<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hb4c35f93c34480cd@http://localhost:8080/homotopy_web_bg.wasm:wasm-function[4189]:0x2949c0
__wbg_adapter_40@http://localhost:8080/homotopy_web.js line 49 > srcScript:262:10
real@http://localhost:8080/homotopy_web.js line 49 > srcScript:244:20
@http://localhost:8080/:49:68
EventListener.handleEvent*EventTarget.prototype.addEventListener</<@eval:4:42
@http://localhost:8080/:49:12

homotopy_web.js line 49 > srcScript:399:21
</details>

**Comment by calintat** [comment]
The crash is caused by `DiagramN::slice`, it's an index out of bounds error. Probably related to the other crashed we've seen.

**Comment by NickHu** [comment]
> The crash is caused by `DiagramN::slice`, it's an index out of bounds error. Probably related to the other crashed we've seen.

I think this is a separate issue perhaps

**Comment by calintat** [comment]
> This patch
> 
> ```diff
> diff --git a/homotopy-core/src/projection.rs b/homotopy-core/src/projection.rs
> index b3c2157..af21b6a 100644
> --- a/homotopy-core/src/projection.rs
> +++ b/homotopy-core/src/projection.rs
> @@ -93,7 +93,10 @@ impl<const N: usize> Projection<N> {
>                  Diagram::Diagram0(g) => *g,
>                  Diagram::DiagramN(d) => match depths.node_depth(coord) {
>                      None => diagram.max_generator(),
> -                    Some(i) => d.slice(Height::Singular(i)).unwrap().max_generator(),
> +                    Some(i) => d
> +                        .slice(Height::Singular(i))
> +                        .unwrap_or_else(|| d.source())
> +                        .max_generator(),
>                  },
>              };
> ```
> 
> fixes this error for me.
> 
> I.e. (in Morse projection) this allows to go from ![image](https://user-images.githubusercontent.com/450276/181040485-1eff32df-009e-434f-aefe-866c89530817.png) to ![image](https://user-images.githubusercontent.com/450276/181040519-53f22a71-8ae0-472c-a3d4-c67547ba0d98.png)
> 
> I can't tell at-a-glance whether this is the correct fix though; what do you think @calintat?

I need to think about this, because I am fairly certain the depth should always point to a singular slice, so the `unwrap` should have been correct. However, if you're gonna merge it, please use `diagram` instead of `d.source()`, that feels more correct.

**Comment by calintat** [comment]
I think this contraction is malformed. This is the contraction/expansion pair:

![homotopy_io_export(4)](https://user-images.githubusercontent.com/16837293/181064984-3b9dba84-c018-4e69-84bc-54be40a0a93e.svg) → ![homotopy_io_export(5)](https://user-images.githubusercontent.com/16837293/181065000-a0c473fd-e3ec-4510-9b16-d5119cde37db.svg) ← ![homotopy_io_export(6)](https://user-images.githubusercontent.com/16837293/181065075-59dfb799-c85c-4f26-9e8d-a105e86d5610.svg)

That middle slice is wrong, it should be a scalar (labelled by the same generator as the wire but with orientation 0).

**Comment by calintat** [comment]
This was working fine before 506da953e24b8d6fdbd76f4bc7224fc988fc300d. @NickHu your cone-wise smoothing must be wrong, it produces malformed results.

**Comment by calintat** [comment]
I think the problem is here:

https://github.com/homotopy-io/homotopy-rs/blob/a7228f5028676eab26478e16b9e6ee72c4b76792/homotopy-core/src/contraction.rs#L173-L233

You're changed `cospan` so it's no longer compatible with the legs of the colimit. You need to do the cone-wise smoothing as a rewrite (namely the expansion part of the pair). The annoying thing is you also need to do coarse smoothing after that so you will end up with two backwards rewrites

$D \xrightarrow{\text{contract}} D' \xleftarrow{\text{cone-wise smoothing}} D'' \xleftarrow{\text{coarse smoothing}} D'''$

Normally I'd say compose the cone-wise smoothing and coarse smoothing, but since composition is not guaranteed to work, we need to do construct the composite manually.
