### ISSUE TITLE
3D bubble doesn't render

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#624]
If you take the identity on the bubble, then contract both ends in Morse projection, this should give the diagram which has slices[^2]
| Height  | Diagram |
| ------------- | ------------- |
| $r_0$ | $\text{id}(\text{id} (x))$|
| $s_0$ | weak unit on $\text{id}(\text{id} (x))$ |
| $r_1$ | 2D bubble |
| $s_1$ | weak unit on $\text{id}(\text{id} (x))$ |
| $r_2$ | $\text{id}(\text{id} (x))$|

The Morse projection looks like this[^1]:
![image](https://user-images.githubusercontent.com/450276/181059055-80d1f914-f4cc-4685-8822-f275fd9ea088.png)
However, the 3D renderer doesn't render anything.

If I behead the diagram:
![image](https://user-images.githubusercontent.com/450276/181059474-ed51606a-51a2-4082-bdeb-6d4a3c8f28ad.png)
In 3D, I get a cylinder which is not centred:
![image](https://user-images.githubusercontent.com/450276/181059290-bf6ad60f-4e42-4a05-8cd3-c664a505a949.png)

I think this is wrong too - it should be showing me a hemisphere, shouldn't it?

[^1]: To get it to not crash, apply patch in #622
[^2]: Making this workspace, exporting, and then importing fails, which should be another bug

**Comment by calintat** [comment]
Ok, the import fails because it's malformed, so that means we are making malformed diagrams somewhere...

My guess is in the contraction of the bubble (#622).

**Comment by jamievicary** [comment]
Can we add in a well-formedness check after all nontrivial operations
please. (We certainly had this before but removed it.)

**Comment by calintat** [comment]
We never removed it, it's just we're using unsafe versions of every method...

**Comment by calintat** [comment]
Wait, never mind, the checks are just disabled, they should've caught this. I will re-enable them for everything.

**Comment by calintat** [comment]
The checks are now re-enabled on both beta and alpha, and it's not possible to build this malformed diagram anymore.
