### ISSUE TITLE
Cone-wise smoothing in expansion

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#629]
Now that we figured out how cone-wise smoothing works, I think we should add it as a case in expansion.

For example, if you have the following diagram:
![homotopy_io_export(10)](https://user-images.githubusercontent.com/16837293/181115900-8a8fb867-0ba2-4110-ab01-6c0601a260a3.svg)
you should be able to smooth it by dragging vertically from R0 to S0 to get
![homotopy_io_export(11)](https://user-images.githubusercontent.com/16837293/181116091-6dbf0020-2f0f-4443-9f24-b0af00ee2ee6.svg)

**Comment by jamievicary** [comment]
Yes this makes sense. And furthermore the specific cone that it smooths should depend on the x coordinate from which you dragged.

**Comment by calintat** [comment]
This was implemented a while ago but I forgot to close it.
