### ISSUE TITLE
Bad signature panel attachment after selection error

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#636]
If an error is triggered before anything on the side panel is opened for the first time after page load, e.g. the signature panel or the settings, the view will attach on the wrong side of the screen.

Steps to reproduce:
- Load a fresh tab
- Press any keyboard shortcut to select a non-existing generator (e.g. hit 1)
- Open any side panel (e.g. hit A or click on settings)

![image](https://user-images.githubusercontent.com/7887982/181725864-68ffb083-daf7-4835-b088-e1cc0c9a302e.png)

**Comment by regular-citizen** [comment]
Originally tested on Firefox/Linux, reproduced on Chromium/Linux.

**Comment by calintat** [comment]
This is so bizarre. Thanks for finding this Chiara!
