### ISSUE TITLE
Homotopy.io should not complain about unsaved work when there is no work to be saved

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#637]
If any action is triggered after page load, the website will complain about unsaved work when attempting to close or reload a tab.
This should not happen if both workspace and history are empty.

Steps to reproduce:
- Load a fresh tab
- Perform an invalid action (e.g. hit 1), or perform an ineffective action (e.g. open project tab),
- Reload tab.

**Comment by calintat** [comment]
I don't think we can do this. The history is empty after a failed action.

**Comment by regular-citizen** [comment]
Can we detect that and avoid issuing a "unsaved work" alert?

**Comment by calintat** [comment]
I don't know. At the moment, we just use the `onbeforeunload` hook to show that warning. I don't actually know why it's not shown if say you loaded the page and immediately reloaded. Maybe it's because the browser knows you haven't interacted with the website yet, I don't know.

**Comment by doctorn** [comment]
I can't quite remember the details but couldn't the `onbeforeunload` hook contain some logic that checks for non-trivial histories?

**Comment by calintat** [comment]
> I can't quite remember the details but couldn't the `onbeforeunload` hook contain some logic that checks for non-trivial histories?

Maybe
