### ISSUE TITLE
Removing the regular slices

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#639]
Today we (CT & NH) did some pair programming and we figured out we can remove the regular slices, and this should fix everything!!!

Key takeaways:
- we can remove regular slices from cones,
- scalars are disambiguated from their inverses by their orientation labels,
- we can remove orientation data from identity 0-rewrites (so $f^+ \to f^0$ can just be `None`) -- to do this, we need to move the orientation data into 0-rewrites (i.e. a 0-rewrite should know the orientation label of its target), and this should be an Option type and only horizontal edges should know about the orientation. This requires more work. It should be possible to deduce orientation labels from framing labels.
- conceptually, labels, instead of being a vector, they are actually sets of vectors of primitive labels (sums of products) - we can talk about the details later
- implementation-wise, we need to be careful in graph explosion when creating the regular slices: a regular slice in the graph is a composite, and it can be done in one of two ways; we need to do both, check if the labels agree, if they do we keep them, if not we discard them (corresponding to using the forward and backward rewrites of the target cospan). So for a scalar, we discard labels on the regular slices, for a cancellation move, we will have a label on the regular slice.
- distinguishing between unit cones and non-unit cones only needs to happen in graph explosion
- not having to compute the regular slices means that things like factorisation, antipushout, normalisation, type checking should work as before.

**Comment by calintat** [comment]
As the cherry on top: we can maintain backwards compatibility with master, and make it easier for the migration from the JS version.

**Comment by jamievicary** [comment]
Shall we have a call to discuss? Not sure I understand yet. Regular slices
are a key part of the labelled framework.

**Comment by calintat** [comment]
I think we're both pretty tired after having a meeting for 5 hours and we need to pack for tomorrow. But we've made a pull request and there is a preview link so you can play with this version.

**Comment by jamievicary** [comment]
Ok. There are a variety of reasons why I am quite sure regular slices are
logically essential for framed invertible generators. I will collect my
thoughts and send a message soon.

**Comment by calintat** [comment]
I think the key takeaway for us is that no all regular slices need labels and the ones that do, we can derive those labels from the data we already have.

**Comment by jamievicary** [comment]
Let's discuss further by email!!
