### ISSUE TITLE
Notifications for commits

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#64]
It seems I'm not getting automatic email notifications from github when a commit references an issue, so I'm missing a lot of activity. For example, I didn't realize Lukas had pushed a fix for #54. Can I set it up so that I'm automatically emailed any commits to master? I've "watched" and "starred" the repository.

**Comment by NickHu** [comment]
There's a repository setting for this, which I've added you to now. Warning: this will be extremely annoying.

**Comment by jamievicary** [comment]
Thanks Nick, it's OK if it's annoying, I can direct them into a separate
folder.

**Comment by jamievicary** [comment]
Of course I really only want this for commits to master, but presumably I
can filter out non-master commits easily enough...
