### ISSUE TITLE
save-as dialogue when exporting from beta?

### ISSUE THREAD

**Issue by vinnylarouge** [homotopy-io/homotopy-rs#641]
i'm saving pretty often to guard against crashes, it would be nice to have an option to save with a name i choose.

**Comment by regular-citizen** [comment]
I don't think it is possible to implement this. From https://github.com/eligrey/FileSaver.js/, it appears it is basically impossible to implement this in a reliable cross-browser way.
For example, Firefox does not support this (https://bugzilla.mozilla.org/show_bug.cgi?id=1302919).

I believe we should close it as WONTFIX, thoughts?

**Comment by calintat** [comment]
But https://github.com/eligrey/FileSaver.js/ says it works on Firefox 20+, Safari 10.1+, and Chrome. Isn't that good enough?

**Comment by regular-citizen** [comment]
Yes, however, I was mistaken as to what the library actually does: it's only a polyfiller for downloads with a certain file name, something we already do reliably (#857). It does not prompt the user to choose a file name.

The mozilla issue together with https://salesforce.stackexchange.com/a/359827 leads me to believe this really cannot be done.

**Comment by regular-citizen** [comment]
Yes, we'll deal with drag and drop separately.

**Comment by calintat** [comment]
Ok I am closing this then. @vinnylarouge sorry but this proved way more difficult than we imagined.
