### ISSUE TITLE
Changing generator name issues an history event for each character

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#645]
Changing the name of a generator spams the history with all the character by character changes.
It should issue a single history event with the change of generator name.

Steps to reproduce:
- Add a generator
- Rename generator to a long name
- Undo repeatedly

**Comment by calintat** [comment]
Has this changed recently? Because I don't remember this being the case.

**Comment by regular-citizen** [comment]
It is definitely the case right now. If you're positive that this was introduced recently, we can figure out the commit that caused this by bisecting.

**Comment by calintat** [comment]
Yeah that's good idea.

**Comment by regular-citizen** [comment]
Regression introduced at 27c0f7e486fff9323b4aa1d693293b0420fd1364 by @thud.

**Comment by thud** [comment]
Yep, this is an artifact of instant style updates. I missed this originally but should be a relatively easy fix (by only dispatching rename update on `done` button). We could even dispatch on unfocus events potentially which might be more user friendly (not sure).

**Comment by doctorn** [comment]
You can mark uncommitted changes as irrelevant actions and the existing machinery should handle this

**Comment by doctorn** [comment]
See `homotopy_web::model::proof::Action::relevant`

**Comment by calintat** [comment]
Generator renamings shouldn't be irrelevant though, because you want to be able to undo them. I think the best solution is to only update the name on done.
