### ISSUE TITLE
Significant memory usage

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#65]
Creating a high-dimensional diagram using contractions consumes a lot of memory. We should investigate where it goes and if that can be avoided.

**Comment by zrho** [comment]
Instrumenting the hashconsing table seems to show that the number of rewrites, diagrams and cones stays almost constant while total memory usage can balloon to more than a gigabyte. This is somewhat reassuring because it is not the core data structures that necessarily get that big.

**Comment by jamievicary** [comment]
This is interesting, I had noticed a big performance hit after extended use in the same tab, maybe this explains it.

Can someone remind me about how the hashcons table is cleaned of unneeded structures.

**Comment by NickHu** [comment]
It's never cleaned, and memory is never reclaimed, but Lukas is saying this isn't causing the issue

**Comment by zrho** [comment]
The hashcons tables are implemented quite non-optimally. A table for a type `T` is basically a `HashMap<T, Weak<T>>` and there is a collect function (which is not called in any public version yet, but calling it does not fix the memory problem) that removes all the entries whose weak pointer does not point to anything anymore. This does mean - in particular - that everything is stored twice. We could probably figure out a way to do this nicely once we have fixed some more pressing issues, since I don't think at the moment that it's causing the memory issues. I'll try and see if https://github.com/rustwasm/wasm-tracing-allocator can help track this down.

**Comment by zrho** [comment]
This issue completely vanishes for me when I replace wee_alloc with the default allocator. For the example workspace I tested this on, with the default allocator I have roughly constant memory usage around 70MB while with wee_alloc memory usage reaches gigabytes until I get an out of memory error. With the default allocator it's also somewhat faster for me; with wee_alloc Chrome appears to insert loads of GC pauses in order to try and free up memory so that the wasm memory can grow. If I'm not seeing mirages here I think that answers #61 since I am more than happy to trade off a slight bundle size increase for gigabytes of RAM usage and more performance.
