### ISSUE TITLE
White cells are impossible to discern against background

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#657]
This is mostly a problem with white 0-cells.

![white_0cell_invisible](https://user-images.githubusercontent.com/7887982/182916166-139a6642-da60-4a6b-be6a-d50f24d60655.jpg)

**Comment by thud** [comment]
I'm aiming to fix this for the signature panel (excluding previews) as part of #632. I'm not sure if there is a good way of accomplishing it for svg without significant change.

As part of #632, we will be able to tell whether a colour is too light `Color::is_light(&self)` to be shown clearly. This should be of help.

**Comment by regular-citizen** [comment]
I think it's worth considering switching #ffffff to #f6f5f4 for our default white. We can discuss this at the next standup.

A minor thing I just noticed in your #632 build: the custom hex colour field does not accept the "enter" key for "done".
It should be a quick fix though.

**Comment by calintat** [comment]
I like the idea of changing the default white colour to a light grey, but if the user picked true white using the colour picker, we should probably not change that. For example, someone might want to use true white for the unique object of a monoidal category so that the regions blend in with the background.

**Comment by thud** [comment]
> A minor thing I just noticed in your https://github.com/homotopy-io/homotopy-rs/pull/632 build: the custom hex colour field does not accept the "enter" key for "done".

This is fixed I think, assuming the default behaviour should be to exit editing mode completely.

**Comment by regular-citizen** [comment]
> This is fixed I think ([7e881f3](https://github.com/homotopy-io/homotopy-rs/pull/632/commits/7e881f32046554bc4837f7a28a72ef6e321a2f96)), assuming the default behaviour should be to exit editing mode completely.

Thank you for the quick fix, I'm happy with this behaviour, but we could discuss it at the next standup.

> I like the idea of changing the default white colour to a light grey, but if the user picked true white using the colour picker, we should probably not change that. For example, someone might want to use true white for the unique object of a monoidal category so that the regions blend in with the background.

Isn't colour serialised anyway? If it is we wouldn't be breaking old .homs, and "true white" is still one of the colours displayed in the extended colour picker.

**Comment by calintat** [comment]
I meant we should replace white as one of the eight default colours to discourage people from using white.

**Comment by regular-citizen** [comment]
> I meant we should replace white as one of the eight default colours to discourage people from using white.

Amazing, then I guess we all agree on doing it this way. Is #f6f5f4 a good alternative "light grey"?

**Comment by calintat** [comment]
How about #F5F5F5?

**Comment by regular-citizen** [comment]
> How about #F5F5F5?

They're basically indistinguishable, but #F6F5F4 is on the current extended palette. Tbh I'd be happy to switch both to #F5F5F5.

**Comment by calintat** [comment]
In that case don't worry about it. It's just in general grey should have equal amounts of red, green, and blue.

**Comment by regular-citizen** [comment]
@thud any chance you could include this change in your #632 branch? We are most likely going to conflict otherwise.

I think it should just come down to changing homotopy-web/src/model/proof/signature.rs:17

**Comment by thud** [comment]
Have added!

Am I missing something? Where can I find the extended palette / which palette are we using (is it FlatUI)?

**Comment by regular-citizen** [comment]
Thanks!

> Am I missing something? Where can I find the extended palette / which palette are we using (is it FlatUI)?
By extended palette, I meant this:
![image](https://user-images.githubusercontent.com/7887982/183092147-00ee87d4-686f-4655-87d6-de8d50876915.png)

**Comment by doctorn** [comment]
> In that case don't worry about it. It's just in general grey should have equal amounts of red, green, and blue.

(Complete bikeshed but people tend to find slightly warmer greys more visually appealing hence the slight hue shift towards red.)

**Comment by thud** [comment]
Aha, nice thanks.

**Comment by jamievicary** [comment]
Why don't we make the workspace background a light gray?

**Comment by calintat** [comment]
Then we would have the same problem with light grey generators. 

I think the current solution is fine, the default "white" colour is actually a very light grey. And if the user manually sets the colour to true white, it's on them.

**Comment by jamievicary** [comment]
Same here, I made this comment months ago via email and weirdly only just appeared.
