### ISSUE TITLE
Workspaces load slowly compared to js version

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#66]
I have built the same 8-dimensional diagram in both the js and rs versions. The time to import the workspace and draw the initial diagram is 1.5s in the js version, but 8.2s in the rs version.
[Downloads.zip](https://github.com/homotopy-io/homotopy-rs/files/6398321/Downloads.zip)

**Comment by jamievicary** [comment]
The execution trace in the rs version shows lots of core::fmt::Debug, core::fmt::DebugTuple calls, maybe this is related.

**Comment by jamievicary** [comment]
I see it also puts over 200Mb into the console.

**Comment by jamievicary** [comment]
What was the issue here?

**Comment by zrho** [comment]
Exactly as you said, it was printing the entire imported workspace to the console, which is extremely slow.
