### ISSUE TITLE
Contracting in a singular slice without rewrite composition

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#674]

**Comment by jamievicary** [comment]
When we contract in a singular slice, currently we use composition. This needs to be replaced by taking the colimit of the entire dag.

**Comment by NickHu** [comment]
Fixed by 562c45771b54d09e42922e87acac662dd492792c.

I'm a little bit weary about the coordinates that are now a part of the DAG used to determine orientation information...

**Comment by jamievicary** [comment]
Thanks for this Nick, what coordinates do you mean?

**Comment by calintat** [comment]
Each node in the DAG is labelled with a coordinate which is needed to calculate the orientation when you contract. If you remember, the idea was to look at subslices of a given codimension, but to do that need you need the DAG to be stratified so you can identify the subslices.

**Comment by jamievicary** [comment]
Thanks. Hmm I didn't know about that, or maybe I forgot. We should discuss this at some point. Is this a problem for contraction in a singular slice?
