### ISSUE TITLE
Better system for handling biases and contractions

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#675]
In the invertible tool there is sometimes ambiguity as to whether we want to braid or annihilate vertices. We had the idea for a "force collision" hotkey (triggered by holding SHIFT), with the following properties:

- With no hotkey selected, braid if possible, otherwise collide (i.e. bias=0).
- With the hotkey selected, always collide (i.e. bias=0).

This should be a new option on the left-hand menu bar, which is maybe sticky if you click it with the mouse.

**Comment by calintat** [comment]
I've made it so that holding shift forces the bias to be `Same`. This makes it possible to contract a wire and its inverse in 3D by just dragging horizontally. This doesn't solve the problem of the 3D scalar inverse contraction, but that's a different problem.

**Comment by calintat** [comment]
Tracking issue for the other problem: #681.
