### ISSUE TITLE
Hash depends on ordering

### ISSUE THREAD

**Issue by zrho** [homotopy-io/homotopy-rs#68]
The hash of an `HConsed` value is determined by the id of the hash-consed value and not the actual hash of the value. This means that the hash of a diagram or rewrite depends on the operations that have been executed before which is problematic since the hashes are also used for serialisation. Unstable hashes still let you serialise and deserialise workspaces, but they defeat the purpose of using hashes instead of ids in the serialisation format.

**Comment by jamievicary** [comment]
Lukas is this sorted now?

**Comment by zrho** [comment]
Yes
