### ISSUE TITLE
3D scalar inverse

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#681]
There is currently no way to contract a 3D scalar and its inverse.

If you drag vertically, that does a contraction with bias `Same` but that results in an error "contraction ambiguous". It's probably because we are discarding the bias somewhere. If the bias is `Same`, we should probably never discard it and always force an annihilation if possible.

**Comment by jamievicary** [comment]
This is a priority, we need to do this all the time.

**Comment by calintat** [comment]
Fixed by 888c4e97127b34f866a9e8248326dcafcc6f0b9a.

Jamie and I figured out we should never discard 0 biases, only +/- biases.

**Comment by jamievicary** [comment]
At least, let's try this for a while and see if it creates any additional issues!
