### ISSUE TITLE
Cannot insert a braid on a regular level

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#685]
In the attached file, on the alpha build, dragging sideways on a regular level in the appropriate manner should insert a bubble, but nothing happens. There is no panic.
[homotopy_io_export (1).zip](https://github.com/homotopy-io/homotopy-rs/files/9353059/homotopy_io_export.1.zip)

**Comment by calintat** [comment]
This is a biasing problem. If you drag while holding shift (which forces bias = 0), it works.

**Comment by calintat** [comment]
I think the correct behaviour would be to introduce a braid, but I am not sure why that doesn't happen.
