### ISSUE TITLE
Oriented/invertible indicators not working

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#687]
@thud after your last commit 05701e8493caabc78fbc08480c5ed02cc9ce8590 the indicators for oriented (O) and invertible (I) are gone. I'm guessing this wasn't deliberate.

**Comment by thud** [comment]
Hmm, weird. Not sure how I managed that.

Simple fix...

**Comment by calintat** [comment]
Nice thanks! What was it?

**Comment by thud** [comment]
Just some rogue styles. Must have edited the wrong class at some point when prototyping (oof, should have properly checked the diffs).
