### ISSUE TITLE
Expansion/typechecking bug

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#69]
Holy heck ... in this workspace, drag the vertex to the right:

[filename_todo (35).zip](https://github.com/homotopy-io/homotopy-rs/files/6407531/filename_todo.35.zip)

The result shows a yellow strand. But *there is no yellow strand* in the signature.

My guess is that the result of the expansion is not being typechecked correctly.

**Comment by jamievicary** [comment]
Another possibility is that this is being incorrectly passed as valid by the typechecker.

Actually, this expansion isn't geometrically meaningless. It's something that in an alternative plausible theory, we might actually want to see. It's a setting where vertices can become "smeared out" along wires. But we don't want it in homotopy.io.

**Comment by zrho** [comment]
I also think this is not a bug in the type checker per se, but that we need to perform some additional checks to rule this out. If you look at what type checking does, it extracts the minimal environment around the yellow thing and then normalises it away, which is perfectly reasonable since the rewrites in the middle are identities. I'll think about what additional checks to perform and how to do them efficiently.

**Comment by jamievicary** [comment]
Ok. I think the check is precisely that completely regular slice n-diagrams
should contain generators of dimension at most n.

Of course the question as to precisely what is the most efficient way to
make this check is perhaps a nontrivial one, it will be interesting to hear
what you think about that.

**Comment by jamievicary** [comment]
Thanks Lukas! What approach did you take here?

**Comment by zrho** [comment]
I built a function that traverses the diagram and checks the dimensions of
generators, starting with a maximum allowed dimension of 0 and increasing
that by 1 every singular slice. This would be extremely slow on it's own
but by caching the results it's fast since there's a lot of duplicate
slices.

**Comment by jamievicary** [comment]
Ok thanks. That sounds a bit different to what I had in mind, can you explain the difference, or maybe give some examples to illustrate the idea here? Looking forward to discussing.
