### ISSUE TITLE
Pressing settings for a generator clears the workspace

### ISSUE THREAD

**Issue by thud** [homotopy-io/homotopy-rs#692]
This is due to the click handler of the generator including clicks which are in the settings/dimension box.

**Comment by thud** [comment]
This was introduced in d9d02b4aefd5b73c4dff3e763050e88067220c41

**Comment by calintat** [comment]
Oops, sorry about that!

**Comment by thud** [comment]
Fixed now and automerging.

**Comment by thud** [comment]
Oops, this only fixes the settings cog. Another PR inbound.
