### ISSUE TITLE
Homotopies with one input and output are rendered as identites

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#696]
Homotopies with one input and one output should be rendered as a vertex. These should be easy to detect since we just need to distinguish them from identities. Calin I remember we discussed this recently, could you take a look at it?

**Comment by calintat** [comment]
Yes I've been meaning to do this. I have figured out the correct way to do this once and for all:

1. Check if the front layer is a homotopy by checking the codimension of the maximum-dimensional generator.
2. If it's not a homotopy, it's an algebraic point so we always render the vertex.
3. If it is a homotopy, we render the vertex unless it's an identity.

I have already done 1 and 2, I only need to implement 3.

This should work in every case:
- braidings will be not rendered as if you restrict to the front layer, they are the same as an identities.
- any non-identity homotopies will be rendered, including units, counits, cups, caps, spiders, etc.

In the labelled brach, we might want to add a special case for orientation 0 generators such as cups and caps.

**Comment by calintat** [comment]
Also related to #599

**Comment by calintat** [comment]
Restricting to the front layer also ensures that braidings with a bead on top are rendered correctly:

![homotopy_io_export](https://user-images.githubusercontent.com/16837293/185240224-5f60ba41-0657-496e-9691-bad9d3259261.svg)

**Comment by jamievicary** [comment]
Hi Calin, I'm confused, why won't this put a vertex on a braiding?

**Comment by calintat** [comment]
Because if you restrict to the front layer, it has one strand going in and one strand going out and both are locally identities. So it will be treated as if it's an identity, i.e. no vertex.

**Comment by jamievicary** [comment]
I guess I don't understand how you can determine that the incoming strands are both "locally identities".

**Comment by calintat** [comment]
You look at the cone at the given depth and check if it's trivial.

**Comment by jamievicary** [comment]
But it won't be trivial, surely? Because it has source width 2. Maybe I'm misunderstanding, anyway if it's clear to you how to proceed that's the main thing, you can tell me what I'm getting wrong next time we meet.

**Comment by calintat** [comment]
Fixed by 9e1c4e1e21cec9875e3255f5da7bf00c8101f19c
