### ISSUE TITLE
We should have no-select on appropriate parts of the interface

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#697]
I think basically everything should be no-select except from the generator names, and the metadata in the project drawer.

Here is an image showing you can currently accidentally select parts of the interface.

![homotopy io - Google Chrome 17_08_2022 21_40_07](https://user-images.githubusercontent.com/10602270/185240826-d6a74b61-dafd-4275-942a-ed98141fa2a4.png)

**Comment by H-Yulong** [comment]
Fixed with pull request #704
