### ISSUE TITLE
Broken wires across a braiding

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#698]
I think in this case the yellow wire should be continuous.

![homotopy io - Google Chrome 17_08_2022 22_07_20](https://user-images.githubusercontent.com/10602270/185243775-1872270b-ab29-4b3c-9261-e60cb5c94418.png)

[homotopy_io_export (1).zip](https://github.com/homotopy-io/homotopy-rs/files/9366097/homotopy_io_export.1.zip)

**Comment by calintat** [comment]
Interesting, I'm not sure the yellow strand should be continuous as it clearly changes depth. However, I think after we fix #696, that will add vertices to the two braids which will look better.

**Comment by calintat** [comment]
I understand what's going on here. The dashed red wire is actually on top of the yellow strand but in the middle, we see the yellow strand as yellow is a higher dimension than red. I think the correct thing to do for wires is to pick the generator in the front layer (same as for vertices).

**Comment by jamievicary** [comment]
I see. Yes I agree we definitely don't want to promote hidden vertices to the front usually. However we have always allowed hidden wires to be promoted so it worries me a bit changing this. But things can't remain as they are it looks silly. So yes can we please try your idea and see what it looks like.

**Comment by calintat** [comment]
Funnily enough I contemplated doing this a while ago (when I did the same for vertices) as it felt right, but I couldn't find an example where it made a difference.

**Comment by calintat** [comment]
Fixed by 08e6f77f454cc5398f1ca3d9d9a80ad037582932.

Now it looks like this:
![homotopy_io_export(4)](https://user-images.githubusercontent.com/16837293/185247837-2f5cf3a7-f14d-499c-a4f8-623da46b06ff.svg)

**Comment by calintat** [comment]
Furthermore, I also tested this on master and it doesn't change anything as far as I can tell. I think this behaviour was only possible with invertible generators.

**Comment by jamievicary** [comment]
Thanks but I'm still confused. Look at the slices of the diagram. Why should the yellow wire be hidden in the middle, but not at the bottom?

**Comment by calintat** [comment]
At the bottom, the yellow bead is not occluded by anything:
![homotopy_io_export(5)](https://user-images.githubusercontent.com/16837293/185253620-4f621d89-f18e-45a7-a0fd-89a4c72bec79.svg)

In the middle, it's occluded by the cap:
![homotopy_io_export(6)](https://user-images.githubusercontent.com/16837293/185253667-e4910173-1d19-4a07-b4c7-cb1f7deffc7d.svg)

At the top, again it's not occluded by anything as it only has identities in front of it:
![homotopy_io_export(7)](https://user-images.githubusercontent.com/16837293/185253692-3282d837-3d4e-47ca-939e-0bf98beb2e07.svg)

**Comment by jamievicary** [comment]
I see. It does not make geometrical sense that it can be occluded by the cap and not by the wire. However this current setup does look nice in projection I agree. So I'm happy to stick with this arrangement.

**Comment by calintat** [comment]
I agree it's a bit weird. It makes more sense if you add a vertex to the cap.
