### ISSUE TITLE
Click zone for dragging a vertex needs to be bigger

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#699]
The circular zone around a vertex where you can click and drag to trigger a homotopy needs to be bigger.

My guess is that the zone is currently the same size as a standard 2-cell vertex. I think the click zone needs to be twice this size.

**Comment by calintat** [comment]
Done. I made the click zone three times as big as that felt better to me.

**Comment by jamievicary** [comment]
Thanks nice and fat, it really speeds things up.
