### ISSUE TITLE
For invertible generator, cannot contract cup and cap to form saddle move

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#700]

**Comment by calintat** [comment]
This works for me...

**Comment by calintat** [comment]
Do you mean this move:

![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/185246752-df8faa0f-cad1-4107-b9ce-50a4c7406ce0.svg) : ![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/185246765-8b3d8dbd-68be-4d2f-815b-ce100c46e506.svg) ->  ![homotopy_io_export(3)](https://user-images.githubusercontent.com/16837293/185246794-7ce1a6cd-6123-4885-94cd-c88d22adc169.svg)

**Comment by jamievicary** [comment]
I think I am probably 1 dimension higher, i.e. the red wire is actually a scalar. I get an error "contraction ambiguous". I think you were discussing this with Nick.

**Comment by calintat** [comment]
Yes, that's the same as the 3D scalar contraction bug (#681).

**Comment by jamievicary** [comment]
Closing as a duplicate.
