### ISSUE TITLE
Layout does not minimize the width of the diagram

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#701]
![homotopy io - Google Chrome 17_08_2022 23_00_21](https://user-images.githubusercontent.com/10602270/185251109-b8514e22-96e2-4760-bd07-447f15941d73.png)
[homotopy_io_export (6).zip](https://github.com/homotopy-io/homotopy-rs/files/9366316/homotopy_io_export.6.zip)

**Comment by calintat** [comment]
This is what this looks like now, so I think it's fixed.

![homotopy_io_export](https://user-images.githubusercontent.com/16837293/205699445-66b3c925-84eb-482b-b070-399087e66022.svg)
