### ISSUE TITLE
Tool freezes when trying to save Theorem

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#705]
I created a framed invertible 1-cell, then created a snake from that, hit "Identity" to make a 3-cell, then contracted the snake, producing a 3-cell from the snake to the identity. I then pressed "Theorem" to save this, but the tool just froze and stopped working. I saved the workspace, but don't know to attach it here.

**Comment by mlharaujo** [comment]
[homotopy_io_export.zip](https://github.com/homotopy-io/homotopy-rs/files/9372779/homotopy_io_export.zip)

**Comment by calintat** [comment]
Thanks Manuel, I will look into this.

**Comment by calintat** [comment]
Fixed by #718.
