### ISSUE TITLE
Run-time error when trying to view a very big knot in 3D

### ISSUE THREAD

**Issue by H-Yulong** [homotopy-io/homotopy-rs#707]
The application panicked when I was trying to view the Goeritz knot in 3D.
[Goeritz.zip](https://github.com/homotopy-io/homotopy-rs/files/9374305/Goeritz.zip)

**Comment by calintat** [comment]
I'm hoping this will be fixed when we improve layout performance, as I am sure I was able to render your Goeritz knot a while ago when layout was faster.

**Comment by calintat** [comment]
But these knots are great for benchmarking mesh/layout, thanks!

**Comment by calintat** [comment]
Sadly we can no longer import Yulong's knot proofs as the data structures are incompatible. @H-Yulong if you feel like redoing the proofs now with invertible generators, that would be great!

**Comment by H-Yulong** [comment]
Sure I'll see what I can do!
