### ISSUE TITLE
Keybindings can select generators in folders

### ISSUE THREAD

**Issue by H-Yulong** [homotopy-io/homotopy-rs#709]
I'm not sure if this is intended, but you can select generators inside a folder with keybindings 1-9.
For example:
- create two generators, Cell 0 and Cell 1.
- create a new folder
- move Cell 1 to the new folder
- collapse the new folder view

Now you can still press 2 to select Cell 1, even if you can't see it, which is a bit confusing I think.

**Comment by calintat** [comment]
Yes, that was intended. It feels quite natural to me.
