### ISSUE TITLE
Signature sometimes appears on the right hand side

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#711]
I think this was discussed in the last meeting, but since I didn't see an issue here I'm adding it.

Sometimes after closing the signature sidebar, opening some  other sidebar and then reopening the signature sidebar, this will appear on the right hand side, where it interferes with the Project/View buttons.

**Comment by calintat** [comment]
There is an issue for this: #636

I think Jasper is fixing this.

**Comment by calintat** [comment]
Closing as duplicate.

**Comment by mlharaujo** [comment]
Sorry!
