### ISSUE TITLE
Highlight not always displayed when selecting attachment

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#712]
I created two 3d scalars, Cell1 and Cell2. Then I selected Cell 1, pressed the right arrow key to go into its source slice, clicked on it and chose to attach Cell 2. The tool crashed.
[3d_scalars.zip](https://github.com/homotopy-io/homotopy-rs/files/9380610/3d_scalars.zip)

**Comment by calintat** [comment]
This seems to be a problem with the attachment highlight. We've had another one in the past.

**Comment by calintat** [comment]
Possibly related to #59
