### ISSUE TITLE
Contraction in a singular slice issues

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#714]
I tried to contract the following diagram but the contraction was invalid:

![homotopy_io_export](https://user-images.githubusercontent.com/16837293/185619238-29567d22-efe0-4d82-bf29-e234c3f7be7c.svg)

Is that the expected behaviour? I thought it's rather surprising. 

You can do the contraction by first doing an interchange, see proof in [homotopy_io_export.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/9382184/homotopy_io_export.hom.zip)

**Comment by jamievicary** [comment]
Looks to me like it should contract.

**Comment by jamievicary** [comment]
Presumably you mean you tried to do it by a horizontal drag?

**Comment by calintat** [comment]
Yes, I tried both in the projection and inside the singular slice.

**Comment by calintat** [comment]
I think contraction in a singular slice is broken. The following contraction doesn't work anymore:
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/185621533-562f5560-4c3f-45ef-ae80-eb3cb5b51947.svg) ![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/185621536-8274a862-7ecf-416e-958e-900720560e4b.svg)

**Comment by calintat** [comment]
Most likely introduced by Nick's change which replaced composition with collapse.

**Comment by calintat** [comment]
I reverted Nick's change and that fixed the braid example, but not the cups example.

I don't think using composition is a problem anymore (it was only a problem when I wasn't storing the orientation in generators) but I still think we should aim to use collapse instead of composition. We can revisit that later.

**Comment by jamievicary** [comment]
I don't think Nick's change should be reverted. The colimits are the morally correct way to compute the singular slice contraction. Nick's code might just need debugging, can we try that instead please?

**Comment by calintat** [comment]
I don't understand the recursive case of collapse enough to be able to debug this. Nick should fix this. For now I just want something that works.

**Comment by calintat** [comment]
I figured out why the two caps don't contract. It's because the smoothing part fails to propagate. I'm not sure how we can fix it. Using an identity if the smoothing fails to propagate would fix this, but then it would break other examples.

**Comment by jamievicary** [comment]
Thanks for working this out, let's think it through carefully on Monday.

**Comment by calintat** [comment]
I had to revert to using collapse for contraction in a singular slice, as composition now only works on unlabelled rewrites (I made it so that it panics if you try to compose labelled rewrites).

**Comment by jamievicary** [comment]
Well obviously I am happy with that change!!

I didn't realize we had unlabelled rewrites as separate objects.

**Comment by calintat** [comment]
There are not separate objects, the label is an option type. That's also what we use for oriented diagrams.

**Comment by jamievicary** [comment]
I understand that makes sense.

**Comment by calintat** [comment]
There are two distinct problems discussed in this issue, so I am closing it and I have opened two new issues #722 and #723.
