### ISSUE TITLE
Composition of regular slices

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#718]
I believe rewrite composition is still broken on alpha. See #705 and #713. This is really problematic as it means the wellformedness checks may give false negatives (which could explain some of the malformed panics we've been seeing).

The issue with composition is computing the regular slices. It's proving impossible to get right, I've had three attempts at fixing it.

**Comment by jamievicary** [comment]
Let's discuss in detail on Monday I'm sure we can sort this.

**Comment by calintat** [comment]
I think I might have already sorted it. I realised now we only use composition for the wellformedness checks (which discard labels) so we can just compute the regular slices like we would in an unlabelled rewrite.

**Comment by jamievicary** [comment]
Yes certainly, you can just ignore the regular slice data for the original rewrites for this purpose.

**Comment by calintat** [comment]
Fixed by 11e0d73978a686079fb5649585d33544435b63be

**Comment by jamievicary** [comment]
Fantastic!!
