### ISSUE TITLE
Expansion/contraction bug

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#720]
Some sort of expansion/contraction bug is corrupting simple beads-on-wire diagrams.

[fixed description] Build a 2-cell scalar, with an endo 3-cell, with an endo 4-cell. Compose the 3-cell as two beads on two wires, you can attach the 4-cell without problems. Now fully interchange the 3-cells. In this configuration you cannot attach the 4-cell. The diagram has been corrupted somehow.

**Comment by calintat** [comment]
This is also the case on beta (if I understood your example correctly) so it's not a bug in the invertible version.

**Comment by calintat** [comment]
It's also the same on the JS version. And thinking about it, it's probably the correct behaviour because what if the 3-cell rewrite the bead into two beads, then it's ambiguous what the resulting diagram should be.

**Comment by jamievicary** [comment]
Sorry for not being clear, by "interchange" I mean the contraction followed by the expansion.

**Comment by calintat** [comment]
Hmm that works fine for me. I can click to attach on either bead.

**Comment by calintat** [comment]
Maybe I am still misunderstanding your example.

**Comment by jamievicary** [comment]
You can click to attach on either bead, even after fully interchanging the beads? (On alpha.)

**Comment by jamievicary** [comment]
Will be free for a quick screenshare in 5 minutes ish if you join my zoom room

**Comment by calintat** [comment]
Ok

**Comment by calintat** [comment]
Just for future reference, this is only a problem in 3D (i.e. the wire needs to be a scalar).

**Comment by jamievicary** [comment]
I fixed my description of the problem in the original post. Unfortunately when I try to upload the example workspace I get some sort of github error.

**Comment by calintat** [comment]
I ran a quick diff between the original diagram and one constructed by interchange and there is indeed a difference in the labels. The orientation numbers are fine though.

**Comment by jamievicary** [comment]
How many labels does the neighborhood of a 3d scalar have in its canonical
diagram? My guess is there should be 6 but it's not completely obvious.

**Comment by calintat** [comment]
It should be 6 yes.

**Comment by jamievicary** [comment]
Ok it would be good to see what the 6 are in the example before and after
the contraction.
