### ISSUE TITLE
Issue with collapse for contraction in singular slice

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#723]
The following contraction doesn't work anymore:

![homotopy_io_export](https://user-images.githubusercontent.com/16837293/185621533-562f5560-4c3f-45ef-ae80-eb3cb5b51947.svg) ![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/185621536-8274a862-7ecf-416e-958e-900720560e4b.svg)

I checked and this was caused by switching to collapse for contraction in a singular slice.

**Comment by calintat** [comment]
I think I fixed this. It was a problem with oriented contraction, something to do with figuring out the right codimension in which to sum up orientations.

**Comment by jamievicary** [comment]
Fantastic!
