### ISSUE TITLE
Migration bug

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#724]
The migration fails on the following workspace (taken from Jamie's LICS 2019 paper)

[homotopy.io - Sun Aug 21 2022 13_02_21 GMT+0100 (BST).json.zip](https://github.com/homotopy-io/homotopy-rs/files/9389045/homotopy.io.-.Sun.Aug.21.2022.13_02_21.GMT%2B0100.BST.json.zip)

**Comment by calintat** [comment]
It works fine if you clear the workspace diagram (which is 5D) so the issue must be there.

**Comment by H-Yulong** [comment]
Thanks for finding the bug. I got the following message from the console.
> Migration tool: cannot load file. Error: missing field `abstract`

It's a problem with parsing JSON, I'll fix it quickly.

**Comment by calintat** [comment]
Thanks Yulong!
