### ISSUE TITLE
Show single image by default

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#726]
After playing with the signature previews for a bit, I think it would be better if `single_preview` was always true by default, instead of true for 1D/2D and false for 3D and above as it's currently implemented.

Often we're working in a suspended context like a braided monoidal category so it's annoying that the 2-cells (which are really 3D) are not depicted as 2-cells by default. Defaulting to false seems more intuitive and that's also what Globular does.

@thud could you please do this?

**Comment by thud** [comment]
Of course!
So to be clear, we want single_image to be false by default (ie. source/target for all generators except 0-cells)?

**Comment by calintat** [comment]
No sorry, I want `single_image` to be true by default (i.e. single preview for all generators).

I updated the description.

**Comment by thud** [comment]
Great, ok. Should be quick.

**Comment by calintat** [comment]
Thanks Jasper!
