### ISSUE TITLE
Signature previews alignment in 0D/1D

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#732]
Sorry for being incredibly pedantic, but I've noticed that the 0D/1D previews in the signature take up ever so slightly less horizontal space than the 2D previews, so things are not aligned correctly (such as the invertible/oriented indicators).

<img width="390" alt="Screenshot 2022-08-22 at 13 12 19" src="https://user-images.githubusercontent.com/16837293/185918760-9404bc91-ac20-40bc-a672-64568444a341.png">

I believe the signature previews should be made to fit inside a square box of a fixed size irregardless of the dimension, similar to the boundary previews that Yulong did.

**Comment by thud** [comment]
Think that should do it (issue with max-width vs width).
