### ISSUE TITLE
3-diagram does not contract

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#735]
This 3-diagram should definitely be contractible, but it does not contract.

![homotopy io - Google Chrome 22_08_2022 18_41_43](https://user-images.githubusercontent.com/10602270/185985195-55fe17d3-5bb1-4eca-8274-fbd10e80f0a2.png)

[homotopy_io_export (10).zip](https://github.com/homotopy-io/homotopy-rs/files/9396461/homotopy_io_export.10.zip)

**Comment by calintat** [comment]
This is another problem with contraction in a singular slice by collapse.

**Comment by calintat** [comment]
Sorry wrong issue.

**Comment by NickHu** [comment]
Probable instance of #751

**Comment by calintat** [comment]
I'm not sure yet if this is related to #751 because it's not a contraction in a singular slice, it's a top level contraction.

**Comment by NickHu** [comment]
I can't import this anymore, will investigate

**Comment by calintat** [comment]
> I can't import this anymore, will investigate

It's because this was built in an old version without side flanges.

**Comment by NickHu** [comment]
Fixed in 6b7eadc5321a71234b103a473fd63bc886ba11a1

**Comment by calintat** [comment]
> Now the contraction works, but the expansion fails

I think that's fine, at least that's the same behaviour as beta.

**Comment by jamievicary** [comment]
Does beta have expansion bugs??

**Comment by calintat** [comment]
I don't think this is a bug, this would only work with antipushout but that needs more work to handle complicated examples like this.

**Comment by NickHu** [comment]
I mean that this expansion fails (which is not the case on beta):
![image](https://user-images.githubusercontent.com/450276/188203328-ea6964df-886e-457d-9ab3-75677e716b3d.png)

**Comment by calintat** [comment]
Right, that's probably similar to unbraiding a scalar and a wire.

**Comment by calintat** [comment]
Since this bug was originally an issue with contraction, I say we close it and make a new issue for these expansion failed to propagate issues.

**Comment by jamievicary** [comment]
Have you verified that the new contraction code is producing appropriate neighbourhoods, eg for the key case of contacting a scalar in front of a wire?

**Comment by calintat** [comment]
> I mean that this expansion fails (which is not the case on beta):
> ![image](https://user-images.githubusercontent.com/450276/188203328-ea6964df-886e-457d-9ab3-75677e716b3d.png)

This is now fixed.

**Comment by calintat** [comment]
The contraction also works. You can't "anticontract" it but that's the same behaviour as beta, so I am closing this.
