### ISSUE TITLE
Cannot braid complex diagrams

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#736]
Possibly related to #735, the following contraction doesn't work:
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/185986098-7946a831-6b24-4032-9ae9-f98b51aa2135.svg) ![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/185986105-392a3673-197f-437f-a6aa-96648ebd21a4.svg)

**Comment by calintat** [comment]
This is another problem with contraction in a singular slice by collapse.

**Comment by calintat** [comment]
An even simpler example:

![homotopy_io_export](https://user-images.githubusercontent.com/16837293/186143065-c0aca4a5-77d7-431b-aede-88034bd26479.svg)

**Comment by NickHu** [comment]
Probable instance of #751

**Comment by calintat** [comment]
> Probable instance of #751 

Well this is why we came up with #751 so I'd say it's more than probable haha.

**Comment by NickHu** [comment]
Fixed by c8ed52f1674256f968413c3be78e92b0de44c91a
