### ISSUE TITLE
Interchange produces malformed diagram

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#744]
Do an interchange move on a braid next to a bead:
![homotopy_io_export(9)](https://user-images.githubusercontent.com/16837293/186518121-f1e3d8d6-4151-4235-92f8-69b7e40e06e8.svg)

If you do it by dragging the braid, it panics. Weirdly it works fine if you drag the bead.

**Comment by NickHu** [comment]
Fixed in 6b7eadc5321a71234b103a473fd63bc886ba11a1

**Comment by calintat** [comment]
@NickHu what is the status of this? It seems to be unrelated to the other expansion bugs.

**Comment by calintat** [comment]
Ignore what I just said, this seems to be the cause of all our remaining bugs now.

**Comment by jamievicary** [comment]
Yes we have a remaining expansion bug. Nick and I have discussed this and we think we are quite sure where the bug is, it is in the complex index shuffling that has to be done when constructing the expansion rewrite. We will definitely fix this early next week.
