### ISSUE TITLE
Collapse base case needs to consider reachability components

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#751]
In the base case of collapse:
* from the input, compute (reverse) reachability components for each sink;
* for each component, group the vertices into equivalence classes:
  * find the equivalence class that contains the sink (unique highest dimensional generator w.r.t. this component) by extending along identities;
  * for each vertex in the component, find the set of shortest paths into the sink equivalence class;
    * verify that each of these sets contains at most one non-identity rewrite label, and this label is the same for all paths;
  * for each edge, check if it is collapsible. Collapsible when:
    * identity edge (as currently); and
    * all participating triangles agree label-wise (as currently); and
    * unique label in shortest path to sink agrees.
  * collapsibility builds equivalence classes of vertices for each component.
* different reachability components will have common vertices: take the union of all the equivalence classes, yielding an equivalence relation on the set of input vertices;
* overall, we need to ensure that there is a unique maximal dimension generator also, and force them to occupy the same equivalence class (as currently), and that no label inconsistencies have resulted (as before, but add a new check).

We get these equivalence classes instead of what we were computing previously:
![image](https://user-images.githubusercontent.com/450276/186901569-6ab538b0-fc7f-4925-817b-b7b681a6e020.png)
![image](https://user-images.githubusercontent.com/450276/186901654-385fa60d-93e9-4839-aa1c-ab3ea9af0caa.png)

**Comment by jamievicary** [comment]
This has arisen from an extensive discussion between Calin, Nick and myself today. The examples that break the old collapse algorithm are the "T-shaped" collapse diagrams arising from contraction in a singular slice. The first time this actually arises in the tool is when we try to braid a 3d scalar horizontally in front of a scalar wire.

**Comment by NickHu** [comment]
I added a commit that implements this behaviour as written down: aee140121a774aeeefcdcfb9bee9571af1cd617a

Unfortunately, it doesn't seem to have fixed the contraction of a 3D scalar horizontally in front of a wire. Perhaps I made a mistake somewhere; will look over it again with fresh eyes tomorrow.

There was a bit of ambiguity in the description above:
> find the equivalence class that contains the sink (unique highest dimensional generator w.r.t. this component) by extending along identities;

I've implemented this by extending along all identities, but could it be the case that this is only valid for identities which are identified as collapsible?

**Comment by jamievicary** [comment]
Thanks Nick for implementing this idea so quickly!

I think it shouldn't matter how you resolve that ambiguity. That is, all
identities on the sink element should be collapsible.

When you say it doesn't seem to have fixed that 3d scalar example can you
be more specific? It would be highly unlikely we are encountering exactly
the same error. Have you thoroughly tested it with other ordinary
contraction scenarios?

Can you please do the code review meeting with Calin that we had discussed.

**Comment by calintat** [comment]
I am closing this as we have moved away from this idea.
