### ISSUE TITLE
Make Diagram deserializable

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#757]
Right now, the train Deserialize is not implemented for Diagrams. This is preventing automatic derivation of the trait for AttachOption, which in turn is preventing us from replaying some labelled-related actions in the CLI. This should be fixed.

**Comment by calintat** [comment]
Nick wrote implementations of Deserialize for Diagram and Rewrite in #755. Unfortunately that will break on labelled because we need Label to implement Deserialize (and moreover the type of Label changes a few times in the commit history).

**Comment by doctorn** [comment]
`obake` 👀👀👀

**Comment by regular-citizen** [comment]
We discussed with Calin a way to add optional action dumps in .hom, with no stability guarantees.
I will obake the relevant data structures in homotopy-core to support backwards compatibility between beta and alpha as well, but only after the labelled data structures are confirmed as stable.
