### ISSUE TITLE
Manim output does not support OpenGL rendering

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#762]
Manim is moving away from its Cairo renderer to using OpenGL. Some minor tweaks are needed for the Manim output for it to work properly in OpenGL mode (`manim --renderer=opengl`):

* [x] #766
* [x] #767
  `add_cubic_bezier_curve_to` has returns unit and not an `OpenGLVMobject`. So It needs to do something like:
  ```python
  wire = OpenGLVMobject()
  wire.start_new_path(...)
  wire.add_line_to(...)
  wire.add_cubic_bezier_curve_to(...)
  ...
  ```

**Comment by regular-citizen** [comment]
@NickHu, just to be sure, can you confirm that this is an API change in the community version of manim?

**Comment by NickHu** [comment]
Yes:

https://github.com/ManimCommunity/manim/blob/cef3565858bcec029bbe8aa553662ade51d924eb/manim/mobject/opengl/opengl_vectorized_mobject.py#L435-L449

Although it's not clear to me if this is an intentional change or a bug.

**Comment by regular-citizen** [comment]
Okok thanks for confirming.

I was thinking that actually, we may render everything as Bezier cubics (even lines with collinear controls), then just put the coordinates in a list and iterate over it to construct the path. It may make the code cleaner.

**Comment by regular-citizen** [comment]
@NickHu I re-designed the manim code export to be compatible with the plethora of breaking changes they introduced in their OpenGL APi, but unfortunately it seems that their OpenGLVMobject do not support the Intersection operation, which we need for masking. While there may be other strategies for masking, they're probably very fiddly.

I propose we return to the cairo rendered export, but leave the code structured in ways to make the move to OpenGL easier in the future, when their API is a bit more mature and stable.

**Comment by calintat** [comment]
Since you put in the effort to switch to new API, we could keep it as an option. Maybe we could have a toggle in the export panel for choosing between Cairo and OpenGL (with an asterisk that OpenGL doesn't support braidings).

**Comment by regular-citizen** [comment]
Sounds good, I'll implement it as part of #765.

@H-Yulong, could I request your help in making a checkbox in "Image export" under "Manim" with text "OpenGL renderer", default false, and expose its value in a way I can reach it from the call site of the manim::render?

**Comment by regular-citizen** [comment]
Implemented fallback renderer, but it turns out they broke both APIs, no manim braidings basically never work (until we figure out an alternative strategy for it).

**Comment by H-Yulong** [comment]
@regular-citizen I didn't follow this thread so not sure what's going on -- anyways, do you still want that checkbox for manim export?

**Comment by regular-citizen** [comment]
Yes, sorry for closing the issue, it's still needed. The merged code now has a flag "use_opengl", which should be set to the value of the checkbox.

**Comment by calintat** [comment]
Let's keep track of these options in #525.
