### ISSUE TITLE
Clicking away from "Image Export Panel" does not close it.

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#770]
There is a divergence of behaviour between the project/etc... tabs and the image export tab with regards to "clicking on other panels will close the current one".
We should fix this by making the image export panel close when one clicks on other ones.

Steps to reproduce:
- Select a 2-cell to make it appear in the workspace (just to enable image export),
- Click on project tab,
- Click on image export tab (this swaps the project tab with the image export tab)
- Click on project tab (this does nothing).

**Comment by H-Yulong** [comment]
Yes, currently it interacts with project/etc. tabs inconsistently. Will fix it along with moving the "Image export" button to the `sidebar__nav` part.

**Comment by regular-citizen** [comment]
Thanks!
