### ISSUE TITLE
Building previews in debug mode (proposal)

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#777]
Right now, "nix build" will automatically produce release builds. Not only is this undesirable from the point of view of compilation speed, it also means that previews will not offer debug functionalities such as the debug panel.

The reason why I'm making an issue for it now is that I am implementing an alternative panic hook for release builds which will provide information in an "issue-filing" friendly format (i.e. action dump + instructions on what to do with it). The current panic handler dumps a stacktrace to console, and it is in theory only supposed to be activated in debug builds as it bloats the deploy size significantly.
However, we definitely want stacktraces in preview builds, hence the above question: do we actually want the previews to be built as release builds?

The only argument I see against is that it would introduce a divergence between pre-merge and post-merge to master builds, which may cause some hassles. But we keep CI jobs for the release builds and prevent most such failures.

**Comment by doctorn** [comment]
Ideal situation would be to have a label you can set on the PR which toggles debug vs release builds (actions is smart enough to support this)

**Comment by regular-citizen** [comment]
I could get behind making debug builds for draft PRs and release builds for "ready to merge" ones.

**Comment by regular-citizen** [comment]
Closing under "too much work, too little need".

**Comment by calintat** [comment]
Could we revive this? I think it's a really good idea, especially given #818.

**Comment by calintat** [comment]
It's less of a priority for alpha as we're going to merge that soon, but in the future we may start other experimental branches and it would be nice to have the debug functionality in the preview.

**Comment by regular-citizen** [comment]
#846 will build everything in debug mode.
