### ISSUE TITLE
Double figure 8 crash

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#780]
I am attaching a .hom file and an action file for constructing a "double figure 8". In the 2d projected view of this 4-diagram, if I try to contract the bit below the tool crashes: 
![image](https://user-images.githubusercontent.com/36002049/187933802-7291e875-fbdd-4ce2-bc27-b2eb205a2cdb.png)

Chiara told me Nick probably already fixed this and just needs to upload the patch, but I'm leaving this here anyway just so I know when it's working.
[double8.zip](https://github.com/homotopy-io/homotopy-rs/files/9470537/double8.zip)

**Comment by calintat** [comment]
Alpha is completely broken at the moment, it should be fixed soon once Nick pushed his changes.

**Comment by NickHu** [comment]
I can't import this workspace anymore (probably due to the change in 6b7eadc5321a71234b103a473fd63bc886ba11a1), so I can't check if this works now. Would it be a huge pain to reconstruct?

**Comment by mlharaujo** [comment]
> 

No, I can do it quickly now.

**Comment by mlharaujo** [comment]
I just tried it and I can import the workspace on alpha. Maybe the change is not live yet?

**Comment by doctorn** [comment]
> I just tried it and I can import the workspace on alpha. Maybe the change is not live yet?

You might need to force refresh to clear your cache

**Comment by mlharaujo** [comment]
I did this (Ctrl + Shift + R) and I am still able to import the workspace. And I still get the crash. I will upload a new .hom file shortly.

**Comment by jamievicary** [comment]
Manuel you can check what commit version you're working with by looking at the code in the bottom right.

**Comment by mlharaujo** [comment]
Version 0.1.2. 

Now the tool crashed earlier in the construction. I'm attaching the action file and workspace.
[homotopyio.zip](https://github.com/homotopy-io/homotopy-rs/files/9479958/homotopyio.zip)

**Comment by jamievicary** [comment]
Not that, I'm referring to the hexadecimal commit reference.

**Comment by mlharaujo** [comment]
The only thing I see in the bottom right of the screen is "Version 0.1.2". How do I find the hexadecimal commit reference?

**Comment by jamievicary** [comment]
Sorry you're right I don't know why it's not there.

**Comment by calintat** [comment]
> I can't import this workspace anymore (probably due to the change in [6b7eadc](https://github.com/homotopy-io/homotopy-rs/commit/6b7eadc5321a71234b103a473fd63bc886ba11a1)), so I can't check if this works now. Would it be a huge pain to reconstruct?

This works fine for me. I don't see how that change would affect the export. Are you sure you didn't try to import it on beta?

**Comment by calintat** [comment]
This still crashes. I think it's related to #744 and the action is an interchange rather than a contraction.

**Comment by calintat** [comment]
I wonder if we can extract a smaller example from this.

**Comment by jamievicary** [comment]
Manuel if you could find a simpler scenario that illustrates the "same" bug that would be great.

**Comment by mlharaujo** [comment]
I have actually posted two different bugs in this thread. The second one is a much smaller diagram, and the bug appears in an seemingly unrelated place to the first one. 

I can also try to isolate the part of the first diagram that gives the bug.

**Comment by mlharaujo** [comment]
Here is a minimal version of the first bug (hom file and crash dump).
[minimal.zip](https://github.com/homotopy-io/homotopy-rs/files/9555002/minimal.zip)

**Comment by calintat** [comment]
Nice! This seems very similar to #798.

**Comment by NickHu** [comment]
Both the simple file and the more complicated file in the OP seem to contract OK if I remove the assertion
https://github.com/homotopy-io/homotopy-rs/blob/d28f85fd9fa157227797a1567c15a37d761ad72e/homotopy-core/src/contraction.rs#L566

This would also fix #798. It's seeming increasingly possible that this assertion is flawed...

**Comment by calintat** [comment]
Correct me if I am wrong, but it seems these check if two edges which are identified have the same label. If they have different labels, then surely we shouldn't identify them.

**Comment by calintat** [comment]
Also this seems to contradict what you just said: https://github.com/homotopy-io/homotopy-rs/issues/798#issuecomment-1243829229

Could it be that your latest commit sort of fixed that?

**Comment by NickHu** [comment]
> Also this seems to contradict what you just said: [#798 (comment)](https://github.com/homotopy-io/homotopy-rs/issues/798#issuecomment-1243829229)
> 
> Could it be that your latest commit sort of fixed that?

Yes, it does seem that way.

Also, having examined the equality check which fails (it's the first one), the values are:

```
panicked at 'assertion failed: `(left == right)`
  left: `Some(Label(None))`,
 right: `None`', homotopy-core/src/contraction.rs:453:29
```

So it's almost certainly an implementation bug rather than a conceptual throwing away of labels.

**Comment by calintat** [comment]
> When does a rewrite have `Label(None)`?

Directed identities,i.e. someting like $f^+ \to f^0$.

**Comment by calintat** [comment]
`Some(Label(None))` and `None` should be treated as the same.

I think we should change `Rewrite0::label` so that it returns an `Option<LabelNode>` instead of `Option<Label>` (which is equivalent to `Option<Option<LabelNode>>`). Does that make sense?

**Comment by NickHu** [comment]
Ok, I'll make a minimal change to fix this then and we can discuss restructuring/cleanup elsewhere.

**Comment by mlharaujo** [comment]
Cool! This has also fixed another bug I had found but not yet reported.
