### ISSUE TITLE
Crash in complex expansion scenario

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#786]
I was using contraction and expansion repeatedly in higher and higher dimensions to produce random stuff, and generated this crash.

[homotopy_io_crash_action_dump.txt](https://github.com/homotopy-io/homotopy-rs/files/9482420/homotopy_io_crash_action_dump.txt)

**Comment by jamievicary** [comment]
These moves only involved top-level contraction and expansion moves.

**Comment by jamievicary** [comment]
Here is a simplified action log that replicates the same crash: 
[homotopy_io_crash_action_dump (1).txt](https://github.com/homotopy-io/homotopy-rs/files/9482434/homotopy_io_crash_action_dump.1.txt)

**Comment by jamievicary** [comment]
Here is the workspace just before the crash, trigger the crash by dragging either vertex up or down:
[homotopy_io_export (12).zip](https://github.com/homotopy-io/homotopy-rs/files/9482436/homotopy_io_export.12.zip)

**Comment by calintat** [comment]
Based on the error, I think this is the same issue as #744 which should be fixed soon.
