### ISSUE TITLE
Suspension

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#788]
It would be useful to be able to take a signature and "suspend" it. The suspended signature would have either one or two 0-cells (this could be a user choice). Then it would have a (k+1)-cell for each k-cell in the original signature, with the obvious sources and targets. The 1-cells in the suspended signature would all have the same source and the same target.

**Comment by regular-citizen** [comment]
Closing this as duplicate of #198. I will quote your perspective on this there.
