### ISSUE TITLE
Inverses of Theorems

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#789]
When a user constructs  k-diagram all of whose k-cells are invertible and then presses Theorem, the resulting theorem cell should be automatically invertible. Moreover, there should be an additional Proof cell connecting the inverse of the Theorem cell to the inverse of the k-diagram, constructed by using the invertibility of the cells it is composed of. 

It should then be possible to construct diagrams using the Theorem cell and its inverse, as well as associated cups, caps etc and then click to expand into a diagram using only cells in the original signature (and their inverses, cups, caps etc).

**Comment by calintat** [comment]
I agree. At the moment the theorem and proof cells are made as directed cells but you can toggle them as invertible as you wish (which is wrong). Related to #590.

**Comment by mlharaujo** [comment]
Just to clarify: Proof cells should always be invertible (this is #590 ). Moreover, in certain cases (described above) Theorem cells should also be invertible, and in these cases they should come with an extra Proof cell, which allows expansion of the inverse of the Theorem cell.

**Comment by calintat** [comment]
Technically we wouldn't need that extra proof cell because you can construct it from the original proof cell (which is itself invertible and its boundaries are also invertible).

**Comment by mlharaujo** [comment]
Yes, that's a good point. It would just make things easier, if you constructed some complicated invertible diagram and then wanted to make diagrams involving that and its inverse.

**Comment by calintat** [comment]
Partially fixed by a056c497bd0147a85cf85459d3e410337ba1ded7

Now if you have a diagram $D : A \to B$ which is invertible and press "Theorem", that will create generators $T : A \to B$ and $P : T \to D$ both invertible. @mlharaujo could you explain again what else you wanted because I'm not entirely sure.

**Comment by mlharaujo** [comment]
I wanted another invertible proof cell P':T^{-1}\to D^-1, where D^{-1} is a diagram in the original signature, which is inverse to D. Basically I want to be able to construct diagrams involving T, T^{-1} and the corresponding cups, caps etc and then click to expand and get a diagram involving only generators in the original signature. This would allow for efficient "boostraping" constructions to make complicated diagrams.

**Comment by mlharaujo** [comment]
But maybe it's not so hard to just build this cell, especially now that there is an invert command (which I just noticed and I think will be extremely useful!)

**Comment by calintat** [comment]
OK, so $P'$ is equivalent to the horizontal inverse $P_\*$ of $P$ right? You should be able to construct $P_*$ in the tool with the new invert action (at least theoretically). Let me know if that's not the case.

Now if you want to use $P_\*$ to rewrite some other diagram, it's not enough to construct it in the workspace, you need to have it in the signature so you can attach it. But you could use Theorem to get $P'$ and a proof cell $P' \Rightarrow P_\*$. WDYT?

If this proves too annoying to do every time, we can think of something else.

**Comment by mlharaujo** [comment]
I will try a few examples and see how it goes.

**Comment by mlharaujo** [comment]
I tried this with the figure 8. I created the figure 8 $3$-diagram  $D$ and saved it has a Theorem $T$ with proof cell $P:T\to D$. Then I built a new cell $P':T^{-1}\to D^{-1}$. Now I built a diagram using $T$, $T^{-1}$ and the associated cups and caps, namely I built a figure 8 $4$-diagram. Now I want to expand to get everything in terms of the original signature, so I click and use the cells $P$ and $P'$. Then I get to this and now I am stuck: 
![image](https://user-images.githubusercontent.com/36002049/190478961-3fee79ae-f195-4dd8-ac4d-8a65029e2f29.png)

**Comment by mlharaujo** [comment]
[fig8_boostrap.zip](https://github.com/homotopy-io/homotopy-rs/files/9577932/fig8_boostrap.zip)

**Comment by jamievicary** [comment]
You would have to manually do the transpose at the top and bottom, and all the braidings. I don't think this helps you very much really.

**Comment by mlharaujo** [comment]
In this case it's fairly easy to just build the double figure 8 by hand, without Theorems. But for the triple figure 8 it gets harder. And in general I think this kind of logic would be a great feature that would make building complicated diagrams much easier. Maybe something to think about for the future :)

**Comment by jamievicary** [comment]
It would be great to do something more automatically but it's hard for me to see how that would work -- something to keep in mind

**Comment by calintat** [comment]
The issue in Manuel's original comment has been fixed so I think it's best to close this.
