### ISSUE TITLE
Record whether a generator is a theorem or proof

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#795]
When creating a generator, we should record what type of generator it is: cell, theorem or proof.

The main use for this is #590 so we can disable the framed/oriented and directed/invertible toggles for theorems and proofs.

Another use could be a better naming scheme for theorems and proofs. Right now, when you press 'Theorem' it adds a theorem cell called "Theorem n" and a proof cell called "Proof n + 1", and then the next generators will be called "Cell n + 2". It would be nice to have separate counters for cells and theorems/proofs, which this would enable.

**Comment by jamievicary** [comment]
I'm not sure I agree with this one. If the user goes in and starts modifying the Theorem, Proof cells that are constructed by the Theorem operation, their interpretation changes, and that's something the user will be aware of. Constraining certain cells in the way you are proposing complicates the UI and potentially confuses users. I prefer to keep things as they are.

**Comment by calintat** [comment]
Hmm maybe you're right, this might be unnecessarily restrictive.

If we make the proof cell invertible, you won't be able to then make it directed anyway so that's fine.

**Comment by calintat** [comment]
For theorem cells, maybe it's fine to allow users to make a theorem cell invertible. You could interpret the inverse as an algebraic generator.

**Comment by calintat** [comment]
I am closing this as we agreed it's not really necessary and potentially too restrictive.
