### ISSUE TITLE
Attachment and Rewriting

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#8]
- [X] Highlights for embedded 2D subdiagrams.
- [x] Highlights for embedded 1D subdiagrams.
- [x] Find attachment points when the user clicks on the diagram.
- [x] Display attachment options in the UI.
- [x] Cancel attachment through a button.
- [x] Cancel attachment through the Esc key.
- [x] Cancel attachment when the workspace is updated.
- [x] Attach cells to a diagram.
- [ ] Update the current path appropriately.
- [x] Attachment of scalars.

**Comment by NickHu** [comment]
Cancelling attachment should be easy @doctorn if you'd like to take this on

**Comment by doctorn** [comment]
Yeah this issue has actually really annoyed me when trying to use the tool

**Comment by jamievicary** [comment]
I don't see any need for a button, surely the "undo" facility is a perfectly natural way to achieve that. The problem is that undo doesn't actually work if you're attaching I think.

**Comment by NickHu** [comment]
By 'button', I suppose we mean an X in the attachment window. It's absolutely crucial for touch-only devices.

**Comment by NickHu** [comment]
I'm not convinced undo is related to this. Opening the attachment window doesn't represent any modification of the proof state, so that's why it doesn't work like that. It's really a UI thing

**Comment by jamievicary** [comment]
OK sounds reasonable.

**Comment by jamievicary** [comment]
All I'm saying is that, when you're in the attachment window, pressing undo
should take you back out of it. At the moment nothing happens.

**Comment by jamievicary** [comment]
Ah I see I was wrong there, pressing undo enough times does work. The
problem is that when you're in the attachment interface, mousing over the
different attachment options adds loads of states to the undo stack. This
should not happen.

**Comment by calintat** [comment]
Update the current path appropriately tracked in #30.
