### ISSUE TITLE
Should a generator on homotopies be invertible?

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#800]
We decided a while ago that if a generator has an invertible cell in its boundary, then the generator itself should be invertible (#673). This was to prevent users from constructing the transpose of a 2-cell when the 2-cell is not invertible:

![homotopy_io_export](https://user-images.githubusercontent.com/16837293/189640238-85d63135-d2b0-409a-9174-495849506cb4.svg)

However you can construct a generator whose boundaries are homotopies (which are like invertible generators).

For example, you can have an endomorphism 4-cell on a braid:

![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/189634170-52dd9945-e0e3-4dd1-aa07-86eca20e7765.svg) : ![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/189634518-24868b8a-e254-4a38-91cb-4148e0eb9caa.svg) $\rightarrow$ ![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/189634518-24868b8a-e254-4a38-91cb-4148e0eb9caa.svg)

This generator is not marked as invertible but I think maybe it should be because its source/target are essentially invertible (even though they don't contain any invertible generators, this is related to #799).

Technically there is nothing preventing the user from constructing the transpose of this generator, though I admit I tried to do it but couldn't get very far (mostly because of a bug in collapse I found).

@jamievicary WDYT?

**Comment by jamievicary** [comment]
Hmmf, yes this is a bit annoying. What we should really do is just implement directed type checking and avoid all these issues.

**Comment by calintat** [comment]
So I wrote a function which checks if a diagram is invertible (such that homotopies are also considered invertible).

With that, we could automatically make this generator invertible, but I realised that would also mean all scalars are invertible (because identities are invertible). We could make an exception for invertible diagrams which are identities but that feels rather ad hoc.

I don't think we can solve this in a nice way without directed type checking.

**Comment by jamievicary** [comment]
That's cool, for now we could just use this to implement a function that inverts the current diagram.

**Comment by calintat** [comment]
Yes. Also to make theorem cells invertible if the corresponding diagram is invertible.

**Comment by jamievicary** [comment]
Yes fair enough

**Comment by calintat** [comment]
Fixed by 8ebb24adb4220ea424399acb04c2e45e131773e9

Now when adding a generator, we check if either boundary is an invertible non-identity diagram, and if so, we automatically make the generator invertible. That should handle all examples correctly.

In the future, when we have directed typechecking, we may consider removing that.
