### ISSUE TITLE
Crash contracting cup and inverse

### ISSUE THREAD

**Issue by doctorn** [homotopy-io/homotopy-rs#801]
[Crash dump](https://github.com/homotopy-io/homotopy-rs/files/9549369/homotopy_io_crash_action_dump.txt)

**Comment by calintat** [comment]
Can you add a screenshot or hom file? We can't import action dumps in the website.

**Comment by NickHu** [comment]
![image](https://user-images.githubusercontent.com/450276/189696509-c709a5ce-6c44-488d-abe9-31bd177b6b22.png)

`panicked at 'node in collapse base does not connect to max_dim_index', homotopy-core/src/contraction.rs:677:30`

**Comment by jamievicary** [comment]
I am very pleased if this is broken because it is a nice simple example.

**Comment by regular-citizen** [comment]
> Can you add a screenshot or hom file? We can't import action dumps in the website.

Yes we can. It doesn't show .txt as a supported format for some reason, but it can load up actions files and replay them just fine.

**Comment by calintat** [comment]
> > Can you add a screenshot or hom file? We can't import action dumps in the website.
> 
> 
> 
> Yes we can. It doesn't show .txt as a supported format for some reason, but it can load up actions files and replay them just fine.
> 
> 
> 
> Correction: we actually cannot import them because AttachOption has a fake deseralize.

See this to add .txt as a supported format: https://github.com/homotopy-io/homotopy-rs/blob/e375617791f0175bc9751dd8924a6bc2d009c042/homotopy-web/src/app/project.rs#L33

**Comment by calintat** [comment]
> > > Can you add a screenshot or hom file? We can't import action dumps in the website.
> > 
> > 
> > 
> > Yes we can. It doesn't show .txt as a supported format for some reason, but it can load up actions files and replay them just fine.
> > 
> > 
> > 
> > Correction: we actually cannot import them because AttachOption has a fake deseralize.
> 
> See this to add .txt as a supported format: https://github.com/homotopy-io/homotopy-rs/blob/e375617791f0175bc9751dd8924a6bc2d009c042/homotopy-web/src/app/project.rs#L33

Sorry that's pointing to an old version because I copied it from an old PR.

**Comment by regular-citizen** [comment]
With 1b24a43, we can import this action file into homotopy-cli and homotopy-web.

**Comment by doctorn** [comment]
You can't even *construct* this diagram now to contract it, let alone trigger the contraction bug.

**Comment by NickHu** [comment]
Is it possible you tried before the CI updated alpha.homotopy.io?

**Comment by calintat** [comment]
I just tried this and it's definitely fixed.

**Comment by doctorn** [comment]
Ok my bad 😅
