### ISSUE TITLE
Simple contraction crash

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#812]
I was attempting to recreate the "trace contraction to scalar" example in #616 (in alpha), and contraction crashed. Logs:
[homotopy_io_crash_action_dump.txt](https://github.com/homotopy-io/homotopy-rs/files/9568012/homotopy_io_crash_action_dump.txt)

Diagram screenshot:
![image](https://user-images.githubusercontent.com/7887982/190205989-b3343c75-5037-4e39-9c2a-fb297171d520.png)
Vertical contraction works, horizontal fails.
It also crashes if we make the 1-cell oriented.

I made sure to do an uncached reload of alpha when debugging so this is a fresh crash.

**Comment by calintat** [comment]
What do you mean by horizontal contraction? As in contracting an endomorphism with an identity horizontally?

**Comment by regular-citizen** [comment]
Precisely

**Comment by calintat** [comment]
Just to clarify, this fails with everything framed right? And by fail I mean panic.

**Comment by regular-citizen** [comment]
Yes. Here are the logs without the last action.
[homotopy_io_crash_action_dump.txt](https://github.com/homotopy-io/homotopy-rs/files/9568093/homotopy_io_crash_action_dump.txt)

The panic is contraction.rs:681.

**Comment by jamievicary** [comment]
This does not even need invertibility, here is a simplified example. Drag horizontally to produce the crash. Note this is not a contractible situation.

**Comment by jamievicary** [comment]
[homotopy_io_export (15).zip](https://github.com/homotopy-io/homotopy-rs/files/9568108/homotopy_io_export.15.zip)

**Comment by calintat** [comment]
Hmm, that seems to be the same error as the circle which Nick just fixed.

**Comment by jamievicary** [comment]
Well the circle was contractible, but this is not contractible, so the situation is fundamentally different.

**Comment by jamievicary** [comment]
Nick in the collapse code, after we have done all the possible collapses, there should be a check that every equivalence class has a direct edge to the max dimensional generator. If this is not the case then the scenario should be declared noncontractible. Is this check being done?

**Comment by calintat** [comment]
We do check that but we panic if it doesn't pass. That should be an easy fix.

**Comment by jamievicary** [comment]
OK that should catch this then.

**Comment by NickHu** [comment]
Fixed by 4b63a647094a39a813d4c068b643cefee5876876
