### ISSUE TITLE
When importing action history, it would be good to have an option not to import the last action

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#813]

**Comment by calintat** [comment]
Even better import everything up to but not including the first action that fails.

**Comment by regular-citizen** [comment]
Should this actually be done all the time? I think we mostly use the action import just for debugging and never running the last action would save us a checkbox.

**Comment by regular-citizen** [comment]
> Even better import everything up to but not including the first action that fails.

I believe this is already the case. The problem is when the "fail" is a panic.

**Comment by calintat** [comment]
That's what I meant by fail sorry.

**Comment by calintat** [comment]
The point is we should have a "safe" import which imports everything before the panic.

**Comment by jamievicary** [comment]
Well it is attractive to have the whole action history including the crash for automated checking

**Comment by calintat** [comment]
Maybe we could have a separate button for importing actions in the debug panel with an option for "safe imports"

**Comment by regular-citizen** [comment]
The quickest fix I see is to:
- Always dump the complete action sequence on panics,
- Have the CLI and test code always run the full action sequence,
- Have the UI only run up to but not including the last action.

Doing this is literally a one-line change in homotopy-web/src/model.rs.

**Comment by jamievicary** [comment]
Sounds good to me.

**Comment by calintat** [comment]
That sounds good to me.

**Comment by calintat** [comment]
Sorry but I'm not happy with this. If the last action doesn't crash, we shouldn't just discard it. This makes it very confusing if you just want to import a list of actions to reconstruct an example.

**Comment by calintat** [comment]
Since the only place where we can get a list of actions that crashes is the panic handler, we could change that so that the last action (i.e. the one that crashes) has a special tag which indicates that it crashes.

Or alternatively, we could split the last action from the list, so instead of returning a list of actions, we could return a pair consisting of a list of actions plus the "bad action".

In the UI, we should ignore the bad action since there is no point importing it but in the CLI we could still import it.

**Comment by calintat** [comment]
> I'll implement when I'm back. Something nice we would get out of this as a side effect is that we could make homotopy-cli handle the last action with a proof.update of its own. This would allow us to only place breakpoints at the last action.

That sounds very useful!

**Comment by calintat** [comment]
@regular-citizen just a heads up I reverted your commit because it was really annoying not being able to import the last action.

**Comment by regular-citizen** [comment]
Following #831, we should also be able to bake the initial proof state into the action dump. I will do this as a fix to this issue.

**Comment by calintat** [comment]
Thanks Chiara!

**Comment by calintat** [comment]
> Following #831, we should also be able to bake the initial proof state into the action dump. I will do this when I'll fix this issue.

I just realised this would also be achieved if we included the ImportProof(data) to the action dump. That would involve moving the ImportProof action to homotopy-model which maybe isn't the worst idea?

**Comment by regular-citizen** [comment]
Yeah  I could get behind this, it really is a proof action, and it would improve determinism/reproducibility quite a lot.

**Comment by calintat** [comment]
Yes, really the only actions that aren't proof actions are the export actions.
