### ISSUE TITLE
Merge alpha into master

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#817]
Surely this is a good time to merge alpha into master? We need to do it at some point, and the sooner the better.

**Comment by calintat** [comment]
Yes please!

**Comment by NickHu** [comment]
We should do a cleanup first, including making all the tests work again.

**Comment by calintat** [comment]
Yeah I need to clean up something about labels.

**Comment by calintat** [comment]
Now that we have typechecking, I see no reason to delay doing this. @NickHu @jamievicary do we agree?

**Comment by jamievicary** [comment]
Yes please!

**Comment by NickHu** [comment]
I don't think we should yet. We haven't stabilised the label type, and want to change it currently for example. We don't know that type checking works, and we don't know what theory alpha implements. Every week we find new bugs and new reasons to change fundamental things. Plus, now that no one is working on beta, all the benefits of merging alpha have evaporated; we wouldn't need to do any rebasing anyway.

**Comment by calintat** [comment]
I disagree with your point about typechecking. It is a conceptually very simple and well motivated, and we have seen strong evidence that it works since it rejects invalid contractions such as the #828 and #875.

**Comment by calintat** [comment]
It's fine if we're going to make breaking changes in the near future. I mean it makes no difference if we merge those into labelled and then master or if we merge them into master directly, the end result is we still won't have backwards compatibility. If anything, it's better to kill the directed version now to prevent people from using it.

**Comment by calintat** [comment]
Sorry for the word vomit, I just feel strongly we should do this now.
