### ISSUE TITLE
Reidemeister 1 crashes

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#820]
Try to contract a twist:
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/190271275-787cc720-8054-414d-95d9-09b260f5876e.svg)

This should be an invalid contraction but it crashes with "label inconsistency".

**Comment by calintat** [comment]
Interestingly, contracting this doesn't crash:

![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/190271566-b70d4322-af19-4354-8012-f0470e69fdba.svg)

**Comment by NickHu** [comment]
Fixed by 1bdf7cea5e785cf635a0058dfb736a8f5a3c3d2e
