### ISSUE TITLE
Braiding a wire and a cap

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#821]
Start with a wire next to a cap in 3D:
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/190273232-2e33e2e3-b84f-43b1-a994-d1fcb68f53f8.svg)

If we try to braid the wire on top of the cap, we get a weak unit:
![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/190273325-b012c930-ab4f-450c-b499-987f7ccf8a6d.svg)

Conversely, if we try to braid the cap on top of the wire, we get an illtyped diagram:
![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/190273387-0f8fc356-4913-47ac-b817-1f1c49338e24.svg)

In both cases, the expansion propagation did a bubbling which means the factorization failed (and it shouldn't).

**Comment by calintat** [comment]
Interestingly, this works fine if we replace the cap with an algebraic cap:
![homotopy_io_export(3)](https://user-images.githubusercontent.com/16837293/190273587-52e595fd-61cf-4d6f-ab88-f27382498364.svg)

**Comment by calintat** [comment]
This was working fine before changes to contraction and given that it works fine for the algebraic cap, I don't think it's a problem with factorization. It could be that the output of contraction has some wrong neighbourhoods.

**Comment by NickHu** [comment]
Possible factorization bug

**Comment by NickHu** [comment]
It seems like the current issue is that contraction propagation fails, in particular where it tries to construct a composite by collapse

**Comment by NickHu** [comment]
Fixed by fb4cc71392c413309ec4ad109ac3ed34ac817c20
