### ISSUE TITLE
Contraction crashes with malformed rewrite

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#823]
Start with a wire next to a half-braid:

![homotopy_io_export(4)](https://user-images.githubusercontent.com/16837293/190275955-df38e571-a73e-4e17-9ad7-aaaedaa3daf8.svg)

Now braid the wire over the braid. This results in a malformed rewrite.

**Comment by NickHu** [comment]
Fixed by 5cf8c9e951c21dcd5f5ac007e6bcd5b3160a26bb

**Comment by calintat** [comment]
Nice! What was the bug?

**Comment by NickHu** [comment]
Regular monotones were just being computed wrong in the recursive case of contraction (the bit that splits into subproblems by strongly connected component/unique singular contents).
