### ISSUE TITLE
Attach more inverses

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#827]
Suppose we have two invertible scalars $a, b$ and an invertible 3-cell $f : a \to b$ between them:

![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/190441918-d0133394-6438-4436-bbd6-344a48e93e50.svg) : ![homotopy_io_export](https://user-images.githubusercontent.com/16837293/190441753-b25463e4-7665-44c6-9a38-83bdea8e9ea7.svg) $\to$ ![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/190441778-19c73ec7-3829-40cf-8100-ac2f3fa7a543.svg)

Now if you have a diagram containing one scalar, you can click to attach $f$ or $f^{-1}$ and rewrite it into the other, that's fine. 

But if you have the inverse of one of the scalars, say $a^{-1}$, there is no way to rewrite it into $b^{-1}$, even though there is a 3-cell with that type, namely $f_* : a^{-1} \to b^{-1}$, the horizontal  inverse of $f$. We should make it possible to attach $f_*$ as well, not just $f$ and $f^{-1}$.

This is precisely what Manuel wants in #789.

**Comment by calintat** [comment]
As a workaround, you could construct $f_\*$ (which is now possible with the invert action) and then press "Theorem" to add an algebraic version of $f_\*$ to the signature which you could then attach. But that's a bit of a hassle.

**Comment by calintat** [comment]
@jamievicary I know Globular didn't do this, has that never been a problem?

**Comment by jamievicary** [comment]
We never did this in Globular. I agree that when a generator is invertible, there are scenarios in which it may make sense to attach some variant of it. However this could rapidly become unwieldy, a 2d scalar would then appear in 4 variants when you try to attach it (which cannot be completely distinguished visually), a 3d scalar could appear in 8 variants, etc.

**Comment by calintat** [comment]
That's a good point. 

However, with the invert action we have now opened the possibility of constructing all variants of a generator (except for scalars) in the tool. And they can be distinguished visually, e.g. here are the variants of a 2-cell:
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/190641355-9bde526a-d5a3-4452-bf94-bffc95c47ae3.svg) ![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/190641352-981389d4-9976-493c-a3d3-fd2c02b5f7b5.svg) ![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/190641351-79b38209-6dc4-4ca7-9445-68898c9f954a.svg) ![homotopy_io_export(3)](https://user-images.githubusercontent.com/16837293/190641342-df64f5ea-4511-4f9f-a31b-35b95857df80.svg)

So it feels very natural to allow these as attach options. Perhaps we could make an exception for scalars (which are easy to detect I think) since 1) they cannot be constructed in the tool with the invert action, and 2) cannot be distinguished visually.

If this proves too unwieldy, we could disable it by default and have it as an option for advanced users.

**Comment by doctorn** [comment]
We've spoken for a long time about depth-limiting attachment search and allowing users to increase the search depth if their desired attachment isn't found. This might be a good reason to finally get round to implementing that!

**Comment by calintat** [comment]
I think that's different? If you have an $(n + 1)$-diagram and you want to attach an $n$-generator, all the $2^n$ variants of that generator are still $n$-cells so they will be attached at the same depth.

**Comment by doctorn** [comment]
I mean depth as informally in the sense of 'how many variants are we willing to try'.

**Comment by mlharaujo** [comment]
> Suppose we have two invertible scalars a,b and an invertible 3-cell f:a→b between them:
> 
> ![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/190441918-d0133394-6438-4436-bbd6-344a48e93e50.svg) : ![homotopy_io_export](https://user-images.githubusercontent.com/16837293/190441753-b25463e4-7665-44c6-9a38-83bdea8e9ea7.svg) → ![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/190441778-19c73ec7-3829-40cf-8100-ac2f3fa7a543.svg)
> 
> Now if you have a diagram containing one scalar, you can click to attach f or f−1 and rewrite it into the other, that's fine.
> 
> But if you have the inverse of one of the scalars, say a−1, there is no way to rewrite it into b−1, even though there is a 3-cell with that type, namely f∗:a−1→b−1, the horizontal inverse of f. We should make it possible to attach f∗ as well, not just f and f−1.
> 
> This is precisely what Manuel wants in #789.

Yes, I think this is a much better way of phrasing what I was talking about! Ideally one should be able to attach all cells labelled by f, including f^{-1}, f_* and also its cups, caps etc. Although I also see the issue about the explosion of options.

**Comment by calintat** [comment]
> Yes, I think this is a much better way of phrasing what I was talking about! Ideally one should be able to attach all cells labelled by f, including f^{-1}, f_* and also its cups, caps etc. Although I also see the issue about the explosion of options.

Cups can already be attached, they are what we call "bubbles" -- but we should allow more bubbles instead of just the ones labelled by $f$ and $f^{-1}$. Caps don't need to be attached because they can be done by contraction.

**Comment by mlharaujo** [comment]
Ok, what I wrote wasn't clear, here is what I meant. Suppose I have $\alpha:f\to g$ all invertible. I want to attach the following thing. 
![20220916_173637](https://user-images.githubusercontent.com/36002049/190687998-62a6010b-3b68-4bda-8114-f10005b9fb0b.jpg)

**Comment by mlharaujo** [comment]
Nevermind, I just checked and I can actually do that just fine. The problem is when f is not a generator by a big composite diagram, which is the way I wanted to use this.

**Comment by calintat** [comment]
You could get around that by taking that composite diagram and pressing theorem.

**Comment by mlharaujo** [comment]
I have done that: $f$ is a composite diagram, $g$ is the Theorem cell and $\alpha$ is the proof cell. Now I want to do that attachment to transform the $g,g^{-1}$ cap into an $f,f^{-1}$ cap, which would be a big diagram with lots of caps for all the generators appearing in $f$.

**Comment by jamievicary** [comment]
Unfortunately that is far beyond our capabilities at the moment.

**Comment by calintat** [comment]
I am closing as "not planned" since it's not on the roadmap.

Actually with the change to contraction not allowing the transpose to be contracted, this is less relevant now.
