### ISSUE TITLE
Unit inverse contraction

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#828]
Suppose we have an invertible unit. Then you can definitely contract it and its inverse:

![homotopy_io_export](https://user-images.githubusercontent.com/16837293/190646786-bad3e851-c6ae-4e6f-8e1e-31d36b808733.svg)

Now consider this snake:

![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/190647055-25c565c3-b02c-4951-b8a5-3f6cf8d92290.svg)

This contracts to the picture above, but then if you try to annihilate them it fails with "label inconsistency".

**Comment by calintat** [comment]
Action dump leading to the buggy contraction:  [homotopy_io_actions.txt](https://github.com/homotopy-io/homotopy-rs/files/9584313/homotopy_io_actions.txt)

**Comment by calintat** [comment]
Thanks @doctorn for discovering this (or rather a slightly different version of this).

**Comment by NickHu** [comment]
This doesn't seem to happen if you contract the snake first. It seems that pulling the unit through the snake doesn't preserve its label neighbourhood.

**Comment by calintat** [comment]
Yes, sorry I should've explained that better.

**Comment by NickHu** [comment]
Indeed this does seem to be the case:
![image](https://user-images.githubusercontent.com/450276/190717682-b2392e0e-d354-4a06-8c6d-49cfe7c717af.png)
(Grey is the result, black is the original)

In fact, this problem can be observed even from this simple contraction:
![image](https://user-images.githubusercontent.com/450276/190717814-69540f5e-70bf-42ae-80b9-000b27208aa0.png)
The label corresponding to 3 is gone entirely, which is a big issue. I took this directly from the output of the tool. I don't think we observed this problem when we were thinking about how collapse should work on the board, so I would conclude that this is an implementation issue rather than a conceptual one.

**Comment by calintat** [comment]
It looks to me like this is a fundamental problem. If you compute the equivalence classes, the equivalence class for 3 is isolated in the middle so it basically disappears. This is very worrying.

**Comment by jamievicary** [comment]
Yes I agree an entire label class disappears. The conclusion in my view is that we should not allow this contraction. This is easy to detect: every equivalence class should "survive" in the contracted diagram.

**Comment by jamievicary** [comment]
If there was a weak unit present that would allow the transpose to be constructed correctly.

**Comment by doctorn** [comment]
From the diagrams Nick drew and my very fuzzy intuition it looks like the unit is only rotating a quarter turn and not a half turn. My expectation would be that this takes two moves to contract: the first performs a quarter turn leaving u in a 'cap-like' state where the left-hand input is a unit and the right-hand input is the wire; the second would then complete the yanking and straighten out. In this view 3 would survive the first quarter turn and consequently survive the second.

Is this total nonsense?

**Comment by NickHu** [comment]
@doctorn that's what Jamie means by allowing a weak unit. It makes perfect sense in the theory, but a design choice we made was to not allow for weak units in the tool (at least, so far), because it adds a lot of complexity to the term language.

**Comment by doctorn** [comment]
Oh wow! I'm very pleased I'm not completely lost! What would he involved in supporting weak units like this?

**Comment by NickHu** [comment]
It's analogous to giving up the property that every term is normalized; previously, we relied on this property to implement a sort of type checking, but now we're doing that in a different way and it might not be such an issue anymore. None of the design conflicts with supporting weak units (and arguably any such decision would be kind of wrong, theoretically), but there just hadn't been a compelling reason to do so yet, and if possible we should try to avoid it.

**Comment by calintat** [comment]
> Yes I agree an entire label class disappears. The conclusion in my view is that we should not allow this contraction. This is easy to detect: every equivalence class should "survive" in the contracted diagram.

I think we should just do typechecking, instead of an ad-hoc solution particular to this example. There could be other examples of illtyped contractions that this might not catch.

**Comment by jamievicary** [comment]
That could be the case. However I think it is certain that, if a contraction discards a particular label, it will never typecheck. So if we can check this at an earlier stage and reject the contraction early, that will be good.

**Comment by calintat** [comment]
I really think it's better and probably easier to just implement typechecking. And it would put us in a better place with regards to preventing bugs like this.

**Comment by calintat** [comment]
And checking that labels don't disappear is a crucial part of typechecking: the simplicial map from the neighbourhood to the canonical neighbourhood needs to be subjective.

**Comment by jamievicary** [comment]
I agree with you completely that typechecking would catch this, and that it would be good to implement typechecking. However a significant potential advantage of the labelled approach is that typechecking may ultimately be unnecessary -- that is, we may be able to achieve the property that if the collapse goes through, the resulting diagram is guaranteed to typecheck. Indeed there are good reasons to believe this should be possible. So to the extent that we can preserve this property within the collapse algorithm, and it is easy to do so, I think we should.

**Comment by doctorn** [comment]
Implementing type-checking doesn't preclude switching it off later if/when we're sure collapse doesn't produce ill-typed diagrams. It may also be useful for debugging anyway so I tend to agree with Calin that it's probably worth implementing.

**Comment by NickHu** [comment]
I think that both proposals lead to a theory in which this contraction of this shape doesn't exist:
> ![image](https://user-images.githubusercontent.com/450276/190717814-69540f5e-70bf-42ae-80b9-000b27208aa0.png)

I have a sketch of what this contraction might look like in the presence of weak units. I had thought that it would only be necessary to introduce a weak unit in the singularity of the contraction, but I think that's not sufficient. I think we would need weak units in the source of the contraction and the target generated by expansion also.

![image](https://user-images.githubusercontent.com/450276/190857479-a20038e4-c49b-4b60-9a36-27c2c7336cca.png)
![image](https://user-images.githubusercontent.com/450276/190857504-5a756025-fe8b-49f8-b163-ba94b0ea06d0.png)

It seems as though the expansion generated from contraction in this instance would not be unique, unless I made a mistake somewhere.

**Comment by calintat** [comment]
I'm at the airport and I had some time to sketch this down.

Basically, I think the contraction **should** be allowed and it should go as follows:

![IMG_054E593FF707-1](https://user-images.githubusercontent.com/16837293/190863501-b42c4232-8a1c-461b-a426-151034a71503.jpeg)

This is geometrically motivated and it also typechecks.

Now the question is how do we get this contraction. I don't think this requires any changes to collapse base as the cocone is already computed correctly. The problem is in collapse recursive. The way we compute the target diagram assumes that the forward/backward rewrites of the target cospan are equal to the side flanges (which is clearly not the case in this example). 

We observed something similar with the T-shaped DAGs but our solution to that was ad-hoc and doesn't apply here.

Honestly, I have no idea how we could solve this, which really worries me.

**Comment by jamievicary** [comment]
I don't think it type checks. Consider the tetrahedron constructed from the bottom left vertex in the source diagram (labelled x), and one of the bottom triangles on the right with boundary labels 1, 3, 5. This tetrahedron also has an edge labelled 2, the one that takes the point on the left to the highest dimensional generator. So we have a tetrahedron with 1, 3, 5, 2 among its edge labels. But no such tetrahedron can type check.

I maintain my earlier proposal: this does not contract, in the absence of the weak unit.

**Comment by jamievicary** [comment]
Nick thanks for your nice pictures, maybe you can explain next week in a meeting, I have some questions.

**Comment by calintat** [comment]
> I don't think this contraction would type check. Consider the tetrahedron constructed from the bottom left vertex in the source diagram (labelled x), and one of the bottom triangles on the right with boundary labels 1, 3, 5. This tetrahedron also has an edge labelled 2, the one that takes the point on the left to the highest dimensional generator. So we have a tetrahedron with 1, 3, 5, 2 among its edge labels. But no such tetrahedron can type check.
> 
> I maintain my earlier proposal: this does not contract, in the absence of the weak unit.

You're right. In that case, I agree with you that this **should not** contract.

**Comment by NickHu** [comment]
> Yes I agree an entire label class disappears. The conclusion in my view is that we should not allow this contraction. This is easy to detect: every equivalence class should "survive" in the contracted diagram.

I just realised that the contraction of a 1D endomorphism with its inverse does not satisfy this.

**Comment by calintat** [comment]
> > Yes I agree an entire label class disappears. The conclusion in my view is that we should not allow this contraction. This is easy to detect: every equivalence class should "survive" in the contracted diagram.
> 
> 
> 
> I just realised that the contraction of a 1D endomorphism with its inverse does not satisfy this.

So we should just do typechecking. The example in this issue does not typecheck because it has a simplex which is invalid.

**Comment by calintat** [comment]
Will be fixed by #703.

**Comment by calintat** [comment]
Now that we have typechecking, the following is no longer contractible:

![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/196003892-330ac9ae-d40e-4ef3-b686-8697727a1d0d.svg)

We agreed this is the desired result (as there is no way to make this contraction typecheck), so I am closing the issue.

**Comment by jamievicary** [comment]
Very good thank you Calin.
