### ISSUE TITLE
Alpha stops responding when manipulating complicated 5-diagram 

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#829]
In the attached workspace, I am trying to build a 5-diagram which consists of a triple figure 8: i make a figure 8 3-diagram, than a figure 8 4-diagram whose wires are figure 8 3-diagrams and then I want to repeat once more. When I start trying to perform the desired contractions to build this 5-diagram, the tool stops responding. It doesn't crash, so I guess it's just taking a long time to compute stuff. I don't know if there is anything that can be done about this. 
[fig8_boostrap (2).zip](https://github.com/homotopy-io/homotopy-rs/files/9585523/fig8_boostrap.2.zip)

**Comment by mlharaujo** [comment]
Now it's actually doing fine, maybe my computer was just a bit busy before.

**Comment by NickHu** [comment]
We have observed empirically (from the benchmark suite) that alpha is slower at contraction. This can probably be alleviated with some caching, but it seems a bit premature for that.

**Comment by jamievicary** [comment]
I think this is unsurprising given all these triangle collapse checks.

**Comment by regular-citizen** [comment]
Took the above .hom and and did some computation-heavy actions on top of it, then replayed it in homotopy-cli under a profiler.

My data seems to suggest that we could make alpha an
 awful lot faster if we had a better strip_labels implementation.
This is the relevant LOC:
https://github.com/homotopy-io/homotopy-rs/blob/d7cb3440604f1674003ef6d9f443bb9714b47062/homotopy-core/src/check.rs#L331-L334

The zip attached contains the actions and the .hom file, in case we ever need it again for benchmarking.
[heavy_proof.zip](https://github.com/homotopy-io/homotopy-rs/files/9593852/heavy_proof.zip)

**Comment by regular-citizen** [comment]
Obviously, I understand that we're not yet in a place to be doing performance work.
I mostly wished to flag this because it can probably be addressed entirely by data structure work.

**Comment by calintat** [comment]
> Took the above .hom and and did some computation-heavy actions on top of it, then replayed it in homotopy-cli under a profiler.
> 
> My data seems to suggest that we could make alpha an awful lot faster if we had a better strip_labels implementation. This is the relevant LOC:
> 
> https://github.com/homotopy-io/homotopy-rs/blob/d7cb3440604f1674003ef6d9f443bb9714b47062/homotopy-core/src/check.rs#L331-L334
> 
> The zip attached contains the actions and the .hom file, in case we ever need it again for benchmarking. [heavy_proof.zip](https://github.com/homotopy-io/homotopy-rs/files/9593852/heavy_proof.zip)

That function is only used in the well-formedness checks which we will turn off in the public version, so I wouldn't worry too much about that. Maybe you could rerun your analysis with the checks turned off (just disabled the "safety-checks" flag)?

**Comment by calintat** [comment]
At the moment we're not in a position to turn these off permanently as contraction is too buggy.

**Comment by regular-citizen** [comment]
> That function is only used in the well-formedness checks which we will turn off in the public version, so I wouldn't worry too much about that. Maybe you could rerun your analysis with the checks turned off (just disable the "safety-checks" flag)?

You seem to be correct, apologies for that. Runtime does go down significantly once I disable safety checks.
However, strip_labels does shows up in factorization, and that does not seem to be feature gated:
https://github.com/homotopy-io/homotopy-rs/blob/d7cb3440604f1674003ef6d9f443bb9714b47062/homotopy-core/src/factorization.rs#L18

Though those are not the calls to strip_labels that are most impacting the runtime, we could still realistically replace them with a Rewrite::equal_modulo_labels.

I reran the profiler on a release build with safety checks disabled. It keeps pointing me towards the following:
- Hashing seems to be dominating the runtime. In particular, we seem to be running an awful lot of std lib's hashes (SIP hashing algo). We could probably replace those by FxHash.
- We seem to be instantiating a silly number of Arcs, and dropping them has a cost.
- We seem to be doing expensive serde invocation somewhere inside the action update loop, which I cannot make sense of. Maybe it is a fluke of the profiler.

**Comment by NickHu** [comment]
> * Hashing seems to be dominating the runtime. In particular, we seem to be running an awful lot of std lib's hashes (SIP hashing algo). We could probably replace those by FxHash.

This is why we have: https://github.com/homotopy-io/homotopy-rs/blob/a1687b7c8ecd424f4f9a2ce4fe7bb4cdb71d4f79/homotopy-common/src/hash.rs#L8-L10
We should probably replace every instance of `std::collections::HashMap` that uses SIP hash with `FastHashMap` etc.

> * We seem to be instantiating a silly number of Arcs, and dropping them has a cost.

This happens internally in `hashconsing`. It's not ideal that it uses `Arc`s rather than `Rc`s, as our use case is single-threaded, but it doesn't seem to be easy to change. Moreover, eventually when we want to do multithreaded stuff they'll have to be `Arc`s anyway. Further examination also reveals that we're not configuring `HConsed`, which is internally backed by `HashMap`, to use FxHash instead of SIP hash (this is like a 3 line change).

**Comment by regular-citizen** [comment]
> It's not ideal that it uses `Arc`s rather than `Rc`s, as our use case is single-threaded, but it doesn't seem to be easy to change.

I'd be surprised if Arcs don't just become Rcs anyway when compiling to single-threaded wasm.
Still, there may be some Arc::clones in homotopy-core that we could manage to shave off, though it is probably not worth the effort.

> Moreover, eventually when we want to do multithreaded stuff they'll have to be `Arc`s anyway.

This is increasingly becoming the wrong issue to discuss this stuff, but I had half a mind to add a derive(Sync) for HConsed data structures when compiling to binary.
Obviously we still want to keep a !Sync when targetting web, but this would allow us to do multithreaded stuff in binaries (e.g. when testing or benchmarking).

**Comment by NickHu** [comment]
>     * Hashing seems to be dominating the runtime. In particular, we seem to be running an awful lot of std lib's hashes (SIP hashing algo). We could probably replace those by FxHash.

Done in becf5f251787e1fdf2b30c9a9ad637f4549406d1. We should probably use SIPHash in `homotopy-server` (eventually) to avoid hash DoS, but indeed FxHash is probably more appropriate everywhere else.
