### ISSUE TITLE
Beta broken, likely due to firebase-compat CORS failure

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#835]
Opening this in case it wasn't picked up.

Beta is broken on my machine (Firefox/Linux), in the sense that yew app doesn't even start.
For some reason an error in:
https://github.com/homotopy-io/homotopy-rs/blob/master/homotopy-web/static/index.html#L43
is stopping the yew app's main from running.

Console dump:
- Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.gstatic.com/firebasejs/9.7.0/firebase-performance-compat.js. (Reason: CORS request did not succeed). Status code: (null)
- Loading failed for the module with source “https://www.gstatic.com/firebasejs/9.7.0/firebase-app-compat.js”.
- Loading failed for the module with source “https://www.gstatic.com/firebasejs/9.7.0/firebase-analytics-compat.js”
- Module source URI is not allowed in this document: “https://www.gstatic.com/firebasejs/9.7.0/firebase-performance-compat.js”.
- Loading failed for the module with source “https://www.gstatic.com/firebasejs/9.7.0/firebase-auth-compat.js”.
- TypeError: error loading dynamically imported module

**Comment by H-Yulong** [comment]
It works fine on my VM (Firefox/Linux). Could it be some Firefox extension that blocks the request (see [this](https://stackoverflow.com/a/56970532)) ?

**Comment by regular-citizen** [comment]
You are correct, site loads fine if I disable UBlock Origin.

I'd be happy to close this issue now, but Ublock is a rather popular extension, so it would result in the site being broken for a lot of potential users. Should we consider at least documenting this?

**Comment by H-Yulong** [comment]
Yes we should definitely document this

**Comment by calintat** [comment]
> It might be as easy as catching any (relevant) error in "firebase.js" and printing on the dom "Failure to load firebase, disable privacy-oriented web extensions."

This sounds like a really good idea.

**Comment by H-Yulong** [comment]
> It might be as easy as catching any (relevant) error in "firebase.js" and printing on the dom "Failure to load firebase, disable privacy-oriented web extensions."

It is a bit harder than I expect -- JS doesn't allow me to catch import errors easily. I'll leave this task later.
