### ISSUE TITLE
Action dump is not deterministic due to "irrelevant" actions

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#836]
Some actions are marked as not relevant wrt the history, meaning they won't be added to the history:

https://github.com/homotopy-io/homotopy-rs/blob/a1687b7c8ecd424f4f9a2ce4fe7bb4cdb71d4f79/homotopy-model/src/proof.rs#L193-L202

However, these actions are needed to ensure an action dump is deterministic. For example, the `Attach` action depends on the current slice path, so the preceding `DescendSlice` and `SwitchSlice` actions make a difference to the result of `Attach`.

Here is a simple example illustrating this: [homotopy_io_actions.txt](https://github.com/homotopy-io/homotopy-rs/files/9611234/homotopy_io_actions.txt) (that attachment works if you go into slice S0 of the diagram).

**Comment by regular-citizen** [comment]
I feared this might happen. I would propose reverting a1687b7, and re-implementing it cleaning as part of a more substantial action-stuff PR.

**Comment by calintat** [comment]
Yes, that sounds reasonable. I will revert the commit now and then we can re-implement it as part of #837.

**Comment by calintat** [comment]
Done. Technically this is fixed now so I will close it. Once #837 is done, we can make sure this will never happen again.
