### ISSUE TITLE
Separate view state and proof state

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#837]
As suggested by Manuel in #830, it might be a good idea if undo/redo didn't change the current view of the workspace (i.e. which slice you're viewing).

To do this, I propose we split the "view state" consisting of the slice path and view dimension from the proof state, so that it's not stored in the history. Moreover, we could also include the attachment/slice highlight. Basically everything except `diagram` and `attach` in `Workspace`. 

https://github.com/homotopy-io/homotopy-rs/blob/a4cfd16d8e70e6382ce5e5c782ee12f975c98af9/homotopy-model/src/proof.rs#L42-L49

Perhaps we could combine this with the existing `View` struct.

https://github.com/homotopy-io/homotopy-rs/blob/a4cfd16d8e70e6382ce5e5c782ee12f975c98af9/homotopy-model/src/proof.rs#L30-L32

We would also need to have a separate class of "view actions" which update the view. These are precisely the actions that are marked as not relevant wrt history (so we could get rid of this function as all proof actions will be relevant):

https://github.com/homotopy-io/homotopy-rs/blob/a4cfd16d8e70e6382ce5e5c782ee12f975c98af9/homotopy-model/src/proof.rs#L193-L202

There are a few subtleties:
* We need to be careful about updating the view, as a change to the proof state (e.g. by undo/redo) can render the current view invalid so we need to update it accordingly.
* Some actions such as `Attach` depend on the current view, so we would need to refactor these actions so they don't depend on how you were viewing the workspace at the time of the action but rather encode that information as part of the action (e.g. see `Contract` and `Expand`). This is related to #836 and doing this would fix that.

This seems to have a lot of benefits, but it's a big refactoring job so we should definitely discuss this.

**Comment by doctorn** [comment]
I absolutely love this idea.

**Comment by regular-citizen** [comment]
I really like this as well, but I expect it will cause some problems labelled conflicts. Should we wait for labelled to be merged before implementing this?

**Comment by calintat** [comment]
Yes, let's wait for labelled to be merged, it's pretty much ready to merge now.

**Comment by calintat** [comment]
I have tried to implement this and I don't think it's a good idea anymore, therefore I am closing this as "not planned".

The issues with the action dump being non-determinist have already been fixed.
