### ISSUE TITLE
Cannot edit title after importing workspace

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#847]
Steps to reproduce:
1. Start a new project and set the title to "foo".
2. Import this workspace [bar.hom.zip](https://github.com/homotopy-io/homotopy-rs/files/9646374/bar.hom.zip) with title "bar".
3. Click to edit the title and try to change it back to "foo", this doesn't work!

You can also reproduce this if you replace "foo" with the empty string and try to delete the title in step 3.

I think the problem is that the `ProjectView` holds a copy of the metadata which is not updated correctly after an import.

**Comment by calintat** [comment]
Actually I don't understand why we have this copy of the metadata in the first place:

https://github.com/homotopy-io/homotopy-rs/blob/48e90e012d307bceb13e28e182acadffabf377ff/homotopy-web/src/app/project.rs#L24-L30

Am I missing something?

**Comment by calintat** [comment]
The copy can also become out-of-sync after an undo/redo.

**Comment by H-Yulong** [comment]
I followed the steps but didn't managed to reproduce the problem?

**Comment by calintat** [comment]
Weird, I just tried it again and I can still reproduce it. How about this:

1. Set title to "foo".
2. Undo.
3. Set title to "foo" again.

**Comment by calintat** [comment]
Anyway I have come up with a fix so I will push that soon.
