### ISSUE TITLE
Colimit recursive chooses the wrong boundary

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#875]
Most likely related to the other bugs about label corruption and hopefully easier to debug!

1. Start with a scalar and compose it horizontally with a weak unit:
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/195864161-817321e0-2f07-4973-84e5-137a75c383e4.svg)
2. Do a contraction in a singular slice:
![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/195864299-1d98af2a-b9ef-4fb6-b964-861e4a3d5861.svg)
3. Now go in slices R0 and R1 and do a contraction:
![homotopy_io_export(2)](https://user-images.githubusercontent.com/16837293/195864381-27ec523a-a42e-4b02-a22a-aecc20250f82.svg)
4. Contract the whole diagram. The result is a corrupted scalar.

**Comment by calintat** [comment]
The following contraction is the culprit as it doesn't typecheck:

![homotopy_io_export](https://user-images.githubusercontent.com/16837293/195864161-817321e0-2f07-4973-84e5-137a75c383e4.svg) ![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/195864299-1d98af2a-b9ef-4fb6-b964-861e4a3d5861.svg)

**Comment by jamievicary** [comment]
This is our classic example which we have thought about many times theoretically, right? I'm sure we worked this out in great detail. It will be very interesting to see why this apparently does not typecheck.

**Comment by calintat** [comment]
You're right, this does indeed typecheck. There was a small bug in typechecking which I've now fixed.

The culprit is actually this contraction:
![homotopy_io_export(1)](https://user-images.githubusercontent.com/16837293/196159400-242a689a-3df1-4264-ae07-e77b3d1d8f7f.svg)
![homotopy_io_export](https://user-images.githubusercontent.com/16837293/196159409-ad45e0ef-50fe-4be7-ae73-7c2dd1ddb0ee.svg)

**Comment by jamievicary** [comment]
Wonderful.

**Comment by calintat** [comment]
OK I debugged this and I think this is a bug in collapse recursive.

Consider the following contraction (a scalar on weak units composed with a weak unit):
 
![IMG_1905BBE1B864-1](https://user-images.githubusercontent.com/16837293/196185908-fdc40214-ccdf-4d64-bae6-45e9ea78ba0f.jpeg)

The result of collapse base is correct but it goes wrong when we reconstruct the diagram. I think it's related to the discussion we had about choosing the boundary correctly. We never came up with a principled way to do it...

**Comment by jamievicary** [comment]
Hmm interesting. It sort of makes sense -- we can only see after the contraction what the "true" boundary is.

The target diagram has a left x and right x in the singular slice. We essentially have to select these from the x's in the first and second column respectively of the left image. Once we've chosen where these x's "come from", that determines these labels.

In this case the correct answer is to choose the isolated x's in the left image, i.e. the ones at the same height as the $\alpha$. The reason this is correct is that these x's are isolated from both boundaries. So we could perhaps switch to a heuristic like this for now.

**Comment by jamievicary** [comment]
I agree with you. So how about this: choose the same height as the highest dimensional generator. (Or, choose any such height, if there are multiple.)

**Comment by NickHu** [comment]
This description is a bit vague; for one thing, this happens in the recursive colimit computation, so each node actually represents an arbitrary $n$-diagram. I guess we want to choose the one which will contain the max dimensional generator, which is a bit more annoying to implement.

**Comment by calintat** [comment]
This seems to be resolved as far as I can tell.

**Comment by jamievicary** [comment]
Great, what method did you choose?
