### ISSUE TITLE
Non-determinism in collapse

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#879]
Consider a counit on an endomorphism:

![homotopy_io_export(5)](https://user-images.githubusercontent.com/16837293/196673030-06004ad7-70e8-463a-bcb6-951ddc82f8e3.svg) :  ![homotopy_io_export(6)](https://user-images.githubusercontent.com/16837293/196673041-02f0340c-4ec7-4976-9b51-da1c61888d84.svg) $\rightarrow$ ![homotopy_io_export(7)](https://user-images.githubusercontent.com/16837293/196673051-c656aa7e-61ce-4138-b0b0-51ed1e01fe62.svg)

Now try to contract the counit with a weak identity:

![homotopy_io_export(8)](https://user-images.githubusercontent.com/16837293/196673178-ac41fe7a-8e82-43e4-a910-76a36407b7d3.svg)

This causes collapse to crash with "non-determinism in collapse; edge has become uncollapsible: label inconsistency".

It is possible that our proposed change to label generation will fix this, so let's wait and see.

**Comment by jamievicary** [comment]
Thanks for discovering this Calin.

**Comment by calintat** [comment]
The label inconsistency is fixed now, but the contraction doesn't typecheck due to the issue #875.
