### ISSUE TITLE
Attachment behaves wierdly

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#892]
If you start with an endomorphism 2-cell and click on the right, the tool presents you with two ways to attach an identity.

<img width="1348" alt="Screenshot 2022-11-02 at 09 43 03" src="https://user-images.githubusercontent.com/16837293/199456903-9df13e1d-b05f-4ccb-8959-45537f1ce6b0.png">

**Comment by calintat** [comment]
I think this might be to our recent changes to labels.

**Comment by calintat** [comment]
Maybe the function which searches for embeddings needs to be updated to use the label equivalence rather than just plain equality?

**Comment by NickHu** [comment]
Another potential solution is to apply a uniqueness filter to the attachment list

**Comment by jamievicary** [comment]
You mean "attach Cell 1" rather than "attach an identity" presumably?

I don't see why this should occur. The system should search for attachments to the codim-2 target of the diagram. This is a 0-diagram. There is only one possible attachment.

**Comment by NickHu** [comment]
Fixed by 23e57c2224ff262e2b9e12fde2e452500700721f
