### ISSUE TITLE
3D graphics library choice

### ISSUE THREAD

**Issue by Akvile1206** [homotopy-io/homotopy-rs#90]
Features required for homotopy.io (from the most basic to the most advanced):

- Given a mesh (vertex, vertex normal, colour buffers), light descriptions, get a picture of that mesh in a scene.
- Rapidly switch between meshes for an animation.
- Let the user zoom, pan, rotate the camera in the scene to inspect 3D surfaces.

Most promising graphics libraries are thus:

- [luminance](https://github.com/phaazon/luminance-rs) is an OpenGL library that has a decent set of examples that achieve the desired features ([preloading frames](https://github.com/phaazon/luminance-rs/blob/master/luminance-examples/README.md#07--offscreen), [basic interactivity](https://github.com/phaazon/luminance-rs/blob/master/luminance-examples/README.md#14--skybox-and-environment-mapping)). It is low level compared to something like Three.JS, so getting started will be difficult, but is likely to result in a very good performance. There are a few other similar level libraries, but this one wins out in terms of documentation, completeness and support.
- [kiss3d](https://github.com/sebcrozet/kiss3d) is a higher-level library advertising quick start but not guaranteeing as good of the performance (might be noticeable for the rapidly changing frames). Seems that the basic interactivity feature comes [by default](http://kiss3d.org/doc/kiss3d/camera/struct.ArcBall.html). Controls can be overwritten, but if we need something more elaborate better use a lower level framework. The author seems to have used the framework to create quite an elaborate [web graphics application](https://www.nphysics.org/all_examples3/) which is encouraging.

Let me know if there are other use cases to consider and your thought on these graphic libraries.

**Comment by jamievicary** [comment]
What about bare metal, i.e. no library. I've written Javascript pure WebGL before and it's not very hard. We're not doing anything massively complicated. (Relatively simple models and textures, minimal interaction.)

**Comment by Akvile1206** [comment]
Would this be more performant? I was thinking that the graphics libraries would have efficient implementations for animation and interaction with objects. I fear that implementing these features from scratch would require figuring out how to optimise them as well. 
Of course, if you say it will win us on productivity I am inclined to believe you. I have not written WebGL shaders, so do not know how steep is the learning curve.

**Comment by doctorn** [comment]
Not entirely sure what kind of interaction we want to support, but from my (very limited) experience with homotopy.io, I can't really imagine animation / interaction doing anything crazy enough to warrant serious optimisations. Obviously I have no idea, but in my head, worst case scenario is we spend an afternoon optimisng memory layouts for animation frame-data?

I can't comment on productivity either but can promise the WebGL learning curve won't be as bad as Rust's :stuck_out_tongue_closed_eyes:

**Comment by jamievicary** [comment]
@Akvile1206: Our animations will be achieved by updating the vertex coordinates each frame, and then changing the geometry at certain keyframes. These simple procedures, and I don't see any reason why a library could give you better performance than doing the WebGL directly.

Regarding shaders, we can start with something simple stolen from the internet and go from there.
