### ISSUE TITLE
Possible typechecking bug

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#902]
Start with an endomorphism on the circle and compose with the circle birth and death:

![homotopy_io_export(4)](https://user-images.githubusercontent.com/16837293/201469044-945b828f-fc20-4d47-be7c-128ad0a5d6b7.svg)

Now contract either the top or bottom, this goes through (I'm not sure it should):

![homotopy_io_export(5)](https://user-images.githubusercontent.com/16837293/201469056-735ae385-4fb0-4de3-92e3-dac58743c42f.svg)

Now if we contract again, it doesn't typecheck.

**Comment by calintat** [comment]
I don't think the first contraction should go through because we're losing labels.

**Comment by calintat** [comment]
Fixed by 25f5f8eab66efa99ea08076658d12649d6f63f5f

**Comment by jamievicary** [comment]
Thanks Calin, what was the issue here?

**Comment by calintat** [comment]
When doing a contraction, we were previously only checking that the cospan is well-typed. Now we are also checking that the target of the contraction is well-typed (the source is assumed to be well-typed). In this example, the target does *not* typecheck (because it's missing some labels) even though the whole cospan does.

**Comment by jamievicary** [comment]
Ah yes that's definitely necessary. Thanks for explaining.

**Comment by calintat** [comment]
Honestly I had just assumed we were already doing that, this bit of code is inherited from beta where I guess this was never necessary.
