### ISSUE TITLE
Problem with rendering of 5-diagram

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#906]
In this workspace the rendering of the 5-diagram is not working properly. There should be wires.

![image](https://user-images.githubusercontent.com/36002049/202755089-0a731af0-0bf2-4f2d-b177-638d5839b817.png)
[rendering_bug.zip](https://github.com/homotopy-io/homotopy-rs/files/10043087/rendering_bug.zip)

**Comment by calintat** [comment]
The problem was simpler than I thought. We just forgot to cycle the codimension numbers. The missing wires in the picture have codimension 3 but since we only define colours for codimensions 0, 1, and 2, the wires were just invisible.
