### ISSUE TITLE
Dragging does not create braid

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#907]
Clicking the second wire from the left (at height = Regular 2) and dragging left should produce a braid.

![image](https://user-images.githubusercontent.com/36002049/202755595-6d66d082-d0f1-499d-9fa5-ef0fec3781e8.png)

[butterfly.zip](https://github.com/homotopy-io/homotopy-rs/files/10043113/butterfly.zip)

**Comment by calintat** [comment]
Fixed by c2232ddf5e1e8bca4098ec8cdb4fb5aa3f37e9ba

@NickHu would you mind making this into a test?
