### ISSUE TITLE
Autosave feature

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#912]
It would be good to have an autosave feature, probably not too hard to implement either.
It would trigger after a period of no interaction (e.g. 15 seconds), and save to localStorage. This could be helpful for development too - we could have the state persist across reloads by serializing to/from localStorage.

**Comment by regular-citizen** [comment]
I was considering looking into a rehidration mode. Basically, some trigger would save the current state of the prover into storage and on refresh it would attempt to deserialise whatever it found in the store, and if that failed, it would fall back to an empty workspace.

I think it could cause a few unintended problems relating to stale caches though, especially with upcoming features such as the server implementation. For instance, how should we deal with login state in conjunction with this?

**Comment by regular-citizen** [comment]
Also the other thing to watch out for is performance impacts. Serialising big diagrams is non-trivial amounts of work, so this could add significant overhead to the tool. I'm in general still in favour of the idea, just mentioning potential downsides.

**Comment by NickHu** [comment]
IndexedDB is the way to go as localStorage has a 5MB limit and only supports strings.

**Comment by NickHu** [comment]
Implemented in 7e253a5e2d70f1b9a028f0154432febba48ffe16.

There's a small visual bug that loading an autosave seems to make everything black coloured (something to do with the signature stylesheet perhaps?) but this fixes itself after any action which causes a rerender. There's also no UI to clear/manage autosave(s).

**Comment by calintat** [comment]
I fixed the issue with the stylesheet, it just needs to be updated whenever the proof state changes.

**Comment by NickHu** [comment]
One very easy thing to do is to show a toast when autosaving begins and also one when it completes, we should probably do that and then we'll have a positive notification in the tool.
