### ISSUE TITLE
"Working..." spinner

### ISSUE THREAD

**Issue by NickHu** [homotopy-io/homotopy-rs#913]
It's not very clear when the tool is doing something currently, and due to the synchronous nature this means that people might try to trigger stuff while the tool is blocked.

**Comment by NickHu** [comment]
Implemented in bbec3d2308f7c7eb5d47433d338463fc94a6d252.

I'm not entirely happy with this:
https://github.com/homotopy-io/homotopy-rs/blob/bbec3d2308f7c7eb5d47433d338463fc94a6d252/homotopy-web/src/app.rs#L182

I needed to do it to force Yew to rerender, but there must surely be a better way.

**Comment by calintat** [comment]
I just tried this and I can't attach anything now because it crashes with "callback contains `FnOnce` which has already been used".

**Comment by NickHu** [comment]
Fixed in 81d69a8ee8fb05461058b2d7e1b92a38601484d0
