### ISSUE TITLE
Allow making a generator non-invertible

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#916]
With the recent changes to diagram neighbourhoods, I think it is now feasible to allow a UI option to make invertble generators non-invertible. (This is currently disallowed.) We can now detect whether this is allowed, by scanning the entire signature & workspace to check if the generator in question is ever used with orientation number different to +1.

**Comment by calintat** [comment]
Sounds good to me!

**Comment by jamievicary** [comment]
Do you agree this would be sound? I think that with the current boundary model, invertible generators cannot appear in a nonstandard configuration if all config numbers are +1.

**Comment by calintat** [comment]
What do you mean by boundary model?

I agree that as long as a generator doesn't appear with orientation number 0 or -1, we can safely make it non-invertible.

**Comment by jamievicary** [comment]
By "boundary model" I mean the way we are currently assigning labels to the boundary of a generator.

**Comment by calintat** [comment]
Ok I see.
