### ISSUE TITLE
Loading of autosave makes it hard to start a fresh workspace

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#919]
I want to start an empty workspace, but when I open beta.homotopy.io it automatically loads what I was working on before. The only solution I have found is to manually delete every cell in the signature.

**Comment by calintat** [comment]
You can press undo to revert the loading from auto save.

**Comment by jamievicary** [comment]
Calin's fix is easy to apple, but thanks Manuel we agree this is not ideal behaviour. We discussed this before and decided the solution was to use session storage instead of local storage.

**Comment by jamievicary** [comment]
Will assign Nick for now but please reassign if I misremembered

**Comment by calintat** [comment]
I looked into this a bit and I don't think we can easily switch to session storage. It has a limit of 5MB and we may need more than that for large proofs. At the moment we're actually not using local storage (which also has this limit) and instead we're using IndexedDB which has a much bigger limit and has a much nicer asynchronous API. Switching to something else is not worth the effort.

**Comment by NickHu** [comment]
To be clear, my suggestion was not to move the autosaving to session storage (this would be useless as it would just disappear when the tab gets closed), but rather to write some kind of token which specifies whether or not to load (which) autosave to session storage

**Comment by NickHu** [comment]
We should also have a new workspace button

**Comment by calintat** [comment]
I think it should disappear when the tab is closed. If you try to close a tab, a confirmation/warning dialog shows up so if you actually close the tab then clearly you're done with that proof. But if a crash happens and you refresh the tab the proof should survive.

**Comment by calintat** [comment]
> We should also have a new workspace button

Once the server is implemented we need this anyway. But I don't see how this would work with the autosave.

**Comment by calintat** [comment]
How about instead of automatically loading the proof from autosave when you start the app, we show a toast with the message "Do you want to load proof from autosave" and a button "Yes".  This way it's only a UI change and we don't need to spend too much time on this.

**Comment by calintat** [comment]
The autosave feature is causing too many problems, so I have decided to bin it.
