### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mlharaujo** [homotopy-io/homotopy-rs#926]
In the attached workspace, click the second crossing from the bottom and drag left to produce a crash. Attaching .hom and action log.

![image](https://user-images.githubusercontent.com/36002049/205072884-337b1c4a-d24f-46a1-bf21-ad923065d367.png)
[crash.zip](https://github.com/homotopy-io/homotopy-rs/files/10133018/crash.zip)

**Comment by calintat** [comment]
This was indeed the same issue as #947 and was fixed by 50b209c442ca5370ab8eb64c32ae7b305a146a67.
