### ISSUE TITLE
Change between 2D and 3D renderer by clicking an appropriate V or P in the dimension controls

### ISSUE THREAD

**Issue by jamievicary** [homotopy-io/homotopy-rs#96]
Suppose you're viewing a slice of a slice of a 7D diagram in the 2D viewer. The dimension controls will look like this:

   * $\star$ R3 S2 V V P P P

Then clicking the first P should change to the 3D viewer, and the dimension controls should look like this:

   * $\star$ R3 S2 V V V P P

**Comment by NickHu** [comment]
I think this is done now
