### ISSUE TITLE
Problem with snapshots with phantom data failing

### ISSUE THREAD

**Issue by regular-citizen** [homotopy-io/homotopy-rs#967]
Issue opened to move the discussion started in d986012b5b4633a1f92ca7903832a04080ab3154.

Since the recent flake update, for some reason the snapshot testing is behaving differently on linux (my machine and the CI) and darwin (@calintat laptop). The issue seems to boil down to phantom data being printed differently.

**Comment by calintat** [comment]
But it seems the CI is consistent with my laptop, right?

**Comment by calintat** [comment]
Actually I'm quite confused how both the flake update and my commit pass the CI since they have different snapshots.

**Comment by calintat** [comment]
I checked the Debug implementation of PhantomData and it's not consistent with what I'm seeing on my machine.

https://doc.rust-lang.org/nightly/src/core/fmt/mod.rs.html#2611-2613

**Comment by regular-citizen** [comment]
> https://doc.rust-lang.org/nightly/src/core/fmt/mod.rs.html#2611-2613

This is the nightly implementation though. Aren't we on stable? Could it be that?
