### ISSUE TITLE
Keyboard shortcuts menu

### ISSUE THREAD

**Issue by calintat** [homotopy-io/homotopy-rs#977]
It would be good to have a menu listing all available keyboard shortcuts. This could be opened with a keyboard shortcut from Chiara's empty workspace view (I was gonna suggest "?" but that's already used for the tutorial).

**Comment by NickHu** [comment]
I would suggest that we use `?` for this, and not have a binding for opening the tutorial (instead, just make the word "tutorial" a hyperlink in the onboarding screen - this has another benefit in that there's no way to use keyboard shortcuts, and therefore currently open the tutorial, on touch devices).

**Comment by calintat** [comment]
I'm working on this btw (just so no one else does).

**Comment by regular-citizen** [comment]
Quiver does a similar thing, if you need inspo for design:
![image](https://user-images.githubusercontent.com/7887982/212673849-c347d722-ef29-4d89-8797-6dd871508d86.png)

**Comment by calintat** [comment]
I basically implemented something similar:
<img width="1436" alt="Screenshot 2023-01-16 at 13 18 59" src="https://user-images.githubusercontent.com/16837293/212687752-82d3f5d9-fdaa-426c-98d4-3c8d9b41a6ad.png">

You can open this with the "?", which means there is no way to open it on a touch device sadly.
