### ISSUE TITLE
"no attachment found" when trying to add the top half of a bubble

### ISSUE THREAD

**Issue by Negabinary** [homotopy-io/homotopy-rs#993]
[homotopy_io_export (3).zip](https://github.com/homotopy-io/homotopy-rs/files/10520640/homotopy_io_export.3.zip)

I have one 0-cell and one 2-cell "string" which is invertible. I open the 2-cell, press I, and then press to the right of the workspace to add an inverse "string" to the right. 

I can now add the bottom half of a bubble to the bottom of the diagram if I wish, but I cannot add anything to the top. (If I want the top half of a bubble I have to create the whole bubble and foot it.)

**Comment by calintat** [comment]
Unless I misunderstood what you meant?

**Comment by Negabinary** [comment]
oh interesting, yep that works! - sorry I didn't realise you could shift-drag.

I guess the thing that tripped me up was that I could make the bottom half bubble by just clicking at the bottom, but I can't get the top half bubble by just clicking at the top - is that the way it's meant to work?

**Comment by calintat** [comment]
Yes, it's sightly annoying that you can attach that half-bubble at the bottom, it's not really something you'd want to do since you can just contract to form the half-bubble, but it's a consequence of how we handle the insertion of bubbles.
